export const DAY_CYCLE_DURATION=1200;
export const ENVIRONMENT_CONFIG={dayCycleDuration:DAY_CYCLE_DURATION,weatherWindow:240,weatherBlend:18,rainChance:.56,clearRunChance:.18,puddleMultiplier:1.8,wetDrying:45,rainDrops:140,headlightRange:145,nightAmbient:.28};
export const SKY_STATES={MORNING:{top:[.38,.62,.84],horizon:[.78,.84,.88],light:[.86,.91,1.0],ambient:.88},DAY:{top:[.31,.62,.87],horizon:[.79,.87,.94],light:[1,1,.98],ambient:1},EVENING:{top:[.27,.34,.56],horizon:[.91,.62,.38],light:[1,.78,.64],ambient:.65},NIGHT:{top:[.025,.045,.10],horizon:[.11,.15,.23],light:[.53,.65,.86],ambient:.28},OVERCAST:{top:[.24,.30,.38],horizon:[.57,.62,.66],light:[.78,.85,.93],ambient:.78}};
const DAY_KEYFRAMES=[[0,'NIGHT'],[5,'NIGHT'],[7,'MORNING'],[11,'DAY'],[16,'DAY'],[19,'EVENING'],[22,'NIGHT'],[24,'NIGHT']];
const WET_SURFACES={ASPHALT:[.94,.82],GRASS:[.88,.65],DIRT:[.95,.89],SOFT_DIRT:[.93,.86],MUD:[.95,.90],ROCK:[.97,.94],WATER:[1,1]};
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=v=>{v=clamp(v);return v*v*(3-2*v);},mix=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t);
function random(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
export class Environment{
 constructor(seed,config=ENVIRONMENT_CONFIG){this.config=config;this.reset(seed);}
 reset(seed){this.seed=seed>>>0;this.time=0;const r=random(this.seed^0x6c8e9cf5);this.startHour=7+r()*2;this.allowRain=r()>this.config.clearRunChance;this.wetness=0;this.rainIntensity=0;this.forceWeather=null;this.forceHour=null;this.window=-1;this.update(0);}
 windowPlan(index){const r=random(this.seed^Math.imul(index+1,0x85ebca6b));return{rain:this.allowRain&&r()<this.config.rainChance,start:25+r()*45,duration:70+r()*100,intensity:.4+r()*.6};}
 update(dt){this.time+=Math.max(0,dt);const index=Math.floor(this.time/this.config.weatherWindow),within=this.time%this.config.weatherWindow;if(index!==this.window){this.plan=this.windowPlan(index);this.window=index;}const p=this.plan,target=p.rain?p.intensity*smooth((within-p.start)/this.config.weatherBlend)*smooth((p.start+p.duration-within)/this.config.weatherBlend):0;this.rainIntensity=this.forceWeather==='RAIN'?.85:this.forceWeather==='CLEAR'?0:target;this.weatherState=this.rainIntensity>.025?'RAIN':'CLEAR';this.wetness+=(this.rainIntensity-this.wetness)*(1-Math.exp(-Math.max(0,dt)/(this.rainIntensity>this.wetness?12:this.config.wetDrying)));this.hour=this.forceHour??((this.startHour+this.time/this.config.dayCycleDuration*24)%24);
 const frames=DAY_KEYFRAMES;let a=frames[0],b=frames[1];for(let i=0;i<frames.length-1;i++)if(this.hour>=frames[i][0]&&this.hour<frames[i+1][0]){a=frames[i];b=frames[i+1];break;}const blend=smooth((this.hour-a[0])/(b[0]-a[0])),A=SKY_STATES[a[1]],B=SKY_STATES[b[1]],rain=this.rainIntensity,over=SKY_STATES.OVERCAST;this.timeOfDay=this.hour<5||this.hour>=22?'NIGHT':this.hour<10?'MORNING':this.hour<17?'DAY':this.hour<21?'EVENING':'NIGHT';const dayLight=A.ambient+(B.ambient-A.ambient)*blend;this.skyTop=mix(mix(A.top,B.top,blend),over.top.map(v=>v*dayLight),rain*.78);this.skyHorizon=mix(mix(A.horizon,B.horizon,blend),over.horizon.map(v=>v*dayLight),rain*.66);this.lightColor=mix(mix(A.light,B.light,blend),over.light,rain*.35);this.ambient=(A.ambient+(B.ambient-A.ambient)*blend)*(1-rain*.18);this.headlights=this.hour>=17.5||this.hour<6.5||rain>.025;this.puddleMultiplier=1+(this.config.puddleMultiplier-1)*rain;this.fogStart=300-this.rainIntensity*55-(1-this.ambient)*90;this.fogEnd=540-this.rainIntensity*55-(1-this.ambient)*65;return this;}
 surface(surface){const wet=this.wetness;if(wet<.00001)return surface;const type=surface.surfaceType,settings=WET_SURFACES[type]||WET_SURFACES.WATER;return{...surface,wetness:wet,surfaceState:type+(wet>.15?'_WET':''),longitudinalGrip:surface.longitudinalGrip*(1-(1-settings[0])*wet),lateralGrip:surface.lateralGrip*(1-(1-settings[1])*wet),rollingResistance:surface.rollingResistance+(type==='MUD'?.035*wet:0),effectMultiplier:surface.effectMultiplier*(type==='WATER'?1+this.rainIntensity*.30:1)};}
}
// Fixed-size local rain volume, updated without physics bodies or per-frame allocations.
export class RainField{
 constructor(seed=1){this.drops=Array.from({length:ENVIRONMENT_CONFIG.rainDrops},()=>({x:0,y:0,z:0,length:0}));this.reset(seed);}
 reset(seed){this.random=random(seed^0x736ab1);for(const p of this.drops){p.x=(this.random()-.5)*44;p.y=this.random()*18;p.z=(this.random()-.5)*44;p.length=.45+this.random()*.45;}this.count=0;}
 update(dt,intensity,speed){this.count=Math.min(this.drops.length,Math.round(this.drops.length*intensity*(1+Math.min(1,speed/120)*.25)));for(let i=0;i<this.count;i++){const p=this.drops[i];p.y-=(14+intensity*8)*dt;p.x-=dt*1.5;if(p.y<0){p.y=18;p.x=(this.random()-.5)*44;p.z=(this.random()-.5)*44;}}}
}
