export const EVENT_AUDIO_CONFIG={voices:10,maxGain:.68,globalCooldown:.035,pitchVariation:.05,variants:4};
const impacts={TREE_HIT:{group:'wood',frequency:92,filter:1600,duration:.24},TREE_BREAK:{group:'break',frequency:130,filter:2400,duration:.20},FENCE_HIT:{group:'wood',frequency:145,filter:3000,duration:.17},SIGN_HIT:{group:'metal',frequency:790,filter:3900,duration:.32},HOUSE_HIT:{group:'body',frequency:58,filter:700,duration:.32},TRAFFIC_HIT:{group:'npc',frequency:100,filter:1800,duration:.36},HARD_LANDING:{group:'ground',frequency:85,filter:600,duration:.22},ROLLOVER_IMPACT:{group:'body',frequency:115,filter:1600,duration:.26}};
impacts.mudSplash={group:'surface',frequency:75,filter:900,duration:.18};impacts.waterSplash={group:'surface',frequency:0,filter:4200,duration:.26};
impacts.COW_HIT={group:'animal',frequency:65,filter:850,duration:.38};
const melodies={COW_MOO:[140,125,110],CHICKEN_HIT:[880,740,1040,660],FUEL_PICKUP:[440,660,880],REPAIR_PICKUP:[523,784,1046],BEER_PICKUP:[330,495,660],BEER_USE:[392,494,587,784,988]};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export class EventAudio{
 constructor(engine,feedback){this.engine=engine;this.voices=[];this.cooldowns={};this.rng=9237;this.lastGlobal=-10;this.lastCue=null;this.disabled=false;this.unsubscribe=feedback.onEvent(e=>this.play(e));}
 random(){this.rng=(Math.imul(this.rng,1664525)+1013904223)>>>0;return this.rng/4294967296;}
 init(){if(this.voices.length||this.disabled)return !!this.voices.length;const ctx=this.engine.ctx;if(!this.engine.started||!ctx)return false;try{this.master=ctx.createGain();this.master.gain.value=EVENT_AUDIO_CONFIG.maxGain;if(ctx.createDynamicsCompressor){this.limiter=ctx.createDynamicsCompressor();this.limiter.threshold.value=-9;this.limiter.knee.value=5;this.limiter.ratio.value=12;this.limiter.attack.value=.003;this.limiter.release.value=.10;this.master.connect(this.limiter).connect(ctx.destination);}else this.master.connect(ctx.destination);const buffer=ctx.createBuffer(1,Math.floor(ctx.sampleRate),ctx.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=this.random()*2-1;
 for(let i=0;i<EVENT_AUDIO_CONFIG.voices;i++){const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.Q.value=.6;filter.connect(this.master);const tone=ctx.createOscillator(),ring=ctx.createOscillator(),noise=ctx.createBufferSource(),toneGain=ctx.createGain(),ringGain=ctx.createGain(),noiseGain=ctx.createGain();tone.type='triangle';ring.type='sine';noise.buffer=buffer;noise.loop=true;toneGain.gain.value=ringGain.gain.value=noiseGain.gain.value=0;tone.connect(toneGain).connect(filter);ring.connect(ringGain).connect(filter);noise.connect(noiseGain).connect(filter);tone.start();ring.start();noise.start();this.voices.push({tone,ring,noise,filter,toneGain,ringGain,noiseGain,until:0});}return true;}catch{this.disabled=true;return false;}}
 envelope(param,peak,now,duration,attack=.008){param.cancelScheduledValues(now);param.setValueAtTime(.00001,now);param.linearRampToValueAtTime(Math.max(.00001,peak),now+attack);param.exponentialRampToValueAtTime(.00001,now+duration);}
 play(event){if(!this.engine.enabled||this.engine.ctx?.state!=='running')return false;const impact=impacts[event.type],notes=melodies[event.type];if(!impact&&!notes)return false;if(!this.init())return false;
 const now=this.engine.ctx.currentTime,group=notes?'pickup':impact.group,cooldown=notes?.08:group==='ground'?.26:group==='surface'?.28:.17;if(now-(this.cooldowns[group]??-10)<cooldown||(now-this.lastGlobal<EVENT_AUDIO_CONFIG.globalCooldown&&!this.lastCue?.surface))return false;const voice=this.voices.find(v=>v.until<=now);if(!voice)return false;
 const water=event.type==='waterSplash',waterDepth=clamp(event.waterDepth||0,0,.3),waterSpeed=clamp((event.speed||0)/30,0,1);const variant=Math.floor(this.random()*EVENT_AUDIO_CONFIG.variants),pitch=1+(this.random()-.5)*EVENT_AUDIO_CONFIG.pitchVariation*2,strength=clamp((event.impulse||0)/28000,0,1),volume=water?clamp(.025+waterSpeed*.16+waterDepth/.24*.11,.025,.32):event.type==='COW_MOO'?.09:event.type==='CHICKEN_HIT'?.14:impact?.group==='surface'?clamp((event.intensity||0)/150,.02,.14):notes?.34:clamp(.035+Math.sqrt(strength)*.47,.035,.50),duration=water?.12+waterDepth*.7+waterSpeed*.12:notes?(event.type==='BEER_USE'?.8:.30):impact.duration*(.9+variant*.06),frequency=notes?notes[0]:impact.frequency*[.91,1,1.09,.96][variant]*pitch;
 try{voice.filter.type=water?'bandpass':'lowpass';voice.filter.Q.setValueAtTime(water?.35:.6,now);voice.filter.frequency.setValueAtTime(water?4200-waterDepth*6500:notes?5600:impact.filter,now);voice.tone.frequency.cancelScheduledValues(now);voice.tone.frequency.setValueAtTime(frequency,now);voice.ring.frequency.setValueAtTime(frequency*(impact?.group==='metal'?1.48:1.9),now);
 if(water){voice.toneGain.gain.cancelScheduledValues(now);voice.toneGain.gain.setValueAtTime(0,now);voice.ringGain.gain.cancelScheduledValues(now);voice.ringGain.gain.setValueAtTime(0,now);voice.filter.frequency.exponentialRampToValueAtTime(900,now+duration);this.envelope(voice.noiseGain.gain,volume,now,duration,.025);}else if(notes){notes.forEach((frequency,i)=>voice.tone.frequency.setValueAtTime(frequency*pitch,now+i*duration/notes.length));this.envelope(voice.toneGain.gain,volume,now,duration);this.envelope(voice.ringGain.gain,event.type==='REPAIR_PICKUP'?.06:.025,now,.11);this.envelope(voice.noiseGain.gain,event.type==='BEER_PICKUP'?.07:.02,now,.07);}
 else{voice.tone.frequency.exponentialRampToValueAtTime(Math.max(30,frequency*.56),now+duration);this.envelope(voice.toneGain.gain,volume*.65,now,duration);this.envelope(voice.ringGain.gain,volume*(impact.group==='metal'||impact.group==='npc'?.30:.03),now,duration*.85);this.envelope(voice.noiseGain.gain,volume*(impact.group==='wood'||impact.group==='break'?.75:.46),now,duration*.75);}
 voice.until=now+duration;this.cooldowns[group]=now;this.lastGlobal=now;this.lastCue={type:event.type,variant,pitch,volume,duration,surface:impact?.group==='surface',waterDepth:water?waterDepth:undefined,speed:water?event.speed:undefined};return true;}catch{return false;}}
 update(){if(this.engine.started&&this.engine.ctx?.state==='running')this.init();if(this.master&&this.engine.ctx?.state==='running')try{this.master.gain.setTargetAtTime(this.engine.enabled?EVENT_AUDIO_CONFIG.maxGain:0,this.engine.ctx.currentTime,.04);}catch{}}
 clear(){this.cooldowns={};this.lastGlobal=-10;}
}
