import {boxContact,resolveBox} from './colliders.js?v=021';
import {PROP_CONFIG} from './props.js?v=021';
import {trafficSafe} from './traffic.js?v=021';
export const FARMER_CONFIG={maxActiveFarmers:2,chance:.42,spawnRange:[120,300],crossAt:75,speed:[2.3,3.1],crossChance:.72,width:.65,depth:.70,height:1.75,loss:.38,ragdollLife:2.6};
function random(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
export function populateFarmers(world,section){section.farmerEvents=[];if(section.id<4||section.biomeProfile.type!=='VILLAGE'||section.crestSafe||['JUMP','EARTH_JUMP','BLIND_CREST','DOUBLE_WAVE','ROCK_SECTION','LOG_CROSSING','WASHOUT','BUMP_CHAIN','RUTS','TECHNICAL_HILL','STEEP_DESCENT'].includes(section.type))return;const r=random(world.seed^Math.imul(section.id+1,0x51ed270b));if(r()>=FARMER_CONFIG.chance)return;for(let i=0;i<5;i++){const u=.23+r()*.5;if(world.sections.at(-2)?.crestSafe&&u*section.length<90)continue;const side=r()<.5?-1:1,p=world.point(section,u),width=section.nodes[Math.floor(u*(section.nodes.length-1))].width,lateral=side*(width/2+1.2),x=p.x+Math.cos(p.yaw)*lateral,z=p.z-Math.sin(p.yaw)*lateral;
 if(section.localFeatures.some(o=>Math.abs((o.u-u)*section.length)<o.longRadius+4)||section.obstacles.some(o=>Math.abs((o.u-u)*section.length)<o.radius+4))continue;
 const clear=world.sections.every(s=>[...s.decorations,...(s.visualDecor||[])].every(d=>{if(d.broken||!['house','parked','hay','fence','gate','well','pole','shed','busStop','canopy'].includes(d.kind))return true;const spec=PROP_CONFIG.village[d.kind],width=spec?.width||d.width||.8,depth=spec?.depth||(d.kind==='fence'?d.width:d.depth)||.8,dx=x-d.x,dz=z-d.z,c=Math.cos(d.rotation||0),sn=Math.sin(d.rotation||0),lx=dx*c-dz*sn,lz=dx*sn+dz*c;return Math.abs(lx)>width/2+1.2||Math.abs(lz)>depth/2+1.2;}));if(!clear)continue;
 section.farmerEvents.push({key:'farmer:'+section.id,u,s:section.startDistance+u*section.length,side,lateral,crossing:trafficSafe(section)&&r()<FARMER_CONFIG.crossChance,speed:FARMER_CONFIG.speed[0]+r()*(FARMER_CONFIG.speed[1]-FARMER_CONFIG.speed[0]),phase:r()*6.28,activated:false,completed:false});break;}}
export class Farmers{
 constructor(world,feedback,traffic){this.world=world;this.feedback=feedback;this.traffic=traffic;this.pool=Array.from({length:FARMER_CONFIG.maxActiveFarmers},()=>({active:false}));this.clear();}
 clear(){this.pool.forEach(a=>a.active=false);this.time=0;this.lastCall=-20;}
 get active(){return this.pool.filter(a=>a.active);}
 activate(playerS){for(const s of this.world.sections)for(const e of s.farmerEvents||[]){if(e.activated||e.completed)continue;const distance=e.s-playerS;if(distance<0){e.completed=true;continue;}if(distance<FARMER_CONFIG.spawnRange[0]||distance>FARMER_CONFIG.spawnRange[1])continue;if(this.world.sections.some(q=>q.startDistance<e.s&&q.exitDistance>playerS&&q.crestSafe))continue;const slot=this.pool.find(a=>!a.active);if(!slot)continue;const p=this.world.point(s,e.u),x=p.x+Math.cos(p.yaw)*e.lateral,z=p.z-Math.sin(p.yaw)*e.lateral;if(this.traffic.active.some(n=>Math.hypot(n.x-x,n.z-z)<10))continue;Object.assign(slot,e,{active:true,sectionId:s.id,x,z,y:this.world.height(x,z),rotation:p.yaw+(e.side>0?-Math.PI/2:Math.PI/2),roadYaw:p.yaw,roadWidth:p.width||s.width,age:0,running:false,hit:false,width:FARMER_CONFIG.width,depth:FARMER_CONFIG.depth,height:FARMER_CONFIG.height});e.activated=true;}}
 tick(dt,body){this.time+=dt;const player=this.world.locate(body.p[0],body.p[2]);this.activate(player.s);for(const a of this.pool){if(!a.active)continue;a.age+=dt;const s=this.world.sections.find(s=>s.id===a.sectionId);if(!s||a.s<player.s-55){a.active=false;continue;}if(a.hit){a.hitAge+=dt;if(a.hitAge>=FARMER_CONFIG.ragdollLife){a.active=false;continue;}a.velocity[1]-=9.81*dt;for(let i=0;i<3;i++)a[['x','y','z'][i]]+=a.velocity[i]*dt;a.tumble+=dt*5;const floor=this.world.height(a.x,a.z)+.22;if(a.y<floor){a.y=floor;a.velocity[1]=Math.abs(a.velocity[1])*.18;a.velocity[0]*=Math.exp(-dt*3);a.velocity[2]*=Math.exp(-dt*3);}continue;}
 if(a.crossing&&a.s-player.s<FARMER_CONFIG.crossAt)a.running=true;if(a.running){a.lateral-=a.side*a.speed*dt;const p=this.world.point(s,a.u);a.x=p.x+Math.cos(p.yaw)*a.lateral;a.z=p.z-Math.sin(p.yaw)*a.lateral;a.y=this.world.height(a.x,a.z);if(a.lateral*a.side<-a.roadWidth/2-3){a.active=false;continue;}}
 if(!boxContact(body,a))continue;const velocity=a.running?[Math.cos(a.roadYaw)*-a.side*a.speed,-Math.sin(a.roadYaw)*-a.side*a.speed]:[0,0],hit=resolveBox(body,a,velocity,FARMER_CONFIG.loss);if(!hit||hit.closing<.8)continue;this.feedback.emit('farmerHit',{sourceId:a.key,impulse:hit.impulse,position:[a.x,a.y,a.z]});this.feedback.burst([a.x,a.y+.8,a.z],body.v,22,'dust');this.feedback.burst([a.x,a.y+1.5,a.z],body.v,8,'cloth');a.hit=true;a.running=false;a.hitAge=0;a.tumble=0;a.velocity=[body.v[0]*.35,4+Math.min(3,hit.closing*.1),body.v[2]*.35];}}
 shift(dx,dz){for(const a of this.pool)if(a.active){a.x-=dx;a.z-=dz;}}
}
