export const FEEDBACK_CONFIG={maxParticles:360,maxEvents:64,maxRate:31,maxPerFrame:18,landingSpeed:2.8,landingAirTime:.08,maxLandingInterval:.4};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export function wheelEmission(w,state){if(w.detached||!w.contact||w.load<50)return null;const speed=Math.abs(state.vehicleSpeed||0)/3.6,spin=Math.abs(w.omega||0)*.44,slip=Math.min(2,Math.abs(w.wheelSlip??w.slipRatio??0)),side=Math.min(1,Math.abs(w.slipAngle||0)*2),energy=Math.max(speed,Math.min(12,spin)*slip),surface=w.surfaceType;
 if(energy<.8)return null;const mult=w.surface?.effectMultiplier||1,wet=w.surface?.wetness||0;if(wet>.12&&surface!=='MUD'&&surface!=='WATER')return{type:'waterSplash',rate:clamp(speed*.22*wet,0,8),energy,slip};
 if(surface==='DIRT'||surface==='SOFT_DIRT')return{type:'dust',rate:clamp((speed*.50+slip*8+side*12)*mult*1.4,0,31),energy,slip};
 if(surface==='MUD')return{type:'mudSplash',rate:clamp((2+speed*.5+slip*9*(.4+state.throttle)) *mult,0,22),energy,slip};
 if(surface==='WATER')return{type:'waterSplash',rate:clamp((speed*.95+slip*6)*(1+Math.min(.3,w.waterDepth||0)*3.5),0,30),energy,slip};return null;
}
export class VehicleFeedback{
 constructor(seed=1,capacity=FEEDBACK_CONFIG.maxParticles){this.seed=seed>>>0;this.intensity=1;this.particles=Array.from({length:capacity},()=>({active:false,p:[0,0,0],v:[0,0,0],color:[0,0,0],age:0,life:0,size:0,type:''}));this.events=[];this.listeners=new Set();this.emitters=[];this.wheelData=[];this.credit=[0,0,0,0];this.time=0;this.airTime=0;this.lastVY=0;this.landingImpact=0;this.lastLanding=-10;this.lastEventTime={};this.emissionCounts={dust:0,mudSplash:0,waterSplash:0};this.cursor=0;this.smokeCredit=0;}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 emit(type,data={}){const event={type,time:this.time,...data};this.events.push(event);if(this.events.length>FEEDBACK_CONFIG.maxEvents)this.events.shift();for(const fn of this.listeners)fn(event);return event;}
 onEvent(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);}
 physicsTick(dt,body){this.time+=dt;const supported=body.wheels.some(w=>w.contact&&w.load>100);if(!supported)this.airTime+=dt;else{if(this.airTime>=FEEDBACK_CONFIG.landingAirTime&&this.lastVY<-FEEDBACK_CONFIG.landingSpeed&&this.time-this.lastLanding>FEEDBACK_CONFIG.maxLandingInterval){this.landingImpact=-this.lastVY;this.lastLanding=this.time;this.emit('hardLanding',{impact:this.landingImpact,contactForce:body.wheels.reduce((n,w)=>n+w.load,0),position:body.p.slice()});}this.airTime=0;}this.lastVY=body.v[1];}
 spawn(w,emission,body){let particle;for(let i=0;i<this.particles.length;i++){const index=(this.cursor+i)%this.particles.length;if(!this.particles[index].active){particle=this.particles[index];this.cursor=(index+1)%this.particles.length;break;}}if(!particle)return false;
 const {type,energy,slip}=emission,point=w.point||w.position,r=this.random(),side=(this.random()-.5)*2,forward=body.point([0,body.c?.centerOfMass?.[1]||0,1]).map((x,i)=>x-body.p[i]),velocity=body.v,wet=type!=='dust';particle.active=true;particle.type=type;particle.age=0;particle.life=wet?.45+r*.45:1.2+r*.78;particle.size=type==='dust'?.42+r*.60:type==='waterSplash'?.09+r*.13:.08+r*.085;
 if(this.intensity>1){const spray=clamp(slip/1.1,0,1);particle.size*=type==='dust'?1.12:type==='mudSplash'?1.3+.38*spray:1.15+.25*spray;}particle.p=[point[0],point[1]+.08,point[2]];const backward=wet?Math.min(type==='waterSplash'?18:13,energy*(type==='waterSplash'?.7:.5)+slip*2):1.0;
 particle.v=[velocity[0]*.22-forward[0]*backward+forward[2]*side*(wet?2.5:.8),wet?(1.4+r*2+Math.min(2,energy*.055))*(this.intensity>1?1+Math.min(.55,slip*.3):1):.6+r*.6,velocity[2]*.22-forward[2]*backward-forward[0]*side*(wet?2.5:.8)];particle.color=type==='dust'?[.64,.55,.40]:type==='waterSplash'?[.65,.82,.82]:[.28,.21,.13];this.emissionCounts[type]++;return true;
 }
 update(dt,body){dt=Math.min(dt,.05);for(const p of this.particles){if(!p.active)continue;p.age+=dt;if(p.age>=p.life){p.active=false;continue;}p.v[1]-=(p.type==='dust'||p.type==='smoke'?-.35:p.type==='feather'?1.5:9.81)*dt;const damping=Math.exp(-(p.type==='dust'||p.type==='smoke'?1.3:.35)*dt);for(let i=0;i<3;i++){p.v[i]*=damping;p.p[i]+=p.v[i]*dt;}if(p.type==='dust'||p.type==='smoke')p.size+=dt*.32;}
 this.emitters=[];let spawned=0;this.wheelData=body.wheels.map(w=>({id:w.id,position:(w.point||w.position).slice(),surfaceType:w.surfaceType,wheelSlip:w.wheelSlip??w.slipRatio,wheelRPM:w.rpm,contactForce:w.load}));
 this.smoke(dt,body);
 for(let i=0;i<4;i++){if(body.state.runEnded)break;const w=body.wheels[i],emission=wheelEmission(w,body.state);if(!emission){this.credit[i]=0;continue;}
 if(this.intensity>1){const spin=clamp(Math.abs(w.slipRatio||0)/1.3,0,1.5);emission.rate=clamp(emission.rate*this.intensity*(1+.85*spin),0,100);}
 this.emitters.push({wheel:w.id,surfaceType:w.surfaceType,...emission});this.credit[i]=Math.min(this.intensity>1?4:2,this.credit[i]+emission.rate*dt);
 while(this.credit[i]>=1&&spawned<(this.intensity>1?30:FEEDBACK_CONFIG.maxPerFrame)){this.credit[i]--;if(this.spawn(w,emission,body)){spawned++;const key=w.id+emission.type;if(this.time-(this.lastEventTime[key]??-10)>.2){this.emit(emission.type,{wheel:w.id,position:(w.point||w.position).slice(),intensity:emission.rate,speed:Math.abs(body.state.vehicleSpeed||0)/3.6,waterDepth:w.waterDepth||0,wetness:w.surface?.wetness||0});this.lastEventTime[key]=this.time;}}}}
 }
 smoke(dt,body){const hp=body.state.hp??100;if(hp>50){this.smokeCredit=0;return;}this.smokeCredit=Math.min(2,this.smokeCredit+dt*(hp<=25?9:3));while(this.smokeCredit>=1){this.smokeCredit--;const p=this.particles.find(p=>!p.active);if(!p)break;const r=this.random(),position=body.point([0,1.25,1.15]);Object.assign(p,{active:true,type:'smoke',age:0,life:1.5+r*.7,size:.27+r*.25,p:position,v:[body.v[0]*.16+(r-.5)*.3,.8+r*.4,body.v[2]*.16],color:hp<=25?[.25,.26,.25]:[.50,.51,.48]});}}
 burst(position,velocity,count,type='antifreeze'){for(let i=0;i<Math.min(count,90);i++){const p=this.particles.find(p=>!p.active)||this.particles[this.cursor++%this.particles.length],a=this.random()*Math.PI*2,r=this.random();Object.assign(p,{active:true,type,age:0,life:type==='feather'?1.2+r: .65+r*.6,size:type==='feather'?.07+r*.08:.10+r*.12,p:position.slice(),v:[velocity[0]*.12+Math.cos(a)*(2+r*4),2+r*5,velocity[2]*.12+Math.sin(a)*(2+r*4)],color:type==='feather'?[.91,.87,.75]:type==='dust'?[.64,.55,.40]:type==='cloth'?[.34,.42,.52]:type==='straw'?[.77,.65,.32]:[.80,.055,.025]});}}
 shift(dx,dz){for(const p of this.particles)if(p.active){p.p[0]-=dx;p.p[2]-=dz;}for(const w of this.wheelData){w.position[0]-=dx;w.position[2]-=dz;}for(const e of this.events)if(e.position){e.position[0]-=dx;e.position[2]-=dz;}}
 clear(){this.smokeCredit=0;this.particles.forEach(p=>p.active=false);this.events.length=0;this.credit.fill(0);this.emitters=[];this.airTime=0;this.lastVY=0;this.landingImpact=0;this.lastEventTime={};}
 get activeParticles(){return this.particles.reduce((n,p)=>n+Number(p.active),0);}
}
