import {buildCircuit,CIRCUIT_CONFIG} from './circuit-world.js?v=026';
const mod=(a,b)=>(a%b+b)%b;
export function eightSkeleton(seed){const target=800+(seed%151),angle=(seed%100)/100*.5-.25,raw=[];let length=0;for(let i=0;i<=2048;i++){const t=i/2048*Math.PI*2,x=Math.sin(t),z=Math.sin(2*t)*.68;if(i)length+=Math.hypot(x-raw[i-1].x,z-raw[i-1].z);raw.push({x,z,s:length});}const factor=target/length;for(const p of raw){const x=p.x*factor,z=p.z*factor;p.x=x*Math.cos(angle)+z*Math.sin(angle);p.z=z*Math.cos(angle)-x*Math.sin(angle);p.s*=factor;}
 const sample=s=>{s=mod(s-CIRCUIT_CONFIG.startLine,target);let lo=0,hi=raw.length-1;while(hi-lo>1){const m=(lo+hi)>>1;if(raw[m].s<=s)lo=m;else hi=m;}const a=raw[lo],b=raw[hi],u=(s-a.s)/(b.s-a.s);return{x:a.x+(b.x-a.x)*u,z:a.z+(b.z-a.z)*u};};const jumpS=mod(raw[256].s+CIRCUIT_CONFIG.startLine,target);
 return{length:target,jumpS,point(s){const p=sample(s),a=sample(s-.4),b=sample(s+.4),delta=Math.abs(mod(s-jumpS+target/2,target)-target/2),u=Math.max(0,1-delta/18);return{...p,y:2.8*Math.sin(u*Math.PI/2)**2,yaw:Math.atan2(b.x-a.x,b.z-a.z)};}};
}
export function buildFigureEight(world,seed){const skeleton=eightSkeleton(seed);buildCircuit(world,seed,{skeleton});world.survival=true;world.figureEight=true;world.raceLength=null;world.jumpS=skeleton.jumpS;
 for(const section of world.sections){section.biomeProfile.type=section.startDistance<skeleton.length*.53?'FIELD':'FOREST';section.biomeProfile.previous=section.biomeProfile.type;section.asphalt=false;section.surface='DIRT';section.hill=null;section.localFeatures=[];section.obstacles=[];section.type=section.id===0?'START_FINISH':Math.abs((section.startDistance+section.length/2)-skeleton.jumpS)<section.length/2?'EARTH_JUMP':'FAST_CURVE';section.crestSafe=section.type==='EARTH_JUMP';
 for(const node of section.nodes)node.y=skeleton.point(node.s).y;section.entryTransform={...section.nodes[0]};section.exitTransform={...section.nodes.at(-1)};
 section.decorations=section.decorations.filter(d=>!['house','shed','fence','gate','parked','busStop','well','sign'].includes(d.kind)&&Math.hypot(d.x,d.z)>25);section.visualDecor=section.visualDecor.filter(d=>Math.hypot(d.x,d.z)>22);section.pickups=section.pickups.filter(d=>d.type!=='REPAIR'&&Math.hypot(d.x,d.z)>28);section.animalEvents=[];section.farmerEvents=[];section.decorationRevision++;}
 world.revision++;world.binsDirty=true;world.indexSegments();for(const section of world.sections)for(const d of [...section.decorations,...section.visualDecor])d.y=world.height(d.x,d.z);
 // Route hint resolves the two coincident roads for guidance only. Terrain and collisions remain shared.
 world.locateRoute=function(x,z,hint=50){const ordinary=this.locate(x,z);let best=ordinary,distance=Infinity;const candidates=this.bins.get(Math.floor(x/8)+','+Math.floor(z/8))||this.allRaceSegments;for(const {section,i,a,b} of candidates){const dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz))),s=a.s+(b.s-a.s)*t,gap=Math.abs(mod(s-hint+this.circuitLength/2,this.circuitLength)-this.circuitLength/2),cx=a.x+dx*t,cz=a.z+dz*t,score=(x-cx)**2+(z-cz)**2+(gap>70?2500:0);if(score<distance){distance=score;const yaw=a.yaw+(b.yaw-a.yaw)*t;best={section,index:i,t,x:cx,z:cz,y:a.y+(b.y-a.y)*t,yaw,width:a.width,u:a.u+(b.u-a.u)*t,s,lateral:(x-cx)*Math.cos(yaw)-(z-cz)*Math.sin(yaw)};}}return best;};return world;
}
