import {RaceDecor,RACE_DECOR_CONFIG} from './race-decor.js?v=022';
import {buildCircuit,CIRCUIT_CONFIG} from './circuit-world.js?v=022';
import {GAME_MODE,VillageCup} from './race.js?v=022';
import {Environment,RainField,ENVIRONMENT_CONFIG} from './environment.js?v=022';
import {Farmers} from './farmers.js?v=022';
import {Animals} from './animals.js?v=022';
import {MusicPlayer} from './music.js?v=022';
import {SafeCheckpoints,CHECKPOINT_CONFIG} from './checkpoints.js?v=022';
import {randomSeed,initialSeed} from './random-seed.js?v=022';
import {fuelRate,RunState} from './run-state.js?v=022';
import {Pickups,PICKUP_CONFIG} from './pickups.js?v=022';
import {EventAudio} from './event-audio.js?v=022';
import {Traffic} from './traffic.js?v=022';
import {npcGeometry,NPC_COLORS} from './npc-models.js?v=022';
import {fieldTone} from './biomes.js?v=022';
import {PropCollisions} from './props.js?v=022';
import {VehicleFeedback} from './feedback.js?v=022';
import {TreeCollisions,TREE_CONFIG} from './trees.js?v=022';
import {bindThrottle} from './controls.js?v=022';
import {HoodCamera,CAMERA_CONFIG} from './cameras.js?v=022';
import {RoadWorld,ROAD_CONFIG,asphaltBlend} from './road-world.js?v=022';
import {VisualCar} from './visual-car.js?v=022';
import {OffroadVehicle,CAR_CONFIG,rotate} from './physics.js?v=022';
import {EngineAudio} from './engine-audio.js?v=022';
const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='WebGL недоступен. Открой сайт в Safari или Chrome.';throw Error('WebGL unavailable');}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
const fragmentPrecision=gl.getShaderPrecisionFormat?.(gl.FRAGMENT_SHADER,gl.HIGH_FLOAT)?.precision>0?'highp':'mediump';
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,`attribute vec3 p;attribute vec3 n;attribute vec4 t;varying vec3 ground;varying vec4 roadUV;uniform mat4 mvp;uniform mat4 model;uniform vec3 eye;varying float light;varying float fog;varying vec3 worldPosition;void main(){worldPosition=(model*vec4(p,1.)).xyz;ground=p;roadUV=t;light=.76+.24*max(dot(normalize(mat3(model)*n),normalize(vec3(-.5,1.,.3))),0.);gl_Position=mvp*vec4(p,1.);fog=distance((model*vec4(p,1.)).xyz,eye);}`));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,`precision ${fragmentPrecision} float;uniform vec3 color;uniform float style;varying vec3 ground;varying vec4 roadUV;varying float light;varying float fog;varying vec3 worldPosition;uniform vec3 skyFog;uniform vec3 daylightColor;uniform vec3 headOrigin;uniform vec3 headDirection;uniform float ambientLevel;uniform float wetness;uniform float headlights;uniform float emissive;uniform float headRange;uniform vec2 fogLimits;
float hash(vec2 p){return fract(sin(dot(mod(p,64.),vec2(12.9898,78.233)))*437.58);}
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}
void main(){vec3 c=color;if(style>0.){c=mix(c,c*vec3(1.09,1.04,.94),roadUV.w);vec2 uv=roadUV.xy;float broad=noise(uv*.15),grain=noise(uv*2.);c*=.91+.15*broad+.035*grain;if(style<1.5){c=mix(c,vec3(.48,.43,.31),smoothstep(.62,.88,broad)*.26);c+=vec3(.025,.018,.009)*(grain-.5);float rut=exp(-pow((abs(roadUV.y)-.84)/.21,2.));c*=1.-.075*rut;float edge=smoothstep(.80,1.,abs(roadUV.z)+.05*(broad-.5));c=mix(c,mix(vec3(.43,.50,.34),vec3(.63,.61,.38),roadUV.w),edge*.75);}if(style>2.5&&style<3.5)c*=.92+.08*sin(roadUV.x*13.);if(style>3.5&&style<4.5)c=mix(c,vec3(.55,.66,.63),pow(max(0.,noise(uv*.8)-.3),3.)*.5);if(style>4.5&&style<5.5){float patch=noise(uv*vec2(.027,.046))*.65+noise(uv*vec2(.071,.11))*.35;vec3 forest=mix(vec3(.31,.39,.26),vec3(.47,.45,.31),smoothstep(.42,.78,patch));vec3 field=mix(vec3(.48,.51,.32),vec3(.68,.63,.42),smoothstep(.27,.73,patch));field=mix(field,vec3(.56,.48,.34),smoothstep(.66,.88,noise(uv*.065))*.55);c=mix(forest,field,roadUV.w)*(.96+.055*grain);float verge=1.-smoothstep(1.04,1.70,abs(roadUV.z)+.09*(noise(uv*.16)-.5));c=mix(c,vec3(.49,.44,.32),verge*.64);float oldRut=exp(-pow((abs(roadUV.y)-5.4)/.23,2.));c*=1.-oldRut*verge*.09;}if(style>5.5&&style<6.5){c=mix(vec3(.64,.59,.44),color*(.94+.08*broad+.025*grain),roadUV.w);float cracks=1.-smoothstep(.0,.025,abs(noise(uv*.5)-.50));c*=1.-cracks*.12;float edge=smoothstep(.93,1.,abs(roadUV.z)+.025*(broad-.5));c=mix(c,vec3(.55,.50,.36),edge*.65);}if(style>6.5)c=color*(.74+.20*broad); }float ahead=dot(worldPosition-headOrigin,headDirection);vec3 off=worldPosition-headOrigin-headDirection*ahead;float spread=1.0+max(0.,ahead)*.40;float beam=headlights*smoothstep(0.,1.5,ahead)*(1.-smoothstep(headRange*.724,headRange,ahead))*(1.-smoothstep(spread*.72,spread,length(off.xz)))*(1.-smoothstep(3.,11.,abs(off.y)));if(style>0.&&style<7.5)c*=1.-wetness*.32;vec3 lit=c*light*daylightColor*ambientLevel+vec3(1.,.91,.69)*c*beam*(.9-.55*ambientLevel);lit=max(lit,c*emissive);gl_FragColor=vec4(mix(lit,skyFog,smoothstep(fogLimits.x,fogLimits.y,fog)),1.);}`));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const loc={};for(const k of ['mvp','model','color','eye','style','skyFog','daylightColor','headOrigin','headDirection','ambientLevel','wetness','headlights','emissive','headRange','fogLimits'])loc[k]=gl.getUniformLocation(program,k);for(const k of ['p','n','t'])loc[k]=gl.getAttribLocation(program,k);
function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function matrix(x,y,z,sx,sy,sz,a=0){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1]);}
function norm(v){const d=Math.hypot(...v)||1;return v.map(x=>x/d);}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}function dot(a,b){return a.reduce((s,v,i)=>s+v*b[i],0);}function view(e,t,up=[0,1,0]){const z=norm(e.map((v,i)=>v-t[i])),x=norm(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,e),-dot(y,e),-dot(z,e),1]);}
function mesh(v,n,t=new Array(v.length/3*4).fill(0)){function buf(data){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return b;}return{p:buf(v),n:buf(n),t:buf(t),count:v.length/3,rawV:v,rawN:n};}
const v=[],n=[];for(let axis=0;axis<3;axis++)for(const sign of [-1,1]){const corners=[];for(const [u,w] of [[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]]){const p=[0,0,0];p[axis]=sign*.5;p[(axis+1)%3]=u;p[(axis+2)%3]=w;corners.push(p);}const normal=[0,0,0];normal[axis]=sign;for(const i of [0,1,2,0,2,3]){v.push(...corners[i]);n.push(...normal);}}const cube=mesh(v,n);
const rv=[],rn=[];for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const points=[[Math.cos(a)*.5,-.5,Math.sin(a)*.5],[Math.cos(b)*.5,-.5,Math.sin(b)*.5],[Math.cos(b)*.5,.5,Math.sin(b)*.5],[Math.cos(a)*.5,.5,Math.sin(a)*.5]];for(const j of [0,1,2,0,2,3]){rv.push(...points[j]);rn.push(Math.cos((a+b)/2),0,Math.sin((a+b)/2));}for(const y of [-.5,.5])for(const p of [[0,y,0],[Math.cos(a)*.5,y,Math.sin(a)*.5],[Math.cos(b)*.5,y,Math.sin(b)*.5]]){rv.push(...p);rn.push(0,Math.sign(y),0);}}const cylinder=mesh(rv,rn);
let lampEmission=0;let pv;function draw(shape,m,col,style=0,emissive=0){gl.uniform1f(loc.emissive,Math.max(emissive,lampEmission));gl.uniform1f(loc.style,style);for(const k of ['p','n','t']){gl.bindBuffer(gl.ARRAY_BUFFER,shape[k]);gl.vertexAttribPointer(loc[k],k==='t'?4:3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc[k]);}gl.uniformMatrix4fv(loc.model,false,m);gl.uniformMatrix4fv(loc.mvp,false,mul(pv,m));gl.uniform3fv(loc.color,col);gl.drawArrays(gl.TRIANGLES,0,shape.count);}
// A bounded rolling corridor replaces the finite polygon.
const parameters=new URLSearchParams(globalThis.location?.search||''),debug=parameters.has('debug'),seed=initialSeed(parameters),environment=new Environment(seed),rain=new RainField(seed),world=new RoadWorld(seed,environment);
const height=(x,z)=>world.height(x,z),groundNormal=(x,z)=>world.normal(x,z),sampleSurface=(x,z)=>world.surface(x,z),grip=(x,z)=>sampleSurface(x,z).longitudinalGrip;
let feedback,collisions,props,traffic,run,pickups,eventAudio,animals,farmers,cup,raceDecor;
let gameMode=GAME_MODE.ENDLESS,menuOpen=true;
const physics=new OffroadVehicle({height,normal:groundNormal,grip,surface:sampleSurface,afterStep:(dt,body)=>{environment.update(dt);collisions?.tick(dt,body);props?.tick(dt,body);if(gameMode===GAME_MODE.ENDLESS)traffic?.tick(dt,body);animals?.tick(dt,body);farmers?.tick(dt,body);if(gameMode===GAME_MODE.CIRCUIT)raceDecor?.tick(dt,body);feedback?.physicsTick(dt,body);run?.tick(dt,body);pickups?.tick(dt,body);}},{...CAR_CONFIG,mapLimit:Infinity}),sound=new EngineAudio(document.querySelector('#sound'));const spawn=world.point(world.sections[0],18/world.sections[0].length);physics.reset(spawn.x,spawn.z,spawn.yaw);const visual=new VisualCar(physics);feedback=new VehicleFeedback(world.seed);collisions=new TreeCollisions(world,feedback);props=new PropCollisions(world,feedback);traffic=new Traffic(world,feedback);animals=new Animals(world,feedback,traffic);farmers=new Farmers(world,feedback,traffic);let localStore;try{localStore=globalThis.localStorage;}catch{}run=new RunState(feedback,localStore);run.body=physics;run.mechanical.bind(physics,world.seed);run.applyEngine(physics);pickups=new Pickups(world,run,traffic);eventAudio=new EventAudio(sound,feedback);const checkpoints=new SafeCheckpoints(world);checkpoints.reset();let cameraKick=0;feedback.onEvent(e=>{if(e.type==='COW_HIT')cameraKick=Math.min(.8,(e.impulse||0)/35000);});cup=new VillageCup(world,physics,run,feedback,localStore);raceDecor=new RaceDecor(world,feedback);const music=new MusicPlayer(sound,[]);music.suspended=true;feedback.onEvent(e=>music.event(e));document.addEventListener('pointerdown',()=>music.unlock());document.addEventListener('keydown',()=>music.unlock());
const chunkSlots=new Map(),freeSlots=[];
function uploadGeometry(vertices,normals,old,uv=new Array(vertices.length/3*4).fill(0)){if(!old)return mesh(vertices,normals,uv);for(const [key,data] of [['p',vertices],['n',normals],['t',uv]]){gl.bindBuffer(gl.ARRAY_BUFFER,old[key]);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);}old.count=vertices.length/3;return old;}
export const VIEW_CONFIG={nearTrees:130,midTrees:260,drawDistance:550,fogStart:300,fogEnd:540};
function sectionDistance(section,pos){if(!world.circular)return Math.max(0,section.startDistance-pos,pos-section.startDistance-section.length);const p=world.atDistance(pos),mid=section.nodes[Math.floor(section.nodes.length/2)];return Math.max(0,Math.hypot(mid.x-p.x,mid.z-p.z)-section.length/2);}
function chunkLOD(section,pos){const dist=sectionDistance(section,pos);return dist<VIEW_CONFIG.nearTrees?0:dist<VIEW_CONFIG.midTrees?1:2;}

function buildChunk(section,slot={},lod=0,decorOnly=false){const batches={};function triangle(key,a,b,c){const batch=batches[key]??={v:[],n:[],uv:[]},raw=norm(cross(b.map((x,i)=>x-a[i]),c.map((x,i)=>x-a[i]))),normal=raw[1]<0?raw.map(v=>-v):raw;batch.uv??=new Array(batch.v.length/3*4).fill(0);for(const point of [a,b,c]){batch.v.push(...point);batch.n.push(...normal);batch.uv.push(...(point.uv||[0,0,0,0]));}}
 function at(node,lateral,water=false){const edge=Math.max(0,Math.abs(lateral)-node.width/2),y=node.y+.025*edge+.12*Math.sin(lateral*.2)**2*Math.min(1,edge/5)+world.localHeight(section,node.u,lateral)+(water?world.surfaceAt({section,u:node.u,lateral,width:node.width}).waterDepth:0);const point=[node.x+Math.cos(node.yaw)*lateral-section.entryTransform.x,y+(water?.02:0),node.z-Math.sin(node.yaw)*lateral-section.entryTransform.z];point.uv=[node.s%4096,lateral,lateral/(node.width/2),Math.abs(lateral)<=node.width/2&&section.asphalt?asphaltBlend(section,node.u):fieldTone(section.biomeProfile,node.s)];return point;}
 if(!decorOnly)for(let i=0;i<section.nodes.length-1;i++){const a=section.nodes[i],b=section.nodes[i+1],fractions=[-1,-.8,-.5,-.3,-.2,0,.2,.3,.5,.8,1],half=(a.width+b.width)/4;
 for(const o of section.localFeatures)if(Math.abs((a.u+b.u)/2-o.u)*section.length<o.longRadius*3+1.5)for(const f of [-2,-1,-.5,0,.5,1,2])fractions.push(Math.max(-.99,Math.min(.99,(o.lateral+f*o.radius)/half)));
 const fs=[...new Set(fractions)].sort((x,y)=>x-y),offsets=node=>[...(world.circular?[]:[-650]),-96,-48,-20,-12,-7,...fs.map(f=>f*node.width/2),7,12,20,48,96,...(world.circular?[]:[650])],aa=offsets(a),bb=offsets(b);
 for(let j=0;j<aa.length-1;j++){const lateral=(aa[j]+aa[j+1])/2,inside=Math.abs(lateral)<=a.width/2+.001,key=inside?world.visualMaterial(section,(a.u+b.u)/2,lateral):'GRASS',p=at(a,aa[j]),q=at(a,aa[j+1]),r=at(b,bb[j]),t=at(b,bb[j+1]);triangle(key,p,q,r);triangle(key,q,t,r);if(inside&&world.surfaceAt({section,u:(a.u+b.u)/2,lateral,width:a.width}).waterDepth>.016){triangle('WATER_TOP',at(a,aa[j],true),at(a,aa[j+1],true),at(b,bb[j],true));triangle('WATER_TOP',at(a,aa[j+1],true),at(b,bb[j+1],true),at(b,bb[j],true));}}
 if(section.asphalt&&a.u*section.length>6&&(1-b.u)*section.length>6&&a.s%12<6){const p=at(a,-.07),q=at(a,.07),r=at(b,-.07),t=at(b,.07);for(const pt of [p,q,r,t])pt[1]+=.022;triangle('MARKING',p,q,r);triangle('MARKING',q,t,r);}
 }
 function boxPiece(key,x,y,z,sx,sy,sz,angle=0){const m=matrix(x-section.entryTransform.x,y,z-section.entryTransform.z,sx,sy,sz,angle),batch=batches[key]??={v:[],n:[]};for(let i=0;i<v.length;i+=3){batch.v.push(m[0]*v[i]+m[4]*v[i+1]+m[8]*v[i+2]+m[12],m[1]*v[i]+m[5]*v[i+1]+m[9]*v[i+2]+m[13],m[2]*v[i]+m[6]*v[i+1]+m[10]*v[i+2]+m[14]);batch.n.push(Math.cos(angle)*n[i]+Math.sin(angle)*n[i+2],n[i+1],-Math.sin(angle)*n[i]+Math.cos(angle)*n[i+2]);if(batch.uv)batch.uv.push(0,0,0,0);}}
 function roof(d){const c=Math.cos(d.rotation),s=Math.sin(d.rotation),pt=(x,y,z)=>[d.x+c*x+s*z-section.entryTransform.x,d.y+y,d.z-s*x+c*z-section.entryTransform.z],w=d.width/2+.3,z=d.depth/2+.3,y=d.height,peak=y+1.45;const a=pt(-w,y,-z),b=pt(-w,y,z),c1=pt(0,peak,-z),e=pt(0,peak,z),f=pt(w,y,-z),g=pt(w,y,z);triangle('ROOF'+(d.variant%2),a,b,c1);triangle('ROOF'+(d.variant%2),b,e,c1);triangle('ROOF'+(d.variant%2),c1,e,f);triangle('ROOF'+(d.variant%2),e,g,f);triangle('HOUSE'+(d.variant%2),a,c1,f);triangle('HOUSE'+(d.variant%2),b,g,e);}
 function hay(d){if(d.variant==='square'){boxPiece('HAY',d.x,d.y+d.height/2,d.z,d.width,d.height,d.depth,d.rotation);return;}const c=Math.cos(d.rotation),s=Math.sin(d.rotation),pt=(p)=>[d.x+c*p[0]*d.width+s*p[1]*d.depth-section.entryTransform.x,d.y+d.height/2+p[2]*d.height,d.z-s*p[0]*d.width+c*p[1]*d.depth-section.entryTransform.z];for(let i=0;i<rv.length;i+=9)triangle('HAY',pt(rv.slice(i,i+3)),pt(rv.slice(i+3,i+6)),pt(rv.slice(i+6,i+9)));}
 for(const d of section.decorations){if(d.broken)continue;if(d.kind==='hay'){hay(d);}else if(d.kind==='parked'){continue;}else if(d.kind==='house'){boxPiece('HOUSE'+(d.variant%2),d.x,d.y+d.height/2,d.z,d.width,d.height,d.depth,d.rotation);roof(d);if(lod<2){const c=Math.cos(d.rotation),s=Math.sin(d.rotation);for(const x of [-d.width*.26,d.width*.26])boxPiece('WINDOW',d.x+c*(-d.side)*(d.width/2+.025)+s*x,d.y+1.45,d.z-s*(-d.side)*(d.width/2+.025)+c*x,.06,.80,.68,d.rotation);}}else if(d.kind==='fence'){boxPiece('FENCE',d.x,d.y+.40,d.z,.10,.13,d.width,d.rotation);boxPiece('FENCE',d.x,d.y+.85,d.z,.10,.13,d.width,d.rotation);for(let i=0;i<5;i++){const off=-d.width/2+i*d.width/4;boxPiece('FENCE',d.x+Math.sin(d.rotation)*off,d.y+.56,d.z+Math.cos(d.rotation)*off,.12,1.12,.16,d.rotation);}}else if(d.kind==='sign'){boxPiece('SIGN_POST',d.x,d.y+1.05,d.z,.10,2.1,.10,d.rotation);}else if(d.kind==='tree'){const h=d.scale,key=d.variant===1?'LEAVES_LIGHT':'LEAVES';if(lod===2){const x=d.x-section.entryTransform.x,z=d.z-section.entryTransform.z,base=d.y,top=base+h*1.5;triangle('FOREST_FAR',[x-h*.35,base+h*.35,z],[x,top,z],[x+h*.35,base+h*.35,z]);triangle('FOREST_FAR',[x,base+h*.35,z-h*.35],[x,top,z],[x,base+h*.35,z+h*.35]);}else{boxPiece('TRUNK',d.x,d.y+h/2,d.z,(d.radius||.125)*2,h,(d.radius||.125)*2,d.rotation);boxPiece(key,d.x,d.y+h*.8,d.z,h*.6,h*.5,h*.6,d.rotation);if(lod===0){boxPiece(key,d.x,d.y+h*1.08,d.z,h*.38,h*.4,h*.38,d.rotation+.4);if(d.variant===2)boxPiece(key,d.x,d.y+h*1.3,d.z,h*.21,h*.3,h*.21,d.rotation);}}}else if(lod===0)boxPiece(d.kind==='stone'?'STONE':'LEAVES_LIGHT',d.x,d.y+d.scale*.4,d.z,d.scale,d.scale*.8,d.scale,d.rotation);}


 // All static scenery shares material batches and the existing reusable chunk buffers.
 function crown(key,d,h,w){const x=d.x-section.entryTransform.x,z=d.z-section.entryTransform.z,y=d.y;for(const angle of [d.rotation,d.rotation+Math.PI/2]){const c=Math.cos(angle),sn=Math.sin(angle),pt=(u,v)=>[x+c*u,y+v,z-sn*u];triangle(key,pt(-w,.35*h),pt(0,h),pt(w,.35*h));triangle(key,pt(-w*.8,.2*h),pt(0,h*.78),pt(w*.8,.2*h));}}
 for(const d of section.visualDecor||[]){if(d.broken)continue;
  if(d.kind==='raceStake'){boxPiece('RACE_STAKE',d.x,d.y+.55,d.z,.065,1.1,.065);}else if(d.kind==='raceStripe'){boxPiece(d.red?'RACE_RED':'RACE_WHITE',d.x,d.y+.95,d.z,.045,.13,d.length,d.rotation);}else if(d.kind==='grass'){if(lod>0)continue;const key=['GRASS_LOW','GRASS_FIELD','GRASS_DRY'][d.variant],h=[.20,.48,.85][d.variant]*d.scale,x=d.x-section.entryTransform.x,z=d.z-section.entryTransform.z;for(let j=0;j<3;j++){const a=d.rotation+j*2.1,c=Math.cos(a),sn=Math.sin(a),shift=(j-1)*.13;triangle(key,[x-c*.16+sn*shift,d.y,z+sn*.16+c*shift],[x+sn*.10,d.y+h,z+c*.10],[x+c*.16+sn*shift,d.y,z-sn*.16+c*shift]);}}
  else if(d.kind==='treeFar')crown('FOREST_FAR',d,d.scale*1.6,d.scale*.43);
  else if(d.kind==='treeMiddle'){if(lod===2)crown('FOREST_FAR',d,d.scale*1.5,d.scale*.43);else{boxPiece('TRUNK',d.x,d.y+d.scale*.5,d.z,.25,d.scale,.25,d.rotation);if(d.variant===0)crown('FOREST_MID',d,d.scale*1.6,d.scale*.43);else{boxPiece('FOREST_MID',d.x,d.y+d.scale,d.z,d.scale*.68,d.scale*.6,d.scale*.65,d.rotation);boxPiece('LEAVES_LIGHT',d.x,d.y+d.scale*1.35,d.z,d.scale*.40,d.scale*.4,d.scale*.4,d.rotation+.5);}}}
  else if(d.kind==='horizon'){const x=d.x-section.entryTransform.x,z=d.z-section.entryTransform.z,w=d.scale*1.7,h=d.scale*.24;for(let j=0;j<12;j++){const left=x-w+j*w/6,right=left+w/6,curve=k=>d.y+h*Math.sin(k*Math.PI/12)**2*(.9+.1*Math.sin(k*.5+d.rotation));triangle('HILLS',[left,d.y,z],[left,curve(j),z],[right,curve(j+1),z]);triangle('HILLS',[left,d.y,z],[right,curve(j+1),z],[right,d.y,z]);}for(let j=0;j<5;j++){const q={...d,x:d.x+(j-2)*d.scale*.46,y:d.y+h*.42,z:d.z+Math.sin(j+d.rotation)*5,rotation:d.rotation};crown('FOREST_FAR',q,5+d.scale*.15,2+d.scale*.06);}}
  else if(lod===2)continue;
  else if(d.kind==='scrub'){boxPiece('SCRUB',d.x,d.y+.25*d.scale,d.z,1.25*d.scale,.55*d.scale,.9*d.scale,d.rotation);if(lod===0)boxPiece('GRASS_DRY',d.x+.25,d.y+.48*d.scale,d.z,.6*d.scale,.4*d.scale,.55*d.scale,d.rotation+.4);}
  else if(lod>0)continue;
  else if(d.kind==='stump'){boxPiece('DEADWOOD',d.x,d.y+.18,d.z,.48,.36,.48,d.rotation);boxPiece('HAY',d.x,d.y+.365,d.z,.40,.015,.4,d.rotation);}
  else if(d.kind==='deadwood'){boxPiece('DEADWOOD',d.x,d.y+.17,d.z,.25,.25,2.5*d.scale,d.rotation);boxPiece('DEADWOOD',d.x+.35,d.y+.1,d.z,.09,.09,1.1,d.rotation+.6);}
  else if(d.kind==='pole'){boxPiece('SCENERY_WOOD',d.x,d.y+2.7,d.z,.18,5.4,.18);boxPiece('SCENERY_METAL',d.x,d.y+4.7,d.z,1.5,.12,.12,d.rotation);}
  else if(d.kind==='gate'){for(const side of [-1,1])boxPiece('SCENERY_WOOD',d.x+Math.sin(d.rotation)*side*1.1,d.y+.7,d.z+Math.cos(d.rotation)*side*1.1,.18,1.4,.18,d.rotation);for(const h of [.4,1.0])boxPiece('SCENERY_WOOD',d.x,d.y+h,d.z,.12,.13,2.1,d.rotation+.045);}
  else if(d.kind==='well'){for(const side of [-1,1]){boxPiece('SCENERY_WOOD',d.x+side*.55,d.y+.45,d.z,.16,.9,1.2);boxPiece('SCENERY_WOOD',d.x,d.y+.45,d.z+side*.55,1.2,.9,.16);}for(const side of [-1,1])boxPiece('SCENERY_WOOD',d.x+side*.62,d.y+1.2,d.z,.10,2.4,.10);boxPiece('SCENERY_ROOF',d.x,d.y+2.35,d.z,1.6,.18,1.5,d.rotation);}
  else if(d.kind==='busStop'){const c=Math.cos(d.rotation),sn=Math.sin(d.rotation),piece=(key,x,y,z,sx,sy,sz)=>boxPiece(key,d.x+c*x+sn*z,d.y+y,d.z-sn*x+c*z,sx,sy,sz,d.rotation);piece('SCENERY_ROOF',0,2.2,0,3.7,.15,1.8);piece('SCENERY_WOOD',0,1.1,.7,3.4,2.2,.12);for(const side of [-1,1])piece('SCENERY_METAL',side*1.55,1.1,-.5,.12,2.2,.12);piece('SCENERY_WOOD',0,.55,0,2.9,.12,.4);}
  else if(d.kind==='canopy'){boxPiece('SCENERY_ROOF',d.x,d.y+2.6,d.z,3.2,.14,3.4,d.rotation);for(const x of [-1.4,1.4])for(const z of [-1.5,1.5])boxPiece('SCENERY_WOOD',d.x+Math.cos(d.rotation)*x+Math.sin(d.rotation)*z,d.y+1.3,d.z-Math.sin(d.rotation)*x+Math.cos(d.rotation)*z,.14,2.6,.14,d.rotation);}
  else if(d.kind==='shed'){boxPiece('SCENERY_WOOD',d.x,d.y+1.1,d.z,3,2.2,3.8,d.rotation);boxPiece('SCENERY_ROOF',d.x,d.y+2.3,d.z,3.3,.23,4.1,d.rotation);}
 }
 const keys=new Set([...Object.keys(terrainColors),...Object.keys(slot),...Object.keys(batches)]);for(const key of keys){if(decorOnly&&!['GRASS_LOW','GRASS_FIELD','GRASS_DRY','SCRUB','DEADWOOD','SCENERY_WOOD','SCENERY_ROOF','SCENERY_METAL','HILLS','FOREST_MID','TRUNK','LEAVES','LEAVES_LIGHT','STONE','FOREST_FAR','HOUSE0','HOUSE1','ROOF0','ROOF1','WINDOW','FENCE','SIGN_POST','HAY'].includes(key))continue;if(!terrainColors[key])continue;const data=batches[key]||{v:[],n:[]};slot[key]=uploadGeometry(data.v,data.n,slot[key],data.uv);}slot._section=section;slot._lod=lod;slot._revision=section.decorationRevision;return slot;
}
function syncWorldMeshes(pos=world.locate(physics.p[0],physics.p[2]).s){const visible=world.sections.filter(q=>!world.circular||sectionDistance(q,pos)<VIEW_CONFIG.drawDistance+40);for(const [id,slot] of chunkSlots)if(!visible.some(q=>q.id===id)){chunkSlots.delete(id);freeSlots.push(slot);}for(const section of visible){const lod=chunkLOD(section,pos);if(!chunkSlots.has(section.id))chunkSlots.set(section.id,buildChunk(section,freeSlots.pop(),lod));else{const slot=chunkSlots.get(section.id);if(slot._section!==section)buildChunk(section,slot,lod);else if(slot._lod!==lod||slot._revision!==section.decorationRevision)buildChunk(section,slot,lod,true);}}}

const terrainColors={RACE_RED:[.87,.15,.10],RACE_WHITE:[.93,.92,.84],RACE_STAKE:[.61,.52,.34],GRASS_LOW:[.48,.46,.31],GRASS_FIELD:[.49,.55,.34],GRASS_DRY:[.69,.63,.41],SCRUB:[.37,.45,.28],DEADWOOD:[.40,.33,.23],SCENERY_WOOD:[.61,.51,.36],SCENERY_ROOF:[.33,.40,.38],SCENERY_METAL:[.51,.54,.51],HILLS:[.52,.58,.47],FOREST_MID:[.30,.40,.28],ASPHALT:[.39,.40,.39],MARKING:[.76,.75,.64],HAY:[.71,.60,.32],HOUSE0:[.62,.48,.33],HOUSE1:[.59,.69,.61],ROOF0:[.46,.22,.17],ROOF1:[.30,.40,.40],WINDOW:[.22,.37,.44],FENCE:[.65,.54,.37],SIGN_POST:[.57,.58,.55],WOOD:[.47,.34,.20],PIT:[.34,.29,.22],HAZARD_ROCK:[.73,.69,.58],EARTH_BUMP:[.72,.57,.36],FOREST_FAR:[.38,.46,.37],ROCK:[.55,.54,.46],GRASS:[.43,.53,.36],DIRT:[.64,.59,.44],SOFT_DIRT:[.55,.44,.30],MUD:[.31,.27,.19],WATER:[.37,.35,.26],WATER_TOP:[.37,.53,.53],TRUNK:[.34,.27,.20],LEAVES:[.22,.36,.25],LEAVES_LIGHT:[.30,.43,.28],STONE:[.48,.50,.44]};syncWorldMeshes();
const car={x:spawn.x,z:spawn.z,a:spawn.yaw,v:0,steer:0,y:spawn.y+.15},keys=new Set(),joy={x:0,y:0,id:null},look={x:0,y:0,id:null},orbit={yaw:0,elevation:CAMERA_CONFIG.chaseElevation,distance:CAMERA_CONFIG.chaseDistance,idle:0},pedals={gas:0,brake:false};
function bindStick(selector,knobSelector,state,steeringOnly=false){const pad=document.querySelector(selector),knob=document.querySelector(knobSelector);function move(e){const r=pad.getBoundingClientRect(),radius=r.width*.35;let x=e.clientX-r.left-r.width/2,y=steeringOnly?0:e.clientY-r.top-r.height/2;const d=Math.hypot(x,y);if(d>radius){x*=radius/d;y*=radius/d;}state.x=x/radius;state.y=-y/radius;knob.style.transform=`translate(${x}px,${y}px)`;e.preventDefault();}function reset(){state.id=null;state.x=state.y=0;knob.style.transform='';}pad.addEventListener('pointerdown',e=>{if(state.id!==null)return;state.id=e.pointerId;pad.setPointerCapture(e.pointerId);move(e);});pad.addEventListener('pointermove',e=>{if(state.id===e.pointerId)move(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===state.id)reset();});return reset;}
const release=bindStick('#stick','#knob',joy,true),lookRelease=()=>{look.id=null;look.x=look.y=0;};
const pedalResets=[bindThrottle(document.querySelector('#gas'),value=>pedals.gas=value)];const brakeButton=document.querySelector('#brake');let brakePointer=null;pedalResets.push(()=>{brakePointer=null;pedals.brake=false;brakeButton.classList.remove('active');});brakeButton.addEventListener('pointerdown',e=>{if(brakePointer!==null)return;brakePointer=e.pointerId;pedals.brake=true;brakeButton.setPointerCapture(e.pointerId);brakeButton.classList.add('active');e.preventDefault();});for(const event of ['pointerup','pointercancel','lostpointercapture'])brakeButton.addEventListener(event,e=>{if(e.pointerId===brakePointer){brakePointer=null;pedals.brake=false;brakeButton.classList.remove('active');}});
let cameraMode='CHASE',cameraSnap=false;const hood=new HoodCamera(visual);document.querySelector('#cam').addEventListener('click',()=>{cameraMode=cameraMode==='CHASE'?'HOOD':'CHASE';document.querySelector('#cam').classList.toggle('active',cameraMode==='HOOD');document.querySelector('#cam').setAttribute('aria-pressed',String(cameraMode==='HOOD'));run.notify(cameraMode,1);releaseFloating();drag=null;hood.reset(visual);cameraSnap=true;});
// Invisible floating camera control, independent from steering and pedals.
let cameraTouch=null;function releaseFloating(){if(!cameraTouch)return;cameraTouch=null;lookRelease();}canvas.addEventListener('pointerdown',e=>{if(cameraMode==='CHASE'&&e.pointerType==='touch'&&e.clientX>=innerWidth/2&&look.id===null){look.id=e.pointerId;cameraTouch={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);e.preventDefault();}});canvas.addEventListener('pointermove',e=>{if(cameraTouch?.id===e.pointerId){let x=e.clientX-cameraTouch.x,y=e.clientY-cameraTouch.y,d=Math.hypot(x,y);if(d>40){x*=40/d;y*=40/d;}look.x=-x/40;look.y=y/40;e.preventDefault();}});for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(cameraTouch?.id===e.pointerId)releaseFloating();});
let drag=null;canvas.addEventListener('pointerdown',e=>{if(cameraMode==='CHASE'&&e.pointerType==='mouse'&&e.clientX>=innerWidth/2){drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(drag&&drag.id===e.pointerId){orbit.yaw-=(e.clientX-drag.x)*.008;orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation-(drag.y-e.clientY)*.006));orbit.idle=0;drag.x=e.clientX;drag.y=e.clientY;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(drag?.id===e.pointerId)drag=null;});
let focus=[spawn.x,spawn.y+1.2,spawn.z];function orbitTarget(dt){const active=look.id!==null||drag!==null;if(active)orbit.idle=0;else orbit.idle+=dt;orbit.yaw+=(Math.abs(look.x)>.08?look.x:0)*1.9*dt;orbit.yaw=Math.atan2(Math.sin(orbit.yaw),Math.cos(orbit.yaw));orbit.elevation=Math.max(.12,Math.min(1.12,orbit.elevation+(Math.abs(look.y)>.08?look.y:0)*1.05*dt));if(orbit.idle>1.6){const blend=1-Math.exp(-1.6*dt);orbit.yaw*=1-blend;orbit.elevation+=(CAMERA_CONFIG.chaseElevation-orbit.elevation)*blend;}focus=focus.map((v,i)=>v+([car.x,car.y+1.05,car.z][i]-v)*(1-Math.exp(-(i===1?3:8)*dt)));const angle=car.a+orbit.yaw,r=(orbit.distance+Math.max(-.15,Math.min(.30,physics.state.longitudinalAcceleration*CAMERA_CONFIG.accelerationOffset)))*Math.cos(orbit.elevation),x=focus[0]-Math.sin(angle)*r,z=focus[2]-Math.cos(angle)*r;return[x,Math.max(focus[1]+orbit.distance*Math.sin(orbit.elevation),height(x,z)+.9),z];}
const allowed=['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'];window.addEventListener('keydown',e=>{if(allowed.includes(e.code)){keys.add(e.code);e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.code));function clear(){keys.clear();releaseFloating();release();lookRelease();drag=null;handHeld=false;pedalResets.forEach(reset=>reset());for(const id of ['#gas','#brake','#handbrake'])document.querySelector(id).classList.remove('active');}window.addEventListener('blur',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();});
let handHeld=false,hudTime=0;function step(dt){const drive=(pedals.brake||keys.has('KeyS')||keys.has('ArrowDown'))?-1:(keys.has('KeyW')||keys.has('ArrowUp')?1:pedals.gas);const steer=Math.abs(joy.x)>.08?joy.x:+(keys.has('KeyD')||keys.has('ArrowRight'))-+(keys.has('KeyA')||keys.has('ArrowLeft'));if(gameMode===GAME_MODE.CIRCUIT&&cup.rescueHold>0){cup.rescueHold-=dt;physics.v=[0,0,0];cup.before(dt);cup.update(dt,animals,farmers);return;}if(gameMode===GAME_MODE.CIRCUIT&&!cup.before(dt)){if(cup.countdown===0)music.setPool('CIRCUIT');updateRaceHUD();return;}physics.advance(dt,{drive,steer,handbrake:handHeld||keys.has('Space')});if(gameMode===GAME_MODE.CIRCUIT){const oldLap=cup.racers[0]?.laps||0;cup.update(dt,animals,farmers);if(cup.racers[0]?.laps>oldLap){animals.clear();farmers.clear();for(const section of world.sections)for(const e of [...(section.animalEvents||[]),...(section.farmerEvents||[])]){e.activated=false;e.completed=false;}}cup.safePlayer();updateRaceHUD();}const roadPoint=world.update(physics.p[0],physics.p[2]);checkpoints.tick(physics,traffic);if(Math.abs(roadPoint.lateral)>34){const side=Math.sign(roadPoint.lateral);physics.p[0]=roadPoint.x+Math.cos(roadPoint.yaw)*34*side;physics.p[2]=roadPoint.z-Math.sin(roadPoint.yaw)*34*side;physics.v[0]*=.9;physics.v[2]*=.9;}if(!world.circular&&Math.abs(physics.p[2])>1000){const dx=physics.p[0],dz=physics.p[2];world.shift(dx,dz);physics.p[0]-=dx;physics.p[2]-=dz;physics.previousPose=null;visual.reset();hood.p[0]-=dx;hood.p[2]-=dz;focus[0]-=dx;focus[2]-=dz;camera[0]-=dx;camera[2]-=dz;feedback.shift(dx,dz);run.mechanical.shift(dx,dz);props.shift(dx,dz);traffic.shift(dx,dz);pickups.shift(dx,dz);animals.shift(dx,dz);farmers.shift(dx,dz);}syncWorldMeshes();visual.update(dt);feedback.update(dt,physics);const origin=visual.matrix;car.x=origin[12];car.y=origin[13];car.z=origin[14];car.a=visual.yaw;car.steer=physics.steer;car.v=physics.state.vehicleSpeed/3.6;sound.update(physics.state,physics.wheels);hudTime+=dt;if(hudTime>=.1){updateHUD();hudTime=0;}}
function rotateX(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]);}function rotateZ(a){const c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,s,0,0,-s,c,0,0,0,0,1,0,0,0,0,1]);}
// Reference-built low-poly Niva. Coordinates in metres, nose at +Z.
function polygonMesh(points){const vv=[],nn=[];for(let i=1;i<points.length-1;i++){const a=points[0],b=points[i],c=points[i+1],normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}return mesh(vv,nn);}
function extrude(profile,width){function half(p){return width/2-(width>1.65?Math.max(0,p[0]-1.60)*.22+Math.max(0,-p[0]-1.66)*.20:0);}const vv=[],nn=[];function tri(a,b,c){const normal=norm(cross(b.map((v,j)=>v-a[j]),c.map((v,j)=>v-a[j])));for(const p of [a,b,c]){vv.push(...p);nn.push(...normal);}}
// Ear clipping preserves the concave openings over all four tyres.
let ids=profile.map((_,i)=>i);const area=profile.reduce((s,p,i)=>{const q=profile[(i+1)%profile.length];return s+p[0]*q[1]-q[0]*p[1];},0),sign=Math.sign(area);const cross2=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const inside=(p,a,b,c)=>sign*cross2(a,b,p)>=-1e-8&&sign*cross2(b,c,p)>=-1e-8&&sign*cross2(c,a,p)>=-1e-8;let guard=0;while(ids.length>2&&guard++<500){let found=false;for(let j=0;j<ids.length;j++){const ia=ids[(j+ids.length-1)%ids.length],ib=ids[j],ic=ids[(j+1)%ids.length],a=profile[ia],b=profile[ib],c=profile[ic];if(sign*cross2(a,b,c)<=1e-8)continue;if(ids.some(k=>k!==ia&&k!==ib&&k!==ic&&inside(profile[k],a,b,c)))continue;for(const side of [-1,1])tri([side*half(a),a[1],a[0]],[side*half(b),b[1],b[0]],[side*half(c),c[1],c[0]]);ids.splice(j,1);found=true;break;}if(!found)throw Error('Car profile triangulation failed');}
for(let i=0;i<profile.length;i++){const a=profile[i],b=profile[(i+1)%profile.length],p=[-half(a),a[1],a[0]],q=[half(a),a[1],a[0]],r=[half(b),b[1],b[0]],t=[-half(b),b[1],b[0]];tri(p,q,r);tri(p,r,t);}return mesh(vv,nn);}
const lower=[[-1.82,.53]];for(const centre of [-1.1,1.1]){const radius=.51,start=Math.asin((.53-.44)/radius);for(let i=0;i<=14;i++){const a=Math.PI-start-(Math.PI-2*start)*i/14;lower.push([centre+radius*Math.cos(a),.44+radius*Math.sin(a)]);}}lower.push([1.82,.53],[1.84,1.06],[1.77,1.145],[.75,1.185],[.55,1.17],[-1.81,1.09]);
const shell=extrude(lower,1.68),cabin=extrude([[-1.81,1.085],[-1.43,1.70],[.17,1.70],[.75,1.18]],1.58);
function sheet(xs,zs,top,side,warp=(x,z)=>z){const pt=(x,z,y)=>[x,y,warp(x,z)];const v=[],n=[];function triangle(a,b,c){const normal=norm(cross(b.map((v,i)=>v-a[i]),c.map((v,i)=>v-a[i])));for(const p of [a,b,c]){v.push(...p);n.push(...normal);}}
for(let j=0;j<zs.length-1;j++)for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],zs[j],top(xs[i],zs[j])),b=pt(xs[i+1],zs[j],top(xs[i+1],zs[j])),c=pt(xs[i+1],zs[j+1],top(xs[i+1],zs[j+1])),d=pt(xs[i],zs[j+1],top(xs[i],zs[j+1]));triangle(a,d,b);triangle(b,d,c);}
for(const x of [xs[0],xs.at(-1)])for(let j=0;j<zs.length-1;j++){const a=pt(x,zs[j],top(x,zs[j])),b=pt(x,zs[j+1],top(x,zs[j+1])),c=pt(x,zs[j+1],side(x,zs[j+1])),d=pt(x,zs[j],side(x,zs[j]));triangle(a,b,c);triangle(a,c,d);}
for(const z of [zs[0],zs.at(-1)])for(let i=0;i<xs.length-1;i++){const a=pt(xs[i],z,top(xs[i],z)),b=pt(xs[i+1],z,top(xs[i+1],z)),c=pt(xs[i+1],z,side(xs[i+1],z)),d=pt(xs[i],z,side(xs[i],z));triangle(a,b,c);triangle(a,c,d);}return mesh(v,n);}
function roofTop(x,z){const across=Math.max(0,1-(x/.815)**2),along=Math.max(0,1-((z+.59)/.89)**4);return 1.704+.09*across+.015*along;}
const roof=sheet([-.815,-.74,-.50,0,.50,.74,.815],[-1.46,-1.37,-1.05,-.55,-.05,.14,.24],roofTop,()=>1.69,(x,z)=>z-(z+.61)*.10*(Math.abs(x)/.815)**6);
function bonnetTop(x,z){return 1.185-(z-.72)*.045+.034*Math.max(0,1-(x/.79)**2);}
const bonnet=sheet([-.79,-.72,-.42,0,.42,.72,.79],[.72,.81,1.22,1.65,1.77,1.83],bonnetTop,(x,z)=>z>1.75?1.065:1.15);
const glazing=[];function panel(points,color){glazing.push({shape:polygonMesh(points),color});}
const green=[.20,.32,.30],dark=[.075,.095,.085],rubber=[.105,.115,.105],glass=[.24,.36,.38],chrome=[.65,.68,.65];
for(const side of [-1,1]){const x=side*.795;
panel([[x,1.16,-1.63],[x,1.47,-1.52],[x,1.65,-1.33],[x,1.65,-.48],[x,1.16,-.48]],dark);
panel([[x+side*.002,1.20,-1.58],[x+side*.002,1.47,-1.47],[x+side*.002,1.60,-1.30],[x+side*.002,1.60,-.53],[x+side*.002,1.20,-.53]],glass);
panel([[x,1.225,-.40],[x,1.65,-.40],[x,1.65,.12],[x,1.225,.57]],dark);
panel([[x+side*.002,1.26,-.35],[x+side*.002,1.60,-.35],[x+side*.002,1.60,.105],[x+side*.002,1.26,.50]],glass);
// Small triangular vent window, separated by a thin frame.
panel([[x+side*.004,1.24,.32],[x+side*.004,1.44,.32],[x+side*.004,1.24,.55]],dark);
panel([[x+side*.006,1.265,.355],[x+side*.006,1.405,.355],[x+side*.006,1.265,.495]],glass);
}
function frontPlane(y,offset=0){return .75-(y-1.18)*.58/.52+offset;}
const windOutline=[[-.71,1.235],[.71,1.235],[.71,1.615],[.665,1.666],[-.665,1.666],[-.71,1.615]];
const windGlass=[[-.678,1.263],[.678,1.263],[.678,1.604],[.645,1.639],[-.645,1.639],[-.678,1.604]];
panel(windOutline.map(([x,y])=>[x,y,frontPlane(y,.01)]),dark);
panel(windGlass.map(([x,y])=>[x,y,frontPlane(y,.015)]),glass);
// Rear glass and trim share one plane, offset slightly from the tailgate.
// The previous non-planar fan intersected the crease in the rear body surface.
function rearPlane(y,offset=0){return -1.81+(y-1.085)*.38/.615-offset;}
const rearOutline=[[-.70,1.20],[.70,1.20],[.70,1.57],[.63,1.65],[-.63,1.65],[-.70,1.57]];
const rearGlass=[[-.665,1.235],[.665,1.235],[.665,1.555],[.614,1.615],[-.614,1.615],[-.665,1.555]];
panel(rearOutline.map(([x,y])=>[x,y,rearPlane(y,.009)]),dark);
panel(rearGlass.map(([x,y])=>[x,y,rearPlane(y,.014)]),glass);
const archDetails=[];for(const side of [-1,1])for(const centre of [-1.1,1.1])for(let i=0;i<18;i++){const a=.18+i*(Math.PI-.36)/18,b=.18+(i+1)*(Math.PI-.36)/18;const points=[];for(const [angle,radius] of [[a,.512],[b,.512],[b,.555],[a,.555]])points.push([side*.846,.44+Math.sin(angle)*radius,centre+Math.cos(angle)*radius]);archDetails.push(polygonMesh(points));}
function linePart(a,b,width,color){const direction=norm(b.map((v,i)=>v-a[i])),right=norm(cross(direction,Math.abs(direction[1])>.9?[1,0,0]:[0,1,0])),up=cross(direction,right),length=Math.hypot(...b.map((v,i)=>v-a[i])),mid=a.map((v,i)=>(v+b[i])/2);const m=new Float32Array([...right.map(v=>v*width),0,...up.map(v=>v*width),0,...direction.map(v=>v*length),0,...mid,1]);draw(cube,mul(body,m),color);}
let body;function part(x,y,z,sx,sy,sz,col){draw(cube,mul(body,matrix(x,y,z,sx,sy,sz)),col);}const facing=new Float32Array([1,0,0,0,0,0,1,0,0,-1,0,0,0,0,0,1]);function roundPart(x,y,z,r,depth,col){draw(cylinder,mul(mul(body,matrix(x,y,z,1,1,1)),mul(facing,matrix(0,0,0,r,depth,r))),col);}
function vehicle(){body=visual.matrix;draw(shell,body,green);draw(cabin,body,green);draw(roof,body,green);draw(bonnet,body,green);for(const panel of glazing)draw(panel.shape,body,panel.color);
part(0,.49,0,1.32,.12,2.6,dark);
// Thin arch mouldings, roof gutters, bonnet stampings and wipers.
for(const arch of archDetails)draw(arch,body,[.23,.32,.28]);
for(const side of [-1,1]){linePart([side*.82,1.699,-1.35],[side*.82,1.699,.12],.018,chrome);linePart([side*.66,bonnetTop(side*.66,.81)+.004,.81],[side*.66,bonnetTop(side*.66,1.68)+.004,1.68],.012,[.29,.38,.33]);linePart([side*.44,1.276,frontPlane(1.276,.027)],[side*.16,1.301,frontPlane(1.301,.027)],.014,dark);linePart([side*.838,1.14,.74],[side*.838,1.12,1.72],.01,dark);part(side*.845,1.08,.96,.009,.055,.14,[.76,.47,.16]);}
// Tailgate perimeter, rear wiper, vents and small licence plates.
linePart([-.73,.71,-1.837],[.73,.71,-1.837],.013,dark);for(const side of [-1,1])linePart([side*.73,.72,-1.837],[side*.73,1.12,-1.837],.013,dark);linePart([.03,1.245,rearPlane(1.245,.025)],[.34,1.27,rearPlane(1.27,.025)],.016,dark);part(0,.648,1.989,.40,.083,.014,[.81,.81,.72]);
for(const side of [-1,1])for(let i=0;i<3;i++)part(side*.803,1.43+i*.039,-1.59,.014,.012,.09,dark);
// Door outlines and recognisable body crease under the glazing.
for(const side of [-1,1]){const x=side*.843;part(x,1.10,-.55,.009,.012,2.32,[.30,.38,.34]);part(x,.80,-.44,.009,.53,.012,dark);part(x,.72,.57,.009,.27,.012,dark);part(x,.548,.03,.009,.012,.9,dark);part(x,1.025,-.24,.025,.035,.15,chrome);part(side*.86,1.23,.52,.11,.028,.035,dark);part(side*.925,1.275,.52,.12,.12,.07,dark);}
// Round lamps, rectangular indicators, narrow grille and plain bumpers.
for(const x of [-.645,.645]){roundPart(x,.93,1.852,.285,.018,dark);lampEmission=environment.headlightIntensity*1.7;roundPart(x,.93,1.873,.237,.023,environment.headlights?[1,.97,.76]:[.88,.87,.70]);roundPart(x-.035,.970,1.889,.065,.01,[.97,.97,.88]);lampEmission=0;part(x,1.112,1.842,.25,.067,.025,dark);part(x,1.115,1.860,.20,.043,.018,[.90,.67,.30]);part(x,.85,-1.833,.17,.27,.025,dark);lampEmission=physics.state.brake>.05?2.7:environment.headlightIntensity*1.6;part(x,.91,-1.849,.135,.13,.018,physics.state.brake>.05?[1,.08,.035]:environment.headlights?[.86,.12,.06]:[.69,.19,.12]);lampEmission=0;part(x,.807,-1.849,.135,.055,.018,[.93,.61,.25]);}
part(0,.86,1.855,.89,.25,.019,dark);for(let i=0;i<4;i++)part(0,.77+i*.057,1.873,.85,.012,.016,chrome);for(let i=-3;i<=3;i++)part(i*.105,.855,1.877,.014,.22,.012,[.32,.37,.34]);part(0,.87,1.896,.055,.075,.01,chrome);
for(const z of [-1.90,1.91]){part(0,.64,z,1.83,.10,.13,chrome);for(const x of [-.61,.61])part(x,.64,z+(z>0?.077:-.077),.11,.16,.025,dark);}
part(0,.77,-1.847,.43,.13,.02,dark);part(0,.773,-1.863,.36,.083,.012,[.83,.83,.75]);part(0,1.04,-1.831,.14,.03,.025,chrome);
// Steel rims with small circular holes; no spinning rectangles outside tyres.
// Rear beam follows both independent wheel contacts.
const left=visual.wheels[2].position,right=visual.wheels[3].position,beam=norm(right.map((v,i)=>v-left[i])),beamUp=norm(cross(rotate(visual.q,[0,0,1]),beam)),beamSide=cross(beam,beamUp),mid=left.map((v,i)=>(v+right[i])/2);draw(cube,new Float32Array([...beam.map(v=>v*1.70),0,...beamUp.map(v=>v*.12),0,...beamSide.map(v=>v*.12),0,...mid,1]),dark);
for(const w of visual.wheels){if(w.detached)continue;const up=rotate(visual.q,[0,1,0]),localForward=rotate(visual.q,[Math.sin(w.steer),0,Math.cos(w.steer)]),axis=w.front?norm(cross(up,localForward)):beam,wheelUp=norm(cross(localForward,axis));let m=new Float32Array([...axis,0,...wheelUp,0,...localForward,0,...w.position.map((v,i)=>v-(i===1?w.visualSink||0:0)),1]);m=mul(m,rotateX(w.angle));const axle=(diameter,width)=>new Float32Array([0,diameter,0,0,-width,0,0,0,0,0,diameter,0,0,0,0,1]);draw(cylinder,mul(m,axle(CAR_CONFIG.wheelRadius*2,.25)),rubber);draw(cylinder,mul(m,axle(.53,.259)),chrome);draw(cylinder,mul(m,axle(.17,.275)),[.40,.44,.41]);for(let i=0;i<6;i++){const a=i*Math.PI/3,local=matrix(Math.sign(w.x)*.134,Math.cos(a)*.18,Math.sin(a)*.18,1,1,1);draw(cylinder,mul(m,mul(local,axle(.075,.008))),dark);}}}
const npcMeshes={};for(const type of ['NIVA','KOPEIKA','TRACTOR']){const raw=npcGeometry(type,{shell,cabin,roof,bonnet,glazing});npcMeshes[type]=Object.fromEntries(Object.entries(raw).map(([key,data])=>[key,mesh(data.v,data.n)]));}
const raceRaw=npcGeometry('NIVA',{shell,cabin,roof,bonnet,glazing},true),raceMeshes=Object.fromEntries(Object.entries(raceRaw).map(([key,data])=>[key,mesh(data.v,data.n)]));
function drawNPCs(){const vehicles=traffic.active.concat(world.sections.flatMap(s=>s.decorations.filter(d=>d.kind==='parked')));for(const n of vehicles){if(Math.hypot(n.x-car.x,n.z-car.z)>VIEW_CONFIG.drawDistance)continue;const mat=matrix(n.x,n.y,n.z,1,1,1,n.rotation),colors={BODY:n.npcType==='TRACTOR'?[.20,.44,.63]:NPC_COLORS[n.colorIndex||0],DARK:[.09,.10,.09],GLASS:[.24,.37,.41],METAL:[.64,.66,.61],LIGHT:[.88,.86,.69],RED:[.65,.18,.13]};for(const [key,shape] of Object.entries(npcMeshes[n.npcType]))draw(shape,mat,colors[key]);}}
function drawPickups(){for(const item of pickups.visible){if(Math.hypot(item.x-car.x,item.z-car.z)>180||traffic.active.some(n=>Math.hypot(n.x-item.x,n.z-item.z)<3.7))continue;const y=item.y+.6+.12*Math.sin(run.time*2+item.phase),root=matrix(item.x,y+.15,item.z,PICKUP_CONFIG.visualScale,PICKUP_CONFIG.visualScale,PICKUP_CONFIG.visualScale,run.time*.5+item.phase),paint=item.type==='FUEL'?[.20,.62,.28]:item.type==='REPAIR'?[.20,.53,.82]:[.65,.37,.13];function piece(x,yy,z,w,h,d,col=paint){draw(cube,mul(root,matrix(x,yy,z,w,h,d)),col);}draw(cylinder,matrix(item.x,item.y+.045,item.z,1.7,.035,1.7),paint);
 if(item.type==='FUEL'){piece(0,0,0,.46,.63,.23);piece(-.16,.40,0,.07,.16,.18);piece(.09,.46,0,.31,.07,.18);piece(.21,.34,0,.10,.08,.20,[.60,.15,.10]);piece(0,0,.126,.19,.25,.02,[.91,.86,.62]);}
 if(item.type==='REPAIR'){piece(0,0,0,.70,.40,.33);piece(0,.24,0,.28,.09,.12,[.74,.76,.71]);piece(0,0,.177,.40,.075,.02,[.96,.95,.85]);piece(0,0,.18,.075,.29,.02,[.96,.95,.85]);}
 if(item.type==='BEER'){draw(cylinder,mul(root,matrix(0,0,0,.25,.50,.25)),paint);draw(cylinder,mul(root,matrix(0,.36,0,.11,.24,.11)),[.26,.21,.12]);piece(0,.51,0,.13,.04,.13,[.86,.76,.49]);piece(0,0,.13,.17,.20,.015,[.93,.82,.53]);}}
}
function drawDetachedWheels(){for(const d of [run,...(gameMode===GAME_MODE.CIRCUIT?cup.ai.map(a=>a.run):[])].flatMap(r=>r.mechanical.debris)){if(!d.active)continue;const m=mul(matrix(...d.p,1,1,1,d.yaw),rotateX(d.angle)),axle=(diameter,width)=>new Float32Array([0,diameter,0,0,-width,0,0,0,0,0,diameter,0,0,0,0,1]);draw(cylinder,mul(m,axle(CAR_CONFIG.wheelRadius*2,.25)),rubber);draw(cylinder,mul(m,axle(.53,.259)),chrome);}}
const runHUD={hp:document.querySelector('#hp-value'),fuel:document.querySelector('#fuel-value'),hpBar:document.querySelector('#hp-bar'),fuelBar:document.querySelector('#fuel-bar'),best:document.querySelector('#best'),beer:document.querySelector('#beer'),toast:document.querySelector('#run-toast'),results:document.querySelector('#run-results'),resultDistance:document.querySelector('#result-distance'),resultBest:document.querySelector('#result-best'),stats:document.querySelector('#result-stats')};
function updateRunHUD(){if(menuOpen){runHUD.results.hidden=true;return;}document.querySelector('#reset').hidden=run.ended;if(typeof menuUntil!=='undefined'&&!transmissionPanel.hidden&&run.time>menuUntil){transmissionPanel.hidden=true;toggle.setAttribute('aria-expanded','false');}const faults=document.querySelector('#mechanical-status');faults.textContent=run.mechanical.indicators;faults.hidden=!faults.textContent;runHUD.hp.textContent=Math.ceil(run.hp);runHUD.fuel.textContent=Math.ceil(run.fuel)+'%';runHUD.hpBar.style.width=run.hp+'%';runHUD.fuelBar.style.width=run.fuel+'%';runHUD.hpBar.classList.toggle('critical',run.hp<=25);runHUD.fuelBar.classList.toggle('critical',run.fuel<=20);runHUD.best.textContent=gameMode===GAME_MODE.CIRCUIT?'ДЕРЕВЕНСКИЙ КУБОК':'BEST '+(run.best/1000).toFixed(1)+' KM';runHUD.beer.hidden=!run.beer||run.ended;runHUD.toast.textContent=run.message||(run.fuel<=0&&!run.ended?'БЕНЗИН ЗАКОНЧИЛСЯ':'');runHUD.toast.hidden=!runHUD.toast.textContent;runHUD.results.hidden=!run.ended;document.querySelector('#result-primary-label').textContent=gameMode===GAME_MODE.CIRCUIT?'ПОЗИЦИЯ':'ПРОБЕГ';document.querySelector('#result-secondary-label').textContent=gameMode===GAME_MODE.CIRCUIT?'TOTAL TIME':'ЛУЧШИЙ';document.querySelector('#result-kicker').textContent=gameMode===GAME_MODE.CIRCUIT?'ДЕРЕВЕНСКИЙ КУБОК / v0.22':'НИВА УСТАЛА / v0.22';document.querySelector('#result-title').textContent=gameMode===GAME_MODE.CIRCUIT?(cup.result?.dnf?'DNF · НИВА УСТАЛА':'ФИНИШ'):'ЗАЕЗД ОКОНЧЕН';if(run.ended&&gameMode===GAME_MODE.CIRCUIT){runHUD.resultDistance.textContent='ПОЗИЦИЯ '+(cup.result?.position||cup.position())+'/10';runHUD.resultBest.textContent=formatTime(cup.result?.time??cup.time);runHUD.stats.textContent='BEST LAP '+formatTime(cup.result?.bestLap)+' · ПОБЕДЫ '+cup.stats.wins+' · ГОНОК '+cup.stats.races;}else if(run.ended){runHUD.resultDistance.textContent=(run.distance/1000).toFixed(1)+' KM';runHUD.resultBest.textContent=(run.best/1000).toFixed(1)+' KM';const s=run.stats;runHUD.stats.textContent=`ДЕРЕВЬЯ ${s.trees} · ЗАБОРЫ ${s.fences} · ЗНАКИ ${s.signs} · ПИВО ${s.beers} · УДАРЫ ${s.collisions} · ПЕРЕВОРОТЫ ${s.rollovers} · ПРИЗЕМЛЕНИЯ ${s.hardLandings}`;}}
function startRun(mode=gameMode){gameMode=mode;menuOpen=false;document.body.classList?.remove('menu-open');document.querySelector('#main-menu').hidden=true;cup.clear();run.mode=mode;run.randomFailures=mode===GAME_MODE.ENDLESS;music.suspended=false;music.setPool(mode===GAME_MODE.CIRCUIT?'CIRCUIT_START':mode);document.body.classList?.toggle('circuit-mode',mode===GAME_MODE.CIRCUIT);raceDecor.clear();transmissionPanel.hidden=true;toggle.setAttribute('aria-expanded','false');menuUntil=0;run.save();const nextSeed=randomSeed(world.seed);environment.reset(nextSeed);rain.reset(nextSeed);if(gameMode===GAME_MODE.CIRCUIT)buildCircuit(world,nextSeed);else world.reset(nextSeed);animals.clear();farmers.clear();run.reset();checkpoints.reset();feedback.seed=world.seed;Object.assign(physics.state,{runEnded:false,engineRunning:true,enginePowerFactor:1,transferRange:'H',centerLocked:false,rearLocked:false,pendingRange:null,pendingCenter:null,pendingRear:null,hp:100,fuel:100});eventAudio.clear();resetToRoad(world.sections[0],18/world.sections[0].length);run.body=physics;run.mechanical.bind(physics,world.seed);run.applyEngine(physics);if(gameMode===GAME_MODE.CIRCUIT){cup.start();raceDecor.build();cup.decor=raceDecor;syncWorldMeshes();for(const ai of cup.ai)ai.feedback.onEvent(e=>{if(Math.hypot(ai.body.p[0]-physics.p[0],ai.body.p[2]-physics.p[2])<70)eventAudio.play(e);});visual.reset();hood.reset(visual);car.x=physics.p[0];car.y=physics.p[1];car.z=physics.p[2];car.a=visual.yaw;car.v=0;focus=[car.x,car.y+1.05,car.z];cameraSnap=true;}updateRunHUD();updateRaceHUD();}
runHUD.beer.addEventListener('click',()=>{run.drink();updateRunHUD();});document.querySelector('#restart-run').addEventListener('click',()=>{if(run.ended)startRun();});feedback.onEvent(e=>{if(e.type==='RUN_END'){if(gameMode===GAME_MODE.CIRCUIT)cup.finish(true);clear();updateRunHUD();}});document.addEventListener('visibilitychange',()=>{if(document.hidden)run.save();});
const hud={gear:document.querySelector('#gear'),rpm:document.querySelector('#rpm'),range:document.querySelector('#range'),center:document.querySelector('#center-lock'),rear:document.querySelector('#rear-lock'),wheels:document.querySelector('#wheel-status')};
function updateHUD(){const s=physics.state;hud.gear.textContent=s.currentGear<0?'R':s.currentGear;document.querySelector('#range-indicator').textContent=s.transferRange;for(const [id,active] of [['#center-indicator',s.centerLocked],['#rear-indicator',s.rearLocked]])document.querySelector(id).classList.toggle('lit',active);hud.rpm.textContent=Math.round(s.currentRPM)+' RPM';hud.range.textContent=s.pendingRange?'H/L · WAIT':'H/L · '+s.transferRange;hud.center.textContent=s.pendingCenter?'C LOCK · WAIT':'C LOCK '+(s.centerLocked?'ON':'OFF');hud.rear.textContent=s.pendingRear?'R LOCK · WAIT':'R LOCK '+(s.rearLocked?'ON':'OFF');hud.center.classList.toggle('active',s.centerLocked);hud.rear.classList.toggle('active',s.rearLocked);hud.range.classList.toggle('active',s.transferRange==='L');hud.center.setAttribute('aria-pressed',String(s.centerLocked));hud.rear.setAttribute('aria-pressed',String(s.rearLocked));document.querySelector('#surface').textContent=[...new Set(physics.wheels.filter(w=>w.contact).map(w=>w.surfaceType||'DIRT'))].join(' / ');if(debug&&!transmissionPanel.hidden)hud.wheels.innerHTML=physics.wheels.map(w=>`<i class="${w.contact&&w.load>100?'contact':'air'}" title="${w.id}: ${Math.round(w.load)} N">${w.id} ${w.surfaceType||'DIRT'}${Math.abs(w.slipRatio)>.22&&w.contact?' ↻':''}</i>`).join('');}
hud.range.addEventListener('click',()=>{physics.requestRange();menuUntil=run.time+4;});hud.center.addEventListener('click',()=>{physics.requestCenter();menuUntil=run.time+4;});hud.rear.addEventListener('click',()=>{physics.requestRear();menuUntil=run.time+4;});const hand=document.querySelector('#handbrake');hand.addEventListener('pointerdown',e=>{handHeld=true;hand.setPointerCapture(e.pointerId);hand.classList.add('active');e.preventDefault();});for(const type of ['pointerup','pointercancel','lostpointercapture'])hand.addEventListener(type,()=>{handHeld=false;hand.classList.remove('active');});document.querySelector('#reset').addEventListener('click',()=>rescue());
const transmissionPanel=document.querySelector('#transmission-panel'),toggle=document.querySelector('#transmission');let menuUntil=0;transmissionPanel.hidden=true;toggle.addEventListener('click',()=>{transmissionPanel.hidden=!transmissionPanel.hidden;menuUntil=run.time+6;toggle.setAttribute('aria-expanded',String(!transmissionPanel.hidden));});
function resetToRoad(section=world.current,u=.15){clear();feedback.clear();collisions.clear();props.clear();traffic.clear();animals.clear();farmers.clear();const p=world.point(section,u);physics.reset(p.x,p.z,p.yaw);physics.previousPose=null;visual.reset();hood.reset(visual);cameraSnap=true;orbit.yaw=0;orbit.elevation=CAMERA_CONFIG.chaseElevation;focus=[p.x,p.y+1.2,p.z];camera=[p.x-Math.sin(p.yaw)*8,p.y+5,p.z-Math.cos(p.yaw)*8];world.update(p.x,p.z);syncWorldMeshes();}
const debugPanel=document.querySelector('#debug-panel');debugPanel.hidden=!debug;document.querySelector('#next-section').addEventListener('click',()=>{const next=world.sections.find(s=>s.id===world.current.id+1);if(next)resetToRoad(next);});document.querySelector('#regenerate').addEventListener('click',()=>startRun());let measuredFPS=60;function updateDebug(){if(debug)document.querySelector('#debug-info').textContent=`${gameMode} · ${music.pool||"—"} · ${world.current.mode} · ${world.current.type} #${world.current.id+1} · SEED ${world.seed} · ${world.sections.length} секций · ${Math.round(measuredFPS)} FPS · ${Math.round(physics.state.vehicleSpeed)} км/ч · G ${physics.state.currentGear} · ${Math.round(physics.state.currentRPM)} RPM · ${physics.state.shiftEventTime?physics.state.shiftEvent: ''} · THR ${Math.round(physics.state.throttle*100)}% · ${cameraMode} · R LOCK ${physics.state.rearLocked?'ON':'OFF'} · SPLIT ${(100*(physics.state.torqueSplit?.[0]??.5)).toFixed(0)}/${(100*(physics.state.torqueSplit?.[1]??.5)).toFixed(0)} · ${physics.wheels.map(w=>w.id+':'+w.surfaceType+'/'+(w.wheelSlip||0).toFixed(2)).join(' ')} · ${world.current.biomeProfile.type} ${world.current.surface} · ${traffic.debug(world.locate(physics.p[0],physics.p[2]).s)} · ${environment.timeOfDay} ${environment.hour.toFixed(1)}h ${environment.weatherState} RAIN ${environment.rainIntensity.toFixed(2)} LIGHTS ${environment.headlights?'ON':'OFF'} PUDDLES ×${environment.puddleMultiplier.toFixed(2)} COWS ${animals.active.filter(a=>a.type==='COW').length} CHICKENS ${animals.active.filter(a=>a.type==='CHICKEN').length} · HP ${run.hp.toFixed(1)} FUEL ${run.fuel.toFixed(1)}% ${run.orientation} · FUEL RATE ${fuelRate(physics.state).toFixed(3)}/s ${(fuelRate(physics.state)*60).toFixed(2)}/min · RANDOM NEXT ${run.mechanical.nextRandomFailureDistance} ROLL ${run.mechanical.lastRandomFailureRoll??"—"} · FARMERS ${farmers.active.length} CROWD ${raceDecor.spectators.filter(a=>a.active).length} AI ${cup.ai.length} MUSIC ${music.musicFileResolved||"—"} · FRONT ${run.mechanical.frontDriveActive} REAR ${run.mechanical.rearDriveActive} WHEEL ${run.mechanical.detachedWheel||"—"} · FAILURE ${run.mechanical.lastFailure} · IMPACT ${(run.lastImpactDamage||0).toFixed(1)} HP · PICKUPS ${pickups.visible.length} · DEBRIS ${props.debris.filter(d=>d.active).length} · GRASS ${physics.wheels.filter(w=>w.surfaceType==='GRASS').length}/4 · FX ${feedback.emitters.length}/${feedback.activeParticles} · TREE ${collisions.lastHit.type} ${(collisions.lastHit.impulse/1000).toFixed(1)}kNs · LAND ${feedback.landingImpact.toFixed(1)}m/s · X ${(physics.p[0]+world.offset[0]).toFixed(1)} Z ${(physics.p[2]+world.offset[1]).toFixed(1)}`;document.querySelector('#distance').textContent=(run.distance/1000).toFixed(1)+' KM';const next=world.sections.find(s=>s.id===world.current.id+1);}

let portraitPaused=false;
function updateOrientation(){const portrait=!!window.matchMedia?.('(orientation: portrait) and (pointer: coarse)').matches;if(portrait!==portraitPaused){clear();portraitPaused=portrait;}document.querySelector('#rotate-hint').setAttribute('aria-hidden',String(!portrait));}
window.addEventListener('resize',updateOrientation);window.addEventListener('orientationchange',updateOrientation);updateOrientation();
document.querySelector('#fullscreen').addEventListener('click',async()=>{try{if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();}catch{}try{if(window.screen?.orientation?.lock)await window.screen.orientation.lock('landscape');}catch{}});
function drawFallingTrees(){for(const fall of [collisions,...(gameMode===GAME_MODE.CIRCUIT?cup.ai.map(a=>a.trees):[])].flatMap(c=>c.falling)){const d=fall.tree,h=d.scale,a=Math.min(Math.PI*.49,(fall.age/1.05)**1.5*Math.PI*.49),up=[fall.direction[0]*Math.sin(a),Math.cos(a),fall.direction[1]*Math.sin(a)],right=[fall.direction[1],0,-fall.direction[0]],front=cross(right,up),base=[d.x,d.y,d.z];function piece(height,width,length,col){const center=base.map((v,i)=>v+up[i]*height);draw(cube,new Float32Array([...right.map(v=>v*width),0,...up.map(v=>v*length),0,...front.map(v=>v*width),0,...center,1]),col);}piece(h*.5,(d.radius||.125)*2,h,terrainColors.TRUNK);piece(h*.8,h*.6,h*.5,d.variant===1?terrainColors.LEAVES_LIGHT:terrainColors.LEAVES);piece(h*1.08,h*.38,h*.4,terrainColors.LEAVES);}}
const particleProgram=gl.createProgram();gl.attachShader(particleProgram,shader(gl.VERTEX_SHADER,`attribute vec3 particlePosition;attribute vec4 particleColor;attribute float particleSize;uniform mat4 particleVP;uniform float viewportHeight;varying vec4 tint;void main(){gl_Position=particleVP*vec4(particlePosition,1.);gl_PointSize=clamp(particleSize*viewportHeight/max(1.,gl_Position.w),2.,64.);tint=particleColor;}`));gl.attachShader(particleProgram,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec4 tint;void main(){float r=length(gl_PointCoord-vec2(.5))*2.;if(r>1.)discard;gl_FragColor=vec4(tint.rgb,tint.a*(1.-smoothstep(.25,1.,r)));}`));gl.linkProgram(particleProgram);if(!gl.getProgramParameter(particleProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(particleProgram));const particleBuffer=gl.createBuffer(),particleData=new Float32Array(feedback.particles.length*8),particleLoc={};for(const key of ['particlePosition','particleColor','particleSize'])particleLoc[key]=gl.getAttribLocation(particleProgram,key);for(const key of ['particleVP','viewportHeight'])particleLoc[key]=gl.getUniformLocation(particleProgram,key);gl.bindBuffer(gl.ARRAY_BUFFER,particleBuffer);gl.bufferData(gl.ARRAY_BUFFER,particleData.byteLength,gl.DYNAMIC_DRAW);
function drawParticles(vp,viewportHeight){let count=0;for(const p of [feedback,...(gameMode===GAME_MODE.CIRCUIT?cup.ai.map(a=>a.feedback):[])].flatMap(f=>f.particles))if(p.active){if(count>=feedback.particles.length)break;const fade=1-p.age/p.life,alpha=p.type==='dust'?.29*fade:p.type==='smoke'?.38*fade:.85*fade;const offset=count*8;for(let i=0;i<3;i++){particleData[offset+i]=p.p[i];particleData[offset+3+i]=p.color[i];}particleData[offset+6]=alpha;particleData[offset+7]=p.size;count++;}if(!count)return;gl.useProgram(particleProgram);gl.bindBuffer(gl.ARRAY_BUFFER,particleBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,particleData.subarray(0,count*8));for(const key of ['p','n','t'])gl.disableVertexAttribArray(loc[key]);for(const [key,size,offset] of [['particlePosition',3,0],['particleColor',4,12],['particleSize',1,28]]){gl.enableVertexAttribArray(particleLoc[key]);gl.vertexAttribPointer(particleLoc[key],size,gl.FLOAT,false,32,offset);}gl.uniformMatrix4fv(particleLoc.particleVP,false,vp);gl.uniform1f(particleLoc.viewportHeight,viewportHeight);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.POINTS,0,count);gl.depthMask(true);gl.disable(gl.BLEND);for(const key of ['particlePosition','particleColor','particleSize'])gl.disableVertexAttribArray(particleLoc[key]);gl.useProgram(program);}
function drawPropDebris(){for(const d of [props,...(gameMode===GAME_MODE.CIRCUIT?cup.ai.map(a=>a.props):[])].flatMap(p=>p.debris))if(d.active){const m=mul(matrix(...d.p,1,1,1),rotateX(d.angle)),shape=mul(m,matrix(0,0,0,...d.size));draw(cube,shape,d.kind==='sign'?[.88,.88,.81]:d.kind==='metal'?[.42,.48,.47]:terrainColors.FENCE);}}
// One small reusable text atlas serves every generated sign.
const signNames=['ЗАЛУПОВКА','КАТЫШКА','МУХОСРАНСКОЕ','КИСЛАЯ ПИСЬКА','БОЛЬШИЕ ПУПЫРКИ','ПЕРДЯЕВО','ДЕРЕВЕНСКИЙ КУБОК'],atlas=document.createElement('canvas');atlas.width=1024;atlas.height=1024;const atlasContext=atlas.getContext('2d');atlasContext.fillStyle='#eeeee4';atlasContext.fillRect(0,0,1024,1024);for(let i=0;i<signNames.length;i++){const y=i*80;atlasContext.strokeStyle='#252b26';atlasContext.lineWidth=5;atlasContext.strokeRect(8,y+6,1008,68);atlasContext.fillStyle='#202921';atlasContext.font='bold 46px sans-serif';atlasContext.textAlign='center';atlasContext.textBaseline='middle';atlasContext.fillText(signNames[i]+(i===6?'':' →'),512,y+41);}
const signTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,signTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,atlas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
const signProgram=gl.createProgram();gl.attachShader(signProgram,shader(gl.VERTEX_SHADER,`attribute vec2 signVertex;uniform mat4 signMVP;uniform vec2 signRow;varying vec2 signUV;void main(){gl_Position=signMVP*vec4(signVertex,0.,1.);signUV=vec2(signVertex.x+.5,signRow.x+(.5-signVertex.y)*signRow.y);}`));gl.attachShader(signProgram,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform sampler2D signAtlas;varying vec2 signUV;void main(){gl_FragColor=texture2D(signAtlas,signUV);}`));gl.linkProgram(signProgram);if(!gl.getProgramParameter(signProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(signProgram));const signLoc={v:gl.getAttribLocation(signProgram,'signVertex'),m:gl.getUniformLocation(signProgram,'signMVP'),r:gl.getUniformLocation(signProgram,'signRow'),tex:gl.getUniformLocation(signProgram,'signAtlas')},signBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,signBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-.5,-.5,.5,-.5,-.5,.5,.5,-.5,.5,.5,-.5,.5]),gl.STATIC_DRAW);
function drawSigns(){gl.useProgram(signProgram);for(const key of ['p','n','t'])gl.disableVertexAttribArray(loc[key]);gl.bindBuffer(gl.ARRAY_BUFFER,signBuffer);gl.vertexAttribPointer(signLoc.v,2,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(signLoc.v);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,signTexture);gl.uniform1i(signLoc.tex,0);function board(text,m){const index=Math.max(0,signNames.indexOf(text));gl.uniform2f(signLoc.r,index*80/1024,80/1024);gl.uniformMatrix4fv(signLoc.m,false,mul(pv,m));gl.drawArrays(gl.TRIANGLES,0,6);}if(world.circular){const p=world.atDistance(CIRCUIT_CONFIG.startLine);board('ДЕРЕВЕНСКИЙ КУБОК',matrix(p.x,p.y+5.3,p.z+.01,10.8,.72,1,p.yaw+Math.PI));}for(const section of world.sections)for(const d of section.decorations)if(d.kind==='sign'&&!d.broken)board(d.text,matrix(d.x,d.y+2.15,d.z,d.width,d.height,1,d.rotation+Math.PI));for(const d of props.debris)if(d.active&&d.kind==='sign')board(d.text,mul(matrix(...d.p,1,1,1),mul(rotateX(d.angle),matrix(0,0,.055,d.size[0],d.size[1],1))));gl.disableVertexAttribArray(signLoc.v);gl.useProgram(program);}
const skyProgram=gl.createProgram();gl.attachShader(skyProgram,shader(gl.VERTEX_SHADER,`attribute vec2 skyVertex;varying vec2 skyUV;void main(){skyUV=skyVertex;gl_Position=vec4(skyVertex,1.,1.);}`));gl.attachShader(skyProgram,shader(gl.FRAGMENT_SHADER,`precision mediump float;varying vec2 skyUV;uniform vec3 skyRight;uniform vec3 skyUp;uniform vec3 skyForward;uniform vec2 skyLens;uniform vec3 skyTopColor;uniform vec3 skyHorizonColor;uniform float skyRain;uniform float skyAmbient;uniform float skyTime;float softCloud(vec2 p){return sin(p.x*.9+sin(p.y*.7))*sin(p.y*.8)+.3*sin(p.x*1.8+p.y*.9);}void main(){vec3 ray=normalize(skyForward+skyRight*skyUV.x*skyLens.x+skyUp*skyUV.y*skyLens.y);float h=clamp(ray.y,0.,1.);vec3 col=mix(skyHorizonColor,skyTopColor,pow(h,.55));vec2 cloud=ray.xz/max(.22,ray.y+.18)*2.4;float cover=smoothstep(.62,1.2,softCloud(cloud+vec2(skyTime*.008,0.))-skyRain*.5);cover*=smoothstep(.02,.30,h);col=mix(col,mix(vec3(.96,.97,.96),vec3(.38,.42,.47),skyRain)*skyAmbient,cover*(.54+skyRain*.30));float sun=pow(max(0.,dot(ray,normalize(vec3(-.5,.85,.3)))),70.);col+=vec3(.10,.08,.045)*sun*skyAmbient*(1.-skyRain);float star=pow(max(0.,sin(ray.x*350.)*sin(ray.z*413.)*sin(ray.y*293.)),40.);col+=vec3(.45,.49,.58)*star*(1.-smoothstep(.28,.48,skyAmbient))*(1.-skyRain);gl_FragColor=vec4(col,1.);}`));gl.linkProgram(skyProgram);if(!gl.getProgramParameter(skyProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(skyProgram));const skyLoc={v:gl.getAttribLocation(skyProgram,'skyVertex')};for(const key of ['skyRight','skyUp','skyForward','skyLens','skyTopColor','skyHorizonColor','skyRain','skyAmbient','skyTime'])skyLoc[key]=gl.getUniformLocation(skyProgram,key);const skyBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);
function drawSky(eye,aim,up,aspect,f){const forward=norm(aim.map((v,i)=>v-eye[i])),right=norm(cross(forward,up)),vertical=cross(right,forward);gl.useProgram(skyProgram);gl.disable(gl.DEPTH_TEST);gl.depthMask(false);for(const key of ['p','n','t'])gl.disableVertexAttribArray(loc[key]);gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);gl.vertexAttribPointer(skyLoc.v,2,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(skyLoc.v);gl.uniform3fv(skyLoc.skyRight,right);gl.uniform3fv(skyLoc.skyUp,vertical);gl.uniform3fv(skyLoc.skyForward,forward);gl.uniform2f(skyLoc.skyLens,aspect/f,1/f);gl.uniform3fv(skyLoc.skyTopColor,environment.skyTop);gl.uniform3fv(skyLoc.skyHorizonColor,environment.skyHorizon);gl.uniform1f(skyLoc.skyRain,environment.rainIntensity);gl.uniform1f(skyLoc.skyAmbient,environment.ambient);gl.uniform1f(skyLoc.skyTime,environment.time);gl.drawArrays(gl.TRIANGLES,0,3);gl.disableVertexAttribArray(skyLoc.v);gl.depthMask(true);gl.enable(gl.DEPTH_TEST);gl.useProgram(program);}
let camera=[spawn.x,spawn.y+5.2,spawn.z+8.7],last=0;gl.enable(gl.DEPTH_TEST);gl.clearColor(.79,.87,.94,1);const speed=document.querySelector('#speed'),gear=document.querySelector('#gear');function frame(t){const rawDt=(t-last)/1000||.016,dt=Math.min(rawDt,.05);last=t;measuredFPS+=(1/Math.max(.001,rawDt)-measuredFPS)*.05;if(!menuOpen&&!portraitPaused&&!run.ended)step(dt);else if(!menuOpen&&run.ended){run.updateClock(dt);feedback.update(dt,physics);}sound.update(physics.state,physics.wheels);eventAudio.update();music.update();updateRunHUD();updateTachometer(dt);const target=orbitTarget(dt);cameraKick*=Math.exp(-9*dt);target[1]+=cameraKick*.12;const hoodView=hood.update(dt,visual,cameraSnap);camera=cameraSnap?target:camera.map((v,i)=>v+(target[i]-v)*(1-Math.exp(-CAMERA_CONFIG.chaseFollow*dt)));camera[1]=Math.max(camera[1],height(camera[0],camera[2])+.7);cameraSnap=false;const dpr=Math.min(devicePixelRatio||1,1.5),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h);}const ceremony=gameMode===GAME_MODE.CIRCUIT&&!menuOpen&&cup.countdown>0?ceremonyCamera():null,eye=ceremony?.eye||(cameraMode==='HOOD'?hoodView.eye:camera),aim=ceremony?.aim||(cameraMode==='HOOD'?hoodView.target:focus),up=cameraMode==='HOOD'?hoodView.up:[0,1,0],f=1/Math.tan((cameraMode==='HOOD'?CAMERA_CONFIG.hoodFov:CAMERA_CONFIG.chaseFov)*Math.PI/360),near=.06,far=650;pv=mul(new Float32Array([f/(w/h),0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]),view(eye,aim,up));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);drawSky(eye,aim,up,w/h,f);applyLighting();gl.uniform3fv(loc.eye,eye);const roadS=world.locate(physics.p[0],physics.p[2]).s;for(const slot of chunkSlots.values()){const section=slot._section,dist=sectionDistance(section,roadS);if(dist>Math.min(VIEW_CONFIG.drawDistance,environment.fogEnd+35))continue;const model=matrix(section.entryTransform.x,0,section.entryTransform.z,1,1,1);for(const [key,shape] of Object.entries(slot))if(terrainColors[key]&&shape.count)draw(shape,model,terrainColors[key],key==='DIRT'||key==='SOFT_DIRT'?1:key==='MUD'||key==='PIT'?2:key==='WOOD'?3:key==='WATER_TOP'?4:key==='GRASS'?5:key==='ASPHALT'?6:key==='MARKING'?7:0);}vehicle();drawRacers();drawStartFinish();drawRaceFlags();drawDetachedWheels();drawNPCs();drawAnimals();drawFarmers();drawPickups();drawFallingTrees();drawPropDebris();drawSigns();drawParticles(pv,h);drawRain(pv,eye,dt);updateDebug();speed.textContent=Math.round(Math.abs(car.v)*3.6);requestAnimationFrame(frame);}canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();clear();document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='3D-контекст потерян. Перезагрузи страницу.';});requestAnimationFrame(frame);
export {raceDecor,ceremonyCamera,gameMode,menuOpen,cup,showMenu,environment,rain,animals,farmers,music,checkpoints,rescue,run,pickups,eventAudio,startRun,traffic,props,feedback,collisions,hood,cameraMode,physics,visual,world,height,groundNormal,grip,sampleSurface,orbit,pedals,chunkSlots,freeSlots,resetToRoad};

function rescue(){if(run.ended||menuOpen)return false;const target=gameMode===GAME_MODE.CIRCUIT?circuitRescueTarget():checkpoints.target(physics,traffic);if(!target){run.notify('НЕТ БЕЗОПАСНОЙ ТОЧКИ');return false;}clear();const p=world.point(target.section,target.u);physics.reset(p.x,p.z,p.yaw);run.applyEngine(physics);const callback=physics.terrain.afterStep;physics.terrain.afterStep=()=>{};try{for(let i=0;i<8;i++)physics.advance(.05,{drive:0,steer:0,handbrake:true});}finally{physics.terrain.afterStep=callback;}physics.v=[0,0,0];physics.omega=[0,0,0];physics.wheels.forEach(w=>w.omega=0);physics.state.vehicleSpeed=0;physics.state.stepDistance=0;physics.previousPose=null;visual.reset();hood.reset(visual);cameraSnap=true;orbit.yaw=0;orbit.elevation=CAMERA_CONFIG.chaseElevation;focus=[physics.p[0],physics.p[1]+1.05,physics.p[2]];car.x=physics.p[0];car.y=physics.p[1];car.z=physics.p[2];car.a=p.yaw;car.v=0;world.update(p.x,p.z);syncWorldMeshes();feedback.airTime=0;feedback.lastVY=0;run.damageImmuneUntil=run.time+CHECKPOINT_CONFIG.immunity;if(gameMode===GAME_MODE.CIRCUIT){cup.racers[0].previousP=physics.p.slice();cup.rescueHold=.75;}run.notify('НА ТРАССЕ');return true;}
let displayedRPM=850;function updateTachometer(dt){displayedRPM+=(physics.state.currentRPM-displayedRPM)*(1-Math.exp(-12*dt));const arc=document.querySelector('#rpm-arc');arc.style.strokeDasharray=`${Math.min(1,Math.max(0,displayedRPM/6500))*100} 100`;document.querySelector('#rpm-display').textContent=Math.round(displayedRPM/50)*50+' RPM';document.querySelector('#speed-arc').style.strokeDasharray=`${Math.min(1,Math.abs(physics.state.vehicleSpeed)/140)*100} 100`;document.querySelector('#rpm-needle').style.transform=`rotate(${-135+Math.min(1,Math.max(0,displayedRPM/6500))*270}deg)`;}
function applyLighting(){const m=visual.matrix,direction=norm(rotate(visual.q,[0,-.02,1])),origin=[m[12]+m[8]*1.85+m[4]*.93,m[13]+m[9]*1.85+m[5]*.93,m[14]+m[10]*1.85+m[6]*.93];gl.uniform3fv(loc.skyFog,environment.skyHorizon);gl.uniform3fv(loc.daylightColor,environment.lightColor);gl.uniform1f(loc.ambientLevel,environment.ambient);gl.uniform1f(loc.wetness,environment.wetness);gl.uniform1f(loc.headlights,environment.headlightIntensity);gl.uniform1f(loc.headRange,ENVIRONMENT_CONFIG.headlightRange);gl.uniform3fv(loc.headOrigin,origin);gl.uniform3fv(loc.headDirection,direction);gl.uniform2f(loc.fogLimits,environment.fogStart,environment.fogEnd);}
function drawAnimals(){for(const a of animals.active){const root=matrix(a.x,a.y,a.z,1,1,1,a.rotation),cream=[.87,.83,.71],black=[.17,.16,.14];function piece(x,y,z,w,h,d,color=cream){draw(cube,mul(root,matrix(x,y,z,w,h,d)),color);}if(a.type==='COW'){piece(0,1.06,-.15,.80,.70,1.78);piece(0,1.36,.89,.47,.54,.65);piece(0,1.21,1.27,.48,.25,.26,[.66,.51,.42]);for(const x of [-.29,.29])for(const z of [-.69,.51]){const swing=a.standing?0:Math.sin(a.age*4+z*5+x*7)*.08;piece(x,.43,z+swing,.13,.83,.16,black);}for(const side of [-1,1]){piece(side*.415,1.15,-.35,.015,.37,.58,black);piece(side*.416,.99,.30,.015,.23,.30,black);piece(side*.31,1.55,.95,.22,.08,.20);piece(side*.23,1.43,1.07,.017,.07,.075,black);piece(side*.17,1.70,.89,.06,.22,.07,[.78,.73,.55]);}piece(0,.75,-1.10,.06,.48,.07,black);}else{const bob=Math.sin(a.age*16)*.035;piece(0,.31+bob,0,.40,.34,.43);piece(0,.51+bob,.25,.22,.28,.22);piece(0,.52+bob,.40,.12,.08,.14,[.81,.48,.18]);piece(0,.67+bob,.25,.08,.11,.16,[.73,.13,.07]);piece(0,.40,-.29,.16,.28,.14,[.55,.48,.37]);for(const x of [-.10,.10])piece(x,.09,Math.sin(a.age*20+x*10)*.025,.045,.18,.075,[.69,.41,.15]);}}for(const d of animals.debris)if(d.active)draw(cube,mul(matrix(...d.p,1,1,1),mul(rotateZ(d.angle),matrix(0,0,0,...d.size))),d.color);}
const rainProgram=gl.createProgram();gl.attachShader(rainProgram,shader(gl.VERTEX_SHADER,`attribute vec3 rainPosition;uniform mat4 rainVP;void main(){gl_Position=rainVP*vec4(rainPosition,1.);}`));gl.attachShader(rainProgram,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform vec4 rainColor;void main(){gl_FragColor=rainColor;}`));gl.linkProgram(rainProgram);if(!gl.getProgramParameter(rainProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(rainProgram));const rainLoc={p:gl.getAttribLocation(rainProgram,'rainPosition'),vp:gl.getUniformLocation(rainProgram,'rainVP'),color:gl.getUniformLocation(rainProgram,'rainColor')},rainBuffer=gl.createBuffer(),rainData=new Float32Array(ENVIRONMENT_CONFIG.rainDrops*6);gl.bindBuffer(gl.ARRAY_BUFFER,rainBuffer);gl.bufferData(gl.ARRAY_BUFFER,rainData.byteLength,gl.DYNAMIC_DRAW);
function drawRain(vp,eye,dt){rain.update(dt,environment.rainIntensity,physics.state.vehicleSpeed);if(!rain.count)return;for(let i=0;i<rain.count;i++){const p=rain.drops[i],k=i*6;rainData[k]=eye[0]+p.x;rainData[k+1]=eye[1]-3+p.y;rainData[k+2]=eye[2]+p.z;rainData[k+3]=rainData[k]-.07;rainData[k+4]=rainData[k+1]-p.length;rainData[k+5]=rainData[k+2];}gl.useProgram(rainProgram);for(const key of ['p','n','t'])gl.disableVertexAttribArray(loc[key]);gl.bindBuffer(gl.ARRAY_BUFFER,rainBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,rainData.subarray(0,rain.count*6));gl.enableVertexAttribArray(rainLoc.p);gl.vertexAttribPointer(rainLoc.p,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(rainLoc.vp,false,vp);gl.uniform4f(rainLoc.color,.66,.76,.86,.26+environment.rainIntensity*.18);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.LINES,0,rain.count*2);gl.depthMask(true);gl.disable(gl.BLEND);gl.disableVertexAttribArray(rainLoc.p);gl.useProgram(program);}

document.querySelector('#debug-time').addEventListener('click',()=>{const hours=[8,12,19,0];environment.forceHour=hours[(hours.indexOf(environment.forceHour)+1)%hours.length];environment.update(0);});document.querySelector('#debug-weather').addEventListener('click',()=>{environment.forceWeather=environment.forceWeather==='RAIN'?'CLEAR':'RAIN';environment.update(0);});

function drawFarmers(){for(const a of farmers.active.concat(gameMode===GAME_MODE.CIRCUIT?raceDecor.spectators.filter(a=>a.active&&Math.hypot(a.x-car.x,a.z-car.z)<RACE_DECOR_CONFIG.drawDistance):[])){let root=matrix(a.x,a.y,a.z,a.scale||1,a.scale||1,a.scale||1,a.rotation);if(a.hit)root=mul(root,mul(rotateZ(a.tumble),rotateX(.9)));const swing=a.running?Math.sin(a.age*9+a.phase)*.28:Math.sin(a.age*2+a.phase)*.025,shirt=a.color||[.34,.46,.53],pants=[.22,.27,.31],skin=[.74,.57,.40],hat=[.53,.43,.26];function piece(x,y,z,w,h,d,color,tilt=0){draw(cube,mul(root,mul(matrix(x,y,z,1,1,1),mul(rotateX(tilt),matrix(0,0,0,w,h,d)))),color);}piece(0,1.10,0,.58,.65,.34,shirt);piece(0,1.59,.015,.33,.36,.32,skin);piece(0,1.80,0,.41,.12,.38,hat);piece(0,1.75,.20,.44,.04,.20,hat);for(const side of [-1,1]){piece(side*.15,.43,side*swing*.15,.21,.78,.24,pants,side*swing);piece(side*.40,a.scale?1.35:1.07,0,.15,.60,.17,shirt,a.scale?.85+Math.sin(a.age*3+a.phase)*.2:-side*swing);piece(side*.15,.10,.10,.23,.16,.36,[.12,.13,.11]);}piece(0,1.55,.19,.16,.055,.04,[.29,.24,.17]);}}

function formatTime(time){if(time==null)return '—';const minutes=Math.floor(time/60);return minutes+':'+(time%60).toFixed(2).padStart(5,'0');}
function updateRaceHUD(){const hud=document.querySelector('#race-hud');hud.hidden=menuOpen||gameMode!==GAME_MODE.CIRCUIT;document.querySelector('#countdown').hidden=menuOpen||gameMode!==GAME_MODE.CIRCUIT||cup.countdown<=-1;if(gameMode!==GAME_MODE.CIRCUIT)return;const r=cup.racers[0];if(!r)return;document.querySelector('#race-position').textContent='POS '+cup.position()+'/10';document.querySelector('#race-lap').textContent='LAP '+Math.min(3,r.laps+1)+'/3';document.querySelector('#race-times').textContent='LAP '+formatTime(cup.time-r.lapStart)+' · LAST '+formatTime(r.lastLap)+' · BEST '+formatTime(r.bestLap);const countdown=document.querySelector('#countdown');countdown.textContent=cup.countdown>0?Math.ceil(cup.countdown):'ГАЗ!';countdown.hidden=cup.countdown>3||cup.time>1||cup.finished;}
function showMenu(){run.save();physics.state.engineRunning=false;clear();menuOpen=true;cup.clear();raceDecor.clear();document.body.classList?.remove('circuit-mode');animals.clear();farmers.clear();traffic.clear();feedback.clear();runHUD.results.hidden=true;document.querySelector('#main-menu').hidden=false;document.body.classList?.add('menu-open');document.querySelector('#menu-cup-stats').textContent='ПОБЕДЫ '+cup.stats.wins+' · ГОНОК '+cup.stats.races;document.querySelector('#menu-best').textContent='BEST '+(run.best/1000).toFixed(1)+' KM';document.querySelector('#race-hud').hidden=true;document.querySelector('#countdown').hidden=true;music.suspended=true;music.audio?.pause();}
function circuitRescueTarget(){const r=cup.racers[0];let s=r.safeS||20;const next=cup.progress.gates[r.nextGate].s,p=world.atDistance(s);if(!checkpoints.safe({...p,width:p.section.width,lateral:0},null,{active:cup.ai.map(a=>({x:a.body.p[0],z:a.body.p[2]}))})){for(let d=8;d<80;d+=8){const q=world.atDistance(s-d);if(checkpoints.safe({...q,width:q.section.width,lateral:0},null,{active:[]}))return{section:q.section,u:q.u};}return{section:world.sections[0],u:20/world.sections[0].length};}return{section:p.section,u:p.u};}
function drawRacers(){if(gameMode!==GAME_MODE.CIRCUIT)return;for(const r of cup.ai){if(r.dnf&&cup.time-r.dnfAt>3)continue;const b=r.body;if(Math.hypot(b.p[0]-car.x,b.p[2]-car.z)>VIEW_CONFIG.drawDistance)continue;const mat=b.matrix(),colors={BODY:r.color,DARK:[.09,.10,.09],GLASS:[.24,.37,.41],METAL:[.64,.66,.61],LIGHT:[.88,.86,.69],RED:[.65,.18,.13]};for(const [key,shape] of Object.entries(raceMeshes))draw(shape,mat,colors[key],0,key==='LIGHT'?environment.headlightIntensity*1.7:key==='RED'?(b.state.brake>.05?2.7:environment.headlightIntensity):0);for(const w of b.wheels){if(w.detached)continue;const point=b.point([w.x,b.c.mountHeight-w.length,w.z]),yaw=Math.atan2(rotate(b.q,[0,0,1])[0],rotate(b.q,[0,0,1])[2])+w.steer,m=mul(matrix(...point,1,1,1,yaw),rotateX(w.angle)),axle=new Float32Array([0,.88,0,0,-.25,0,0,0,0,0,.88,0,0,0,0,1]);draw(cylinder,mul(m,axle),rubber);}}
}
function drawStartFinish(){if(!world.circular)return;const p=world.atDistance(CIRCUIT_CONFIG.startLine),root=matrix(p.x,p.y,p.z,1,1,1,p.yaw);for(const side of [-1,1])draw(cube,mul(root,matrix(side*5.6,2.65,0,.24,5.3,.24)),[.7,.69,.59]);draw(cube,mul(root,matrix(0,5.3,0,11.5,.9,.24)),[.31,.42,.34]);for(let i=0;i<12;i++)for(let j=0;j<2;j++)draw(cube,mul(root,matrix(-4.4+i*.8,.035,j*.42-.2,.79,.025,.4)),(i+j)%2?[.22,.24,.22]:[.86,.85,.72]);for(let row=0;row<5;row++)for(const side of [-1,1]){const q=world.atDistance(CIRCUIT_CONFIG.gridFront-row*CIRCUIT_CONFIG.gridGap),m=matrix(q.x,q.y+.025,q.z,1,1,1,q.yaw);draw(cube,mul(m,matrix(side*1.6,0,0,1.9,.02,.10)),[.85,.84,.73]);}}
document.querySelector('#mode-endless').addEventListener('click',()=>startRun(GAME_MODE.ENDLESS));document.querySelector('#mode-circuit').addEventListener('click',()=>startRun(GAME_MODE.CIRCUIT));document.querySelector('#back-menu').addEventListener('click',showMenu);showMenu();

function ceremonyCamera(){const elapsed=10-cup.countdown,grid=world.atDistance(70),angle=grid.yaw-.9+elapsed*.38,radius=23-4*Math.min(1,elapsed/6),eye=[grid.x+Math.sin(angle)*radius,grid.y+7.0-Math.sin(elapsed*.35)*1.5,grid.z+Math.cos(angle)*radius],aim=[grid.x,grid.y+1.25,grid.z];if(elapsed>6){const blend=Math.min(1,(elapsed-6)/4),u=blend*blend*(3-2*blend),normalEye=cameraMode==='HOOD'?hood.p:camera;return{eye:eye.map((v,i)=>v*(1-u)+normalEye[i]*u),aim:aim.map((v,i)=>v*(1-u)+focus[i]*u)};}return{eye,aim};}
function drawRaceFlags(){if(!world.circular||!cup.progress)return;const next=cup.racers[0]?.nextGate;for(let i=0;i<cup.progress.gates.length;i++){const p=cup.progress.gates[i];if(Math.hypot(p.x-car.x,p.z-car.z)>200)continue;const active=i===next,root=matrix(p.x,p.y,p.z,1,1,1,p.yaw),color=active?[1.0,.76,.035]:[.19,.81,.66];for(const side of [-1,1]){const x=side*(p.section.width/2+2.5);draw(cube,mul(root,matrix(x,3.15,0,.10,6.3,.10)),[.88,.89,.79],0,.5);draw(cube,mul(root,matrix(x+side*.38,3.8,0,.76,4.8,.09)),color,0,active?1.5:.75);for(const y of [1.9,3.1,4.3,5.5])draw(cube,mul(root,matrix(x+side*.38,y,-.06,.55,.10,.025)),[.97,.97,.83],0,1);if(active)draw(cube,mul(root,matrix(x+side*.38,6.16,0,1.0,.20,.13)),[1,.88,.12],0,1.6);}}}
