import {rotate} from './physics.js?v=020';
export const MECHANICAL_CONFIG={minMechanicalDamage:10,failureChance:[.04,.12,.24],wheelDetachChance:[.01,.025,.07],damageBands:[20,35],maxDetachedWheels:1,wheelLife:4,debrisPool:4,landingMinDamage:20,randomFailureSpacing:200,randomFailureChance:.01,randomFailureWeights:{FRONT_DRIVE_FAILURE:.40,REAR_DRIVE_FAILURE:.40,WHEEL_DETACHED:.20}};
const eligible=new Set(['TREE_HIT','HOUSE_HIT','TRAFFIC_HIT','COW_HIT','ROLLOVER_IMPACT','HARD_LANDING']);
export class MechanicalDamage{
 constructor(feedback){this.feedback=feedback;this.body=null;this.debris=Array.from({length:MECHANICAL_CONFIG.debrisPool},()=>({active:false}));this.reset();}
 reset(seed=1){this.seed=seed>>>0;this.distanceSeed=(seed^0x68bc21eb)>>>0;this.frontDriveActive=true;this.rearDriveActive=true;this.detachedWheel=null;this.nextRandomFailureDistance=MECHANICAL_CONFIG.randomFailureSpacing;this.lastRandomFailureRoll=null;this.randomChecks=0;this.lastFailure='—';this.lastImpactDamage=0;this.debris.forEach(d=>d.active=false);this.apply();}
 bind(body,seed){this.body=body;if(seed!==undefined){this.seed=seed>>>0;this.distanceSeed=(seed^0x68bc21eb)>>>0;}this.apply();}
 random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
 apply(){if(!this.body)return;Object.assign(this.body.state,{frontDriveActive:this.frontDriveActive,rearDriveActive:this.rearDriveActive,detachedWheel:this.detachedWheel});for(const w of this.body.wheels){w.detached=w.id===this.detachedWheel;if(w.detached){w.contact=false;w.load=w.longForce=w.sideForce=w.omega=w.driveTorque=w.brakeApplied=0;}}}
 impact(type,damage,event={}){this.lastImpactDamage=damage;if(!this.body||!eligible.has(type)||damage<MECHANICAL_CONFIG.minMechanicalDamage||(type==='HARD_LANDING'&&damage<MECHANICAL_CONFIG.landingMinDamage))return false;const band=damage>=MECHANICAL_CONFIG.damageBands[1]?2:damage>=MECHANICAL_CONFIG.damageBands[0]?1:0,roll=this.random();if(roll>=MECHANICAL_CONFIG.failureChance[band])return false;
 const wheelAvailable=this.body.wheels.filter(w=>w.detached).length<MECHANICAL_CONFIG.maxDetachedWheels;
 if(wheelAvailable&&roll<MECHANICAL_CONFIG.wheelDetachChance[band])return this.fail('WHEEL_DETACHED',this.chooseWheel(type,event),event);
 // Keep one working axle: a mechanical event should leave a way to reach repair.
 if(this.frontDriveActive&&this.rearDriveActive)return this.fail(this.random()<.5?'FRONT_DRIVE_FAILURE':'REAR_DRIVE_FAILURE',null,event);return false;}
 distanceRandom(){this.distanceSeed=(Math.imul(this.distanceSeed,1664525)+1013904223)>>>0;return this.distanceSeed/4294967296;}
 checkDistance(distance){while(distance>=this.nextRandomFailureDistance){this.nextRandomFailureDistance+=MECHANICAL_CONFIG.randomFailureSpacing;this.randomChecks++;const roll=this.lastRandomFailureRoll=this.distanceRandom();if(roll>=MECHANICAL_CONFIG.randomFailureChance||!this.body)continue;const choices=[];if(this.frontDriveActive&&this.rearDriveActive)choices.push('FRONT_DRIVE_FAILURE','REAR_DRIVE_FAILURE');if(!this.detachedWheel)choices.push('WHEEL_DETACHED');if(!choices.length)continue;const total=choices.reduce((n,t)=>n+MECHANICAL_CONFIG.randomFailureWeights[t],0);let pick=this.distanceRandom()*total,type=choices.at(-1);for(const t of choices){pick-=MECHANICAL_CONFIG.randomFailureWeights[t];if(pick<0){type=t;break;}}const alive=this.body.wheels.filter(w=>!w.detached),id=type==='WHEEL_DETACHED'?alive[Math.min(alive.length-1,Math.floor(this.distanceRandom()*alive.length))].id:null;this.fail(type,id,{randomFailure:true});}}
 chooseWheel(type,event){const wheels=this.body.wheels.filter(w=>!w.detached);let weights;if(type==='HARD_LANDING')weights=wheels.map(w=>Math.max(100,w.load||w.contactForce||0));else if(event.position){const q=this.body.q,p=rotate([-q[0],-q[1],-q[2],q[3]],event.position.map((v,i)=>v-this.body.p[i]));weights=wheels.map(w=>1+(Math.sign(w.x)===Math.sign(p[0])?Math.abs(p[0])*3:0)+(Math.sign(w.z)===Math.sign(p[2])?Math.abs(p[2])*3:0));}else weights=wheels.map(()=>1);let r=this.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<wheels.length;i++){r-=weights[i];if(r<=0)return wheels[i].id;}return wheels.at(-1).id;}
 fail(type,wheelId=null,event={}){if(!this.body)return false;if(type==='FRONT_DRIVE_FAILURE'){if(!this.frontDriveActive||!this.rearDriveActive)return false;this.frontDriveActive=false;}else if(type==='REAR_DRIVE_FAILURE'){if(!this.rearDriveActive||!this.frontDriveActive)return false;this.rearDriveActive=false;}else if(type==='WHEEL_DETACHED'){if(this.detachedWheel||!this.body.wheels.some(w=>w.id===wheelId))return false;const w=this.body.wheels.find(w=>w.id===wheelId),d=this.debris.find(d=>!d.active)||this.debris[0],out=rotate(this.body.q,[Math.sign(w.x)*3,2,0]);Object.assign(d,{active:true,p:w.position.slice(),v:this.body.v.map((v,i)=>v+out[i]),angle:w.angle,spin:w.omega||12,yaw:Math.atan2(rotate(this.body.q,[0,0,1])[0],rotate(this.body.q,[0,0,1])[2]),age:0});this.detachedWheel=wheelId;}else return false;this.lastFailure=type;this.apply();this.feedback.emit(type,{wheel:wheelId,position:event.position||this.body.p.slice(),impulse:event.impulse||0,randomFailure:!!event.randomFailure});return true;}
 repair(){this.frontDriveActive=this.rearDriveActive=true;this.detachedWheel=null;this.debris.forEach(d=>d.active=false);this.apply();}
 tick(dt){for(const d of this.debris){if(!d.active)continue;d.age+=dt;if(d.age>=MECHANICAL_CONFIG.wheelLife){d.active=false;continue;}d.v[1]-=9.81*dt;for(let i=0;i<3;i++)d.p[i]+=d.v[i]*dt;const ground=this.body.terrain.height(d.p[0],d.p[2])+.44;if(d.p[1]<ground){d.p[1]=ground;if(d.v[1]<0)d.v[1]*=-.30;d.v[0]*=Math.exp(-dt*2);d.v[2]*=Math.exp(-dt*2);}d.angle+=d.spin*dt;}}
 shift(dx,dz){for(const d of this.debris)if(d.active){d.p[0]-=dx;d.p[2]-=dz;}}
 get indicators(){return[!this.frontDriveActive?'F DRIVE ✕':'',!this.rearDriveActive?'R DRIVE ✕':'',this.detachedWheel?this.detachedWheel+' ✕':''].filter(Boolean).join(' · ');}
}
