// Add each new filename here once. Optional files live next to index.html.
export const MUSIC_TRACKS=['music1.mp3','music2.mp3','music3.mp3','music4.mp3'];
export const MUSIC_POOLS={ENDLESS:{prefix:'music',maxTracks:64},CIRCUIT:{prefix:'race',maxTracks:64},CIRCUIT_START:{files:['racestart']},RUN_END:{files:['racestart']}};
export async function discoverTracks(pool,fetcher=globalThis.fetch){const available=[];if(!fetcher)return available;if(pool.files){for(const base of pool.files)for(const ext of ['mp3','MP3']){const file=base+'.'+ext;try{const response=await fetcher(new URL(file,globalThis.location?.href||'http://localhost/').href,{method:'HEAD',cache:'no-cache'});if(response.ok&&!(response.headers?.get?.('content-type')||'').includes('text/html')){available.push(file);break;}}catch{}}return available;}let next=1;await Promise.all(Array.from({length:4},async()=>{while(next<=pool.maxTracks){const n=next++;for(const ext of ['mp3','MP3']){const file=pool.prefix+n+'.'+ext;try{const response=await fetcher(new URL(file,globalThis.location?.href||'http://localhost/').href,{method:'HEAD',cache:'no-cache'}),type=response.headers?.get?.('content-type')||'';if(response.ok&&!type.includes('text/html')){available.push(file);break;}}catch{}}}}));return available.sort((a,b)=>Number(a.match(/\d+/)[0])-Number(b.match(/\d+/)[0]));}
export const MUSIC_CONFIG={volume:.096,duckVolume:.036,duckSeconds:.55};
export class MusicPlayer{
 constructor(engine,tracks=MUSIC_TRACKS,makeAudio=()=>new Audio(),random=Math.random){this.engine=engine;this.tracks=[...new Set(tracks.map(t=>t.replace(/\.mp3$/i,'')+'.mp3'))];this.resolved=new Map();this.musicFileResolved=null;this.random=random;this.failed=new Set();this.previous=null;this.current=null;this.unlocked=false;this.retry=false;this.duckUntil=0;this.audio=null;this.pending=false;this.generation=0;try{this.audio=makeAudio();this.audio.preload='none';this.audio.loop=false;this.audio.volume=MUSIC_CONFIG.volume;this.audio.addEventListener('ended',()=>{if((this.pool==='CIRCUIT_START'||this.pool==='RUN_END')){this.current=null;this.musicFileResolved=null;this.audio.pause();}else this.next();});this.audio.addEventListener('error',()=>{if(!('error' in this.audio)||this.audio.error)this.fail(this.generation);});}catch{} }
 async setPool(mode,force=false){this.fade=null;if(this.pool===mode&&!force)return;this.pool=mode;this.poolGeneration=(this.poolGeneration||0)+1;const generation=this.poolGeneration;this.audio?.pause();this.generation++;this.current=this.previous=this.musicFileResolved=null;this.pending=false;this.failed.clear();this.resolved.clear();this.tracks=[];if(mode==='CIRCUIT_START')this.racePreload=discoverTracks(MUSIC_POOLS.CIRCUIT);const files=await(mode==='CIRCUIT'&&this.racePreload?this.racePreload:discoverTracks(MUSIC_POOLS[mode]));if(generation!==this.poolGeneration)return;for(const filename of files){const canonical=filename.replace(/\.mp3$/i,'.mp3');this.tracks.push(canonical);this.resolved.set(canonical,filename);}this.next();}
 unlock(){if(!this.audio)return;this.unlocked=true;if(this.engine.enabled){if(this.current){this.retry=false;this.play();}else{if(!this.tracks.length&&!this.warmed){this.warmed=true;try{this.audio.src='data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=';this.audio.play()?.catch(()=>{});}catch{}}this.next();}}}
 candidates(){const available=this.tracks.filter(t=>!this.failed.has(t));return available.length>1?available.filter(t=>t!==this.previous):available;}
 next(){if(this.suspended||!this.unlocked||!this.audio||!this.engine.enabled)return;const options=this.candidates();if(!options.length){this.current=null;this.audio.pause();return;}const chosen=options[Math.min(options.length-1,Math.floor(this.random()*options.length))];this.current=chosen;this.extensionAttempt=this.resolved.get(chosen)?.endsWith('.MP3')?1:0;this.source(this.resolved.get(chosen)||chosen);}
 source(filename){this.generation++;this.pending=false;this.musicFileResolved=filename;this.audio.src=new URL(filename,globalThis.location?.href||'http://localhost/').href;this.audio.load?.();this.play();}
 play(){if(this.pending)return;this.pending=true;const generation=this.generation;try{const p=this.audio.play();p?.then(()=>{if(generation!==this.generation)return;this.pending=false;this.previous=this.current;this.retry=false;this.resolved.set(this.current,this.musicFileResolved);}).catch(error=>{if(generation!==this.generation)return;this.pending=false;if(error?.name==='AbortError')return;if(error?.name==='NotAllowedError'){this.retry=true;return;}this.fail(generation);});if(!p?.then)this.pending=false;}catch{this.pending=false;this.fail(generation);}}
 fail(generation=this.generation){if(generation!==this.generation)return;this.pending=false;if(!this.current)return;if(this.extensionAttempt===0){this.extensionAttempt=1;this.source(this.current.replace(/\.mp3$/i,'.MP3'));return;}this.failed.add(this.current);this.resolved.delete(this.current);this.current=null;this.musicFileResolved=null;this.next();}
 event(event){if(['TREE_HIT','HOUSE_HIT','TRAFFIC_HIT','HARD_LANDING','ROLLOVER_IMPACT','BEER_USE'].includes(event.type))this.duckUntil=Date.now()/1000+MUSIC_CONFIG.duckSeconds;}
 finale(){if(this.fade||this.pool==='RUN_END')return;this.fade={start:Date.now(),generation:this.generation};}
 update(){if(this.fade){const elapsed=Date.now()-this.fade.start;if(elapsed<220){if(this.audio)this.audio.volume=MUSIC_CONFIG.volume*Math.max(0,1-elapsed/220);return;}this.fade=null;this.setPool('RUN_END',true);}if(!this.audio)return;this.audio.volume=Date.now()/1000<this.duckUntil?MUSIC_CONFIG.duckVolume:MUSIC_CONFIG.volume;if(this.suspended||!this.engine.enabled||globalThis.document?.hidden){if(!this.audio.paused)this.audio.pause();}else if(this.unlocked&&this.audio.paused&&this.current&&!this.retry)this.play();}
}
