import {boxContact,resolveBox} from './colliders.js?v=021';
import {rotate} from './physics.js?v=021';
export const PROP_CONFIG={maxDebris:80,lifetime:2.4,loss:{fence:.065,sign:.045},breakSpeed:.6,village:{gate:{width:.22,depth:2.4,height:1.4,loss:.10,speed:2},pole:{width:.25,depth:.25,height:5.4,loss:.085,speed:3},well:{width:1.4,depth:1.4,height:2.5,loss:.17,speed:4},busStop:{width:3.7,depth:1.8,height:2.3,loss:.22,speed:5},shed:{width:3.3,depth:4.1,height:2.5,loss:.28,speed:6},canopy:{width:3.2,depth:3.4,height:2.7,loss:.15,speed:4}}};
export class PropCollisions{
 constructor(world,feedback){this.world=world;this.feedback=feedback;this.signature='';this.grid=new Map();this.debris=Array.from({length:PROP_CONFIG.maxDebris},()=>({active:false,p:[0,0,0],v:[0,0,0],size:[.1,.8,.08],angle:0,spin:0,age:0,kind:'wood'}));this.time=0;this.rng=(world.seed^777)>>>0;this.lastHit='—';}
 random(){this.rng=(Math.imul(this.rng,1664525)+1013904223)>>>0;return this.rng/4294967296;}
 rebuild(){this.grid.clear();for(const section of this.world.sections)for(const prop of [...section.decorations,...(section.visualDecor||[])])if((['fence','sign','house','hay','parked'].includes(prop.kind)||PROP_CONFIG.village[prop.kind])&&!prop.broken){if(PROP_CONFIG.village[prop.kind])Object.assign(prop,{...PROP_CONFIG.village[prop.kind],...prop});const key=Math.floor(prop.x/8)+','+Math.floor(prop.z/8);if(!this.grid.has(key))this.grid.set(key,[]);this.grid.get(key).push({prop,section});}this.signature=this.world.nextId+':'+this.world.revision;}
 tick(dt,body){this.time+=dt;for(const d of this.debris)if(d.active){d.age+=dt;if(d.age>=PROP_CONFIG.lifetime){d.active=false;continue;}d.v[1]-=9.81*dt;for(let i=0;i<3;i++)d.p[i]+=d.v[i]*dt;d.angle+=d.spin*dt;if(d.p[1]<d.floor){d.p[1]=d.floor;d.v[1]=Math.abs(d.v[1])*.15;d.v[0]*=.9;d.v[2]*=.9;}}
 if(this.signature!==this.world.nextId+':'+this.world.revision)this.rebuild();const gx=Math.floor(body.p[0]/8),gz=Math.floor(body.p[2]/8);for(let x=gx-2;x<=gx+2;x++)for(let z=gz-2;z<=gz+2;z++)for(const item of this.grid.get(x+','+z)||[])this.collide(item,body);}
 collide({prop,section},body){if(prop.broken)return;if(PROP_CONFIG.village[prop.kind])return this.collideVillage(prop,section,body);if(['house','hay','parked'].includes(prop.kind)){const hit=resolveBox(body,prop);if(hit&&hit.closing>1&&this.time-(prop.lastHitTime??-10)>.20){prop.lastHitTime=this.time;this.lastHit=prop.kind;this.feedback.emit('propHit',{sourceId:prop.hitKey??=('prop:'+section.id+':'+prop.x+':'+prop.z),propType:prop.kind,impulse:hit.impulse,position:[prop.x,prop.y,prop.z]});}return;}if(prop.broken||body.p[1]>prop.y+2.7||body.p[1]<prop.y-.4)return;const forward=rotate(body.q,[0,0,1]),yaw=Math.atan2(forward[0],forward[2]),a=yaw-prop.rotation,c=Math.cos(prop.rotation),s=Math.sin(prop.rotation),dx=body.p[0]-prop.x,dz=body.p[2]-prop.z,lx=dx*c-dz*s,lz=dx*s+dz*c,hx=.87*Math.abs(Math.cos(a))+1.9*Math.abs(Math.sin(a)),hz=.87*Math.abs(Math.sin(a))+1.9*Math.abs(Math.cos(a)),px=prop.kind==='fence'?.10:.20,pz=prop.kind==='fence'?prop.width/2:.20;if(Math.abs(lx)>hx+px||Math.abs(lz)>hz+pz)return;
 const speed=Math.hypot(body.v[0],body.v[2]);if(speed<PROP_CONFIG.breakSpeed)return;prop.broken=true;section.decorationRevision++;const loss=PROP_CONFIG.loss[prop.kind],impulse=speed*body.c.mass*loss;body.v[0]*=1-loss;body.v[2]*=1-loss;this.lastHit=prop.kind;this.feedback.emit(prop.kind==='fence'?'fenceBreak':'signHit',{sourceId:prop.hitKey??=('prop:'+section.id+':'+prop.x+':'+prop.z),impulse,position:[prop.x,prop.y,prop.z],name:prop.text||''});
 const count=prop.kind==='fence'?7:3;for(let i=0;i<count;i++){const d=this.debris.find(d=>!d.active);if(!d)break;d.active=true;d.age=0;d.kind=prop.kind==='sign'&&i===0?'sign':'wood';d.text=prop.text||'';d.floor=prop.y+.05;d.p=[prop.x+(this.random()-.5),prop.y+.4+this.random(),prop.z+(this.random()-.5)];d.v=[body.v[0]*.16+(this.random()-.5)*5,2+this.random()*3,body.v[2]*.16+(this.random()-.5)*5];d.size=d.kind==='sign'?[prop.width,prop.height,.08]:[.10,.55+this.random()*.8,.06];d.angle=this.random()*6.28;d.spin=(this.random()-.5)*8;}}
 collideVillage(prop,section,body){if(prop.broken)return;const spec=PROP_CONFIG.village[prop.kind],contact=boxContact(body,prop);if(!contact)return;const closing=Math.max(0,-(body.v[0]*contact.normal[0]+body.v[2]*contact.normal[1]));if(closing<spec.speed){const hit=resolveBox(body,prop);if(hit&&hit.closing>1&&this.time-(prop.lastHitTime??-10)>.35){prop.lastHitTime=this.time;this.feedback.emit('villagePropHit',{sourceId:'vprop:'+section.id+':'+prop.kind+':'+prop.x,propType:prop.kind,impulse:hit.impulse,position:[prop.x,prop.y,prop.z]});}return;}const impulse=closing*body.c.mass*spec.loss;body.v[0]+=contact.normal[0]*impulse/body.c.mass;body.v[2]+=contact.normal[1]*impulse/body.c.mass;prop.broken=true;section.decorationRevision++;this.lastHit=prop.kind;this.feedback.emit('villagePropBreak',{sourceId:'vprop:'+section.id+':'+prop.kind+':'+prop.x,propType:prop.kind,impulse,position:[prop.x,prop.y,prop.z]});const count=prop.kind==='busStop'||prop.kind==='shed'?6:prop.kind==='pole'?3:4;for(let i=0;i<count;i++){const d=this.debris.find(d=>!d.active);if(!d)break;const metal=prop.kind==='gate'||prop.kind==='busStop'||prop.kind==='canopy';Object.assign(d,{active:true,age:0,kind:metal?'metal':'wood',floor:prop.y+.05,p:[prop.x+(this.random()-.5)*prop.width,prop.y+.5+this.random()*1.5,prop.z+(this.random()-.5)*prop.depth],v:[body.v[0]*.18+(this.random()-.5)*5,2+this.random()*4,body.v[2]*.18+(this.random()-.5)*5],size:prop.kind==='pole'?[.16,1.5,.16]:[.14,.5+this.random(),.7+this.random()],angle:this.random()*6.28,spin:(this.random()-.5)*9});}}
 shift(dx,dz){for(const d of this.debris)if(d.active){d.p[0]-=dx;d.p[2]-=dz;}}
 clear(){this.debris.forEach(d=>d.active=false);this.signature='';this.lastHit='—';}
}
