import {SpatialGrid} from './performance.js?v=028';
import {boxContact,resolveBox} from './colliders.js?v=028';
// Deterministic, bounded and collision-free tape; spectators alone have cheap box contacts.
export const RACE_DECOR_CONFIG={maxGroups:24,groupSize:[3,5],spectatorLife:2.6,drawDistance:150};
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
export class RaceDecor{
 constructor(world,feedback){this.world=world;this.feedback=feedback;this.clear();}
 clear(){this.spectators=[];this.tapes=[];this.time=0;this.grid=new SpatialGrid();}
 build(){this.clear();for(const section of this.world.sections)section.visualDecor=(section.visualDecor||[]).filter(d=>!d.raceOnly);let seed=this.world.seed^0x22c0ffee;const r=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};let groups=0;for(let s=140;s<(this.world.raceFinishS||this.world.circuitLength)-40;s+=32){const p=this.world.atDistance(s),a=this.world.atDistance(s-12),b=this.world.atDistance(s+12),bend=wrap(b.yaw-a.yaw),curve=Math.abs(bend)>.025||['FAST_CURVE','FAST_S_CURVE','TECH_S_CURVE','CHICANE','HAIRPIN','APEX_TURN'].includes(p.section.type),outer=bend>0?-1:1,village=p.section.biomeProfile.type==='VILLAGE';
 if((s<260||s>(this.world.raceFinishS||this.world.circuitLength)-130)||(village?r()<.20:curve?r()<.95:r()<.35)){const sides=s<260||s>(this.world.raceFinishS||this.world.circuitLength)-130||curve&&r()<.42?[-1,1]:[outer];for(const side of sides){const points=[];for(let d=-16;d<=16;d+=8){const q=this.world.atDistance(s+d),lateral=side*(q.width/2+1.05);const x=q.x+Math.cos(q.yaw)*lateral,z=q.z-Math.sin(q.yaw)*lateral;points.push({x,z,y:this.world.height(x,z)});}if(points.length>=2)this.tapes.push({s,side,points});}}
 const finishCrowd=s>(this.world.raceFinishS||this.world.circuitLength)-100;if(groups>=RACE_DECOR_CONFIG.maxGroups-(s<(this.world.raceFinishS||this.world.circuitLength)-100?1:0)||(!finishCrowd&&((!curve&&!village)||r()>(village?.55:.78)*Math.min(1,2400/(this.world.raceFinishS||this.world.circuitLength))))||p.section.crestSafe)continue;const members=[],count=3+Math.floor(r()*3);for(let i=0;i<count;i++){const q=this.world.atDistance(s+(i-(count-1)/2)*1.25),lateral=outer*(q.width/2+1.8+r()*.6),x=q.x+Math.cos(q.yaw)*lateral,z=q.z-Math.sin(q.yaw)*lateral;
 // Keep every spectator outside the driving corridor and clear of houses/props.
 const blocked=this.world.sections.some(section=>[...section.decorations,...(section.visualDecor||[])].some(d=>!d.broken&&['house','shed','fence','well','busStop','gate','parked','tree'].includes(d.kind)&&Math.hypot(x-d.x,z-d.z)<(d.kind==='tree'?(d.radius||.3)+.9:Math.max(d.width||2,d.depth||2)/2+1.1)));if(blocked)continue;
 members.push({key:'spectator:'+groups+':'+i,type:'FARMER',active:true,s,x,z,y:this.world.height(x,z),rotation:q.yaw+(outer>0?-Math.PI/2:Math.PI/2),phase:r()*6.28,scale:.90+r()*.18,color:[.36+r()*.16,.40+r()*.17,.29+r()*.20],width:.65,depth:.7,height:1.75,hit:false,running:false,age:0});}if(members.length>=3){this.spectators.push(...members);groups++;}}
 this.grid.rebuild(this.spectators);for(const tape of this.tapes){const section=this.world.atDistance(tape.s).section;for(let i=0;i<tape.points.length;i++){const a=tape.points[i];section.visualDecor.push({kind:'raceStake',raceOnly:true,...a});if(i===0)continue;const b=tape.points[i-1],length=Math.hypot(a.x-b.x,a.z-b.z),rotation=Math.atan2(a.x-b.x,a.z-b.z);for(let k=0;k<4;k++){const u=(k+.5)/4;section.visualDecor.push({kind:'raceStripe',raceOnly:true,x:b.x+(a.x-b.x)*u,y:b.y+(a.y-b.y)*u,z:b.z+(a.z-b.z)*u,rotation,length:length/4+.04,red:k%2===0});}}section.decorationRevision++;}
 }
 tick(dt,body){this.time+=dt;for(const a of this.spectators){if(!a.active)continue;a.age+=dt;if(a.hit){a.hitAge+=dt;if(a.hitAge>RACE_DECOR_CONFIG.spectatorLife){a.active=false;continue;}a.velocity[1]-=9.81*dt;for(let i=0;i<3;i++)a[['x','y','z'][i]]+=a.velocity[i]*dt;a.tumble+=dt*5;const floor=this.world.height(a.x,a.z)+.2;if(a.y<floor){a.y=floor;a.velocity[1]=Math.abs(a.velocity[1])*.15;a.velocity[0]*=Math.exp(-dt*3);a.velocity[2]*=Math.exp(-dt*3);}continue;}}for(const a of this.nearby(body))this.contact(body,a,this.feedback);}
 nearby(body){return this.grid.nearby(body.p[0],body.p[2],12);}
 contact(body,a,feedback=this.feedback){if(a.hit||!a.active||Math.hypot(a.x-body.p[0],a.z-body.p[2])>3||!boxContact(body,a))return;const hit=resolveBox(body,a,[0,0],.32);if(!hit||hit.closing<.8)return;feedback.emit('farmerHit',{sourceId:a.key,impulse:hit.impulse,position:[a.x,a.y,a.z]});feedback.burst([a.x,a.y+.8,a.z],body.v,24,'dust');feedback.burst([a.x,a.y+1.2,a.z],body.v,22,'straw');feedback.burst([a.x,a.y+.7,a.z],body.v,32,'antifreeze');Object.assign(a,{hit:true,hitAge:0,tumble:0,velocity:[body.v[0]*.35,4+Math.min(3,hit.closing*.1),body.v[2]*.35]});}
}
