import {GameplayClock,SpatialGrid,aiPhysicsRate,controllerInterval} from './performance.js?v=028';
import {OffroadVehicle,CAR_CONFIG,rotate} from './physics.js?v=028';
import {RunState} from './run-state.js?v=028';
import {VehicleFeedback} from './feedback.js?v=028';
import {TreeCollisions} from './trees.js?v=028';
import {PropCollisions} from './props.js?v=028';
import {Pickups} from './pickups.js?v=028';
import {CIRCUIT_CONFIG} from './circuit-world.js?v=028';
import {boxContact} from './colliders.js?v=028';
export const GAME_MODE={ENDLESS:'ENDLESS',OFFROAD:'OFFROAD',CIRCUIT:'CIRCUIT',SPRINT_5:'SPRINT_5',SPRINT_10:'SPRINT_10'};
export const isRaceMode=mode=>mode===GAME_MODE.CIRCUIT||mode===GAME_MODE.SPRINT_5||mode===GAME_MODE.SPRINT_10;
export const RACE_CONFIG={laps:3,racers:10,countdown:10,cupKey:'niva3d.cupStats.v1',aiSpeeds:[29,32,30,33,28.8,32.5,30.5,31,29.2],colors:[[.90,.88,.80],[.70,.18,.13],[.18,.34,.62],[.24,.47,.27],[.70,.61,.43],[.80,.80,.71],[.58,.22,.18],[.22,.41,.61],[.38,.52,.34]]};
export const AI_NAMES='Кузьмич|Петрович|Михалыч|Палыч|Саныч|Иваныч|Семёныч|Егорыч|Дядя Гена|Дядя Витя|Батя|Просто Серёга|Тихий Лёха|Толян|Валерыч|Геннадий|Ветеран|Призрачный Гонщик|Колхозный Стиг|Сельский Сенна|Шумахер из Катышки|Король Обочины|Грязевой Барон|Дрифт-Дед|Пивной Рейсер|Геннадий Турбо|Ночной Хмырь|Бешеный Петрович|Безумный Кузьмич|Дед на Полном|Последний Самоблок|Тракторист 3000|Неубиваемый|Чёрный Бампер|Синий Дым|Правый Привод|Левый Привод|Три Колеса|Живой Кардан|Злой Карбюратор|Дед Блокировка|Грязный Санёк|Обочинный Волк|Лесной Шумахер|Катышкинский Демон|Великий Петрович|Последний Колхозник|Ржавый Барон|Без Тормозов|Батя на Ниве'.split('|');
export function chooseNames(seed){const pool=AI_NAMES.slice();let state=seed>>>0;for(let i=pool.length-1;i>0;i--){state=(Math.imul(state,1664525)+1013904223)>>>0;const j=Math.floor(state/4294967296*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}return pool.slice(0,9);}
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a)),clamp=(a,l,h)=>Math.max(l,Math.min(h,a));
export function raceInput(body,world,personality=1,other=[],controllerDt=1/60){const p=world.locate(body.p[0],body.p[2]),speed=Math.hypot(body.v[0],body.v[2]),look=clamp(9+speed*.72,10,28),target=world.atDistance(p.s+look),front=rotate(body.q,[0,0,1]),yaw=Math.atan2(front[0],front[2]);let desired=Math.atan2(target.x-body.p[0],target.z-body.p[2]),curve=0;
 for(const distance of [12,25,40,personality<1.2?60:personality>1.28?48:55]){const next=world.atDistance(p.s+distance);curve=Math.max(curve,Math.abs(wrap(next.yaw-p.yaw))/distance);}
 let targetSpeed=Math.min(29.17,Math.sqrt((5.6+.6*Math.max(0,personality-1))/Math.max(.004,curve)));if(['HAIRPIN','APEX_TURN'].includes(target.section.type))targetSpeed=Math.min(targetSpeed,19);
 const hazard=target.section.localFeatures.find(o=>Math.abs((o.u-target.u)*target.section.length)<14&&['ROCK','LOG_LARGE','LOG_MEDIUM','DITCH'].includes(o.kind));if(hazard){const lane=hazard.lateral>0?-1.3:1.3;desired=Math.atan2(target.x+Math.cos(target.yaw)*lane-body.p[0],target.z-Math.sin(target.yaw)*lane-body.p[2]);targetSpeed=Math.min(targetSpeed,23);}
 let passing=0;for(const n of other){if(n===body)continue;const dx=n.p[0]-body.p[0],dz=n.p[2]-body.p[2],ahead=dx*Math.sin(yaw)+dz*Math.cos(yaw),side=dx*Math.cos(yaw)-dz*Math.sin(yaw);if(ahead>0&&ahead<18&&Math.abs(side)<2.0){passing=side>=0?-1.6:1.6;const direction=rotate(n.q,[0,0,1]),parallel=direction[0]*front[0]+direction[2]*front[2]>.55;if(ahead<5&&parallel&&Math.hypot(n.v[0],n.v[2])>1)targetSpeed=Math.min(targetSpeed,Math.max(7,Math.hypot(n.v[0],n.v[2])));}}
 if(passing&&!hazard)desired=Math.atan2(target.x+Math.cos(target.yaw)*passing-body.p[0],target.z-Math.sin(target.yaw)*passing-body.p[2]);let steer=clamp(-wrap(desired-yaw)*2.2+body.omega[1]*.12,-1,1);
 if(Math.abs(p.lateral)>p.width/2)targetSpeed=Math.min(targetSpeed,9);if(body.state.detachedWheel)targetSpeed=Math.min(targetSpeed,10);
 const steep=!!(p.section.hill&&Math.abs(p.section.hill.angle)>30||target.section.hill&&Math.abs(target.section.hill.angle)>30),mud=body.wheels.some(w=>!w.detached&&(w.mudDepth||0)>.65&&speed<3),rangeGoal=steep||mud?'L':'H';
 if(body.state.transferRange!==rangeGoal){body.state.pendingRange=rangeGoal;if(rangeGoal==='L'){body.state.pendingCenter=true;body.state.pendingRear=true;}return{drive:speed>1.1?-1:0,steer:clamp(steer,-1,1),handbrake:false,targetSpeed:0};}
 body.aiStuckTime=speed<1.5?(body.aiStuckTime||0)+controllerDt:0;
 if(body.aiStuckTime>3&&rotate(body.q,[0,1,0])[1]>.1){const phase=(body.aiStuckTime-3)%6;return{drive:phase<2.4?-1:1,steer:phase<2.4?-.65:.65,handbrake:false,targetSpeed:9};}
 const kmh=speed*3.6,governor=clamp((106-kmh)/6,0,1),bend=curve>.014?.45:curve>.0065?.78:1;
 let drive=speed>targetSpeed+2?-clamp((speed-targetSpeed)*.22,.04,1):Math.min(governor,bend,clamp((targetSpeed-speed)*.3+.65,.1,1));if(kmh>108)drive=-.08;
 return{drive,steer:clamp(steer,-1,1),handbrake:false,targetSpeed};}

export class RaceProgress{
 constructor(world){this.world=world;this.sprint=!!world.finiteRace;this.totalLaps=this.sprint?1:3;this.gates=[];const end=this.sprint?world.raceFinishS:world.circuitLength-100,spacing=this.sprint?500:CIRCUIT_CONFIG.checkpointSpacing;for(let s=this.sprint?CIRCUIT_CONFIG.startLine+spacing:180;s<end;s+=spacing)this.gates.push(world.atDistance(s));this.gates.push(world.atDistance(this.sprint?world.raceFinishS:CIRCUIT_CONFIG.startLine));}
 reset(racer){Object.assign(racer,{nextGate:0,laps:0,lastLap:null,bestLap:null,lapStart:0,finishTime:null,dnf:false,acceptedS:CIRCUIT_CONFIG.gridFront-4*CIRCUIT_CONFIG.gridGap,previousP:racer.body.p.slice(),safeS:CIRCUIT_CONFIG.gridFront-4*CIRCUIT_CONFIG.gridGap,missedGate:null});}
 tick(racer,time){if(racer.dnf||racer.finishTime!==null)return;const gate=this.gates[racer.nextGate],old=racer.previousP,p=racer.body.p;const signed=q=>(q[0]-gate.x)*Math.sin(gate.yaw)+(q[2]-gate.z)*Math.cos(gate.yaw),before=signed(old),after=signed(p);if(before<=0&&after>0){const u=-before/(after-before),x=old[0]+(p[0]-old[0])*u,z=old[2]+(p[2]-old[2])*u,lateral=(x-gate.x)*Math.cos(gate.yaw)-(z-gate.z)*Math.sin(gate.yaw);if(Math.abs(lateral)<gate.width/2+3.2&&Math.abs(p[1]-gate.y)<3.5){racer.missedGate=null;racer.acceptedS=racer.safeS=gate.s;racer.nextGate++;if(racer.nextGate===this.gates.length){racer.laps++;racer.lastLap=time-racer.lapStart;racer.bestLap=Math.min(racer.bestLap??Infinity,racer.lastLap);racer.lapStart=time;racer.nextGate=0;racer.acceptedS=racer.safeS=CIRCUIT_CONFIG.startLine;if(racer.laps===this.totalLaps)racer.finishTime=time;}}else if(Math.abs(lateral)<25)racer.missedGate=racer.nextGate;}for(let i=0;i<3;i++)racer.previousP[i]=p[i];}
 distance(racer){return clamp(this.world.locate(racer.body.p[0],racer.body.p[2]).s-CIRCUIT_CONFIG.startLine,0,this.world.raceLength||this.world.circuitLength);}
 score(racer){if(racer.finishTime!==null)return this.totalLaps*1e6+1e5-racer.finishTime;if(racer.dnf)return -1e6+racer.laps*1000+racer.nextGate;const gate=this.gates[racer.nextGate],previous=racer.nextGate?this.gates[racer.nextGate-1]:this.world.atDistance(CIRCUIT_CONFIG.startLine),p=this.world.locate(racer.body.p[0],racer.body.p[2]),mod=(a,b)=>(a%b+b)%b,L=this.world.circuitLength;if(racer.laps===0&&racer.nextGate===0&&p.s<CIRCUIT_CONFIG.startLine)return p.s-CIRCUIT_CONFIG.startLine-(racer.gridPosition||0)*.001;const length=this.sprint?gate.s-previous.s:mod(gate.s-previous.s,L),delta=this.sprint?p.s-previous.s:mod(p.s-previous.s,L);return racer.laps*1e6+racer.nextGate*1000+clamp(delta/Math.max(1,length),0,.99)*1000;}

}
export class VillageCup{
 constructor(world,player,run,feedback,storage){Object.assign(this,{world,player,run,feedback,storage});this.stats={wins:0,races:0};try{Object.assign(this.stats,JSON.parse(storage?.getItem(RACE_CONFIG.cupKey)||'{}'));}catch{}this.active=false;this.ai=[];}
 start(){this.clear();this.active=true;this.finished=false;this.countdown=RACE_CONFIG.countdown;this.time=0;this.result=null;this.lastMissedGate=null;this.solo=false;this.progress=new RaceProgress(this.world);this.racers=[{id:0,name:'ТЫ',body:this.player,run:this.run,gridPosition:10}];this.progress.reset(this.racers[0]);
 const names=chooseNames(this.world.seed);this.hornSeed=(this.world.seed^0x123abcdef)>>>0;this.nextHorn=0;const emptyTraffic={active:[]};this.actorGrid=new SpatialGrid();this.actorItems=[];this.otherBodies=[];this.progressElapsed=0;for(let i=0;i<RACE_CONFIG.racers-1;i++){const fx=new VehicleFeedback(this.world.seed+i+1),r=new RunState(fx,null);fx.particles.length=90;r.mode=this.run.mode;r.randomFailures=false;r.isAI=true;const trees=new TreeCollisions(this.world,fx),props=new PropCollisions(this.world,fx),pickups=new Pickups(this.world,r,emptyTraffic),gameplay=new GameplayClock(),tickGameplay=(elapsed,body)=>{r.tick(elapsed,body);pickups.tick(elapsed,body);},body=new OffroadVehicle({height:(x,z)=>this.world.height(x,z),normal:(x,z)=>this.world.normal(x,z),surface:(x,z)=>this.world.surface(x,z),grip:(x,z)=>this.world.surface(x,z).longitudinalGrip,afterStep:(dt,b)=>{trees.tick(dt,b);props.tick(dt,b);fx.physicsTick(dt,b);gameplay.step(dt,b,tickGameplay);}},{...CAR_CONFIG,mapLimit:Infinity}),s=CIRCUIT_CONFIG.gridFront-Math.floor(i/2)*CIRCUIT_CONFIG.gridGap,p=this.world.atDistance(s),side=i%2?1:-1;body.reset(p.x+Math.cos(p.yaw)*side*1.6,p.z-Math.sin(p.yaw)*side*1.6,p.yaw);r.body=body;r.mechanical.bind(body,this.world.seed+i*19);r.applyEngine(body);const racer={id:i+1,gridPosition:i+1,name:names[i],body,run:r,feedback:fx,trees,props,gameplay,physicsHz:180,personality:RACE_CONFIG.aiSpeeds[i]/25,color:RACE_CONFIG.colors[i],stuck:0,controllerTime:0};this.progress.reset(racer);this.racers.push(racer);this.ai.push(racer);}
 const p=this.world.atDistance(CIRCUIT_CONFIG.gridFront-4*CIRCUIT_CONFIG.gridGap);this.player.reset(p.x+Math.cos(p.yaw)*1.6,p.z-Math.sin(p.yaw)*1.6,p.yaw);this.run.applyEngine(this.player);this.racers[0].previousP=this.player.p.slice();for(const racer of this.racers){this.settle(racer.body);racer.previousP=racer.body.p.slice();racer.body.routeS=this.world.locate(racer.body.p[0],racer.body.p[2]).s;}this.run.distance=0;this.run.fuel=100;this.run.hp=100;
 }
 settle(body){const callback=body.terrain.afterStep;body.terrain.afterStep=()=>{};try{for(let i=0;i<8;i++)body.advance(.05,{drive:0,steer:0,handbrake:true});}finally{body.terrain.afterStep=callback;}body.v=[0,0,0];body.omega=[0,0,0];body.wheels.forEach(w=>w.omega=0);body.state.stepDistance=0;}
 startSolo(){this.clear();this.solo=true;this.active=true;this.finished=false;this.countdown=10;this.time=0;this.racers=[{id:0,body:this.player,run:this.run}];}
 clear(){this.solo=false;this.rescueHold=0;for(const ai of this.ai||[])ai.run.unsubscribe?.();this.ai=[];this.racers=[];this.active=false;}
 before(dt,drive=0){if(!this.active||this.finished)return false;if(this.countdown>0){this.countdown=Math.max(0,this.countdown-dt);for(const racer of this.racers){revOnGrid(racer.body,dt,racer.id?.35+.25*(1+Math.sin((10-this.countdown)*2+racer.id))*.5:Math.max(0,drive));racer.run.tick(dt,racer.body);if(this.countdown===0)racer.body.state.startLock=false;}return false;}for(const r of this.racers)r.body.state.startLock=false;this.time+=dt;return true;}
 update(dt,animals,farmers){if(!this.active||this.finished||this.countdown>0)return;const others=this.otherBodies;others.length=0;for(const a of this.racers)if(!a.dnf)others.push(a.body);const items=this.actorItems;items.length=0;for(const a of animals?.active||[])items.push(a);for(const a of farmers?.active||[])items.push(a);this.actorGrid.rebuild(items);for(const r of this.ai){if(r.dnf)continue;if(r.finishTime!==null)continue;if(r.run.ended){this.retire(r);continue;}const distance=Math.hypot(r.body.p[0]-this.player.p[0],r.body.p[2]-this.player.p[2]);r.physicsHz=aiPhysicsRate(distance,r.physicsHz);r.body.setPhysicsRate(r.physicsHz);r.controllerTime-=dt;if(r.controllerTime<=0){const stamp=this.profiler?.now();r.input=raceInput(r.body,this.world,r.personality,others,controllerInterval(distance));const grounded=r.body.wheels.some(w=>w.contact);if(grounded&&r.wasAirborne)r.stabilizeUntil=this.time+.45;r.wasAirborne=!grounded;if(this.time<(r.stabilizeUntil||0)){r.input.steer=clamp(r.input.steer,-.45,.45);const f=rotate(r.body.q,[0,0,1]),p=this.world.locate(r.body.p[0],r.body.p[2]);if(f[0]*Math.sin(p.yaw)+f[2]*Math.cos(p.yaw)<.6)r.input.drive=Math.min(.3,r.input.drive);}r.controllerTime=controllerInterval(distance);if(this.profiler)this.profiler.record("aiController",stamp);}const stamp=this.profiler?.now();r.body.advance(dt,r.input);if(this.profiler)this.profiler.record("aiPhysics",stamp);this.updateFlash(r,others);if(Math.hypot(r.body.p[0]-this.player.p[0],r.body.p[2]-this.player.p[2])<120)r.feedback.update(dt,r.body);else r.feedback.particles.forEach(p=>p.active=false);this.actorContacts(r,animals,farmers);for(const a of this.decor?.nearby(r.body)||[])this.decor.contact(r.body,a,r.feedback);}
 const collisionStamp=this.profiler?.now();this.carContacts();if(this.profiler)this.profiler.record("collisions",collisionStamp);this.progressElapsed+=dt;const progressDue=this.progressElapsed>=1/30;if(progressDue)this.progressElapsed=0;for(const r of this.racers){if(progressDue)this.progress.tick(r,this.time);if(r.run.ended)this.retire(r);}
 const p=this.racers[0];if(p.missedGate!==null&&p.missedGate!==this.lastMissedGate){this.run.notify('ЧЕКПОИНТ ПРОПУЩЕН',3);this.lastMissedGate=p.missedGate;}if(p.missedGate===null)this.lastMissedGate=null;if(p.dnf||p.finishTime!==null)this.finish(p.dnf);
 }
 updateFlash(r,others){r.flashCooldown=Math.max(0,(r.flashCooldown||0));if(this.time<(r.flashUntil||0)||this.time<(r.nextFlash||0))return;const f=rotate(r.body.q,[0,0,1]),speed=Math.hypot(r.body.v[0],r.body.v[2]);if(others.some(b=>{if(b===r.body)return false;const dx=b.p[0]-r.body.p[0],dz=b.p[2]-r.body.p[2],ahead=dx*f[0]+dz*f[2],side=dx*f[2]-dz*f[0];return ahead>5&&ahead<30&&Math.abs(side)<2.5&&speed>Math.hypot(b.v[0],b.v[2])+.8;})){r.flashUntil=this.time+.7;r.nextFlash=this.time+8;}}
 actorContacts(r,animals,farmers){for(const a of this.actorGrid.nearby(r.body.p[0],r.body.p[2],12)){if(a.type==='CHICKEN'||a.hit||!a.active)continue;if(!boxContact(r.body,a))continue;const speed=Math.hypot(r.body.v[0],r.body.v[2]);r.body.v[0]*=.65;r.body.v[2]*=.65;r.run.hit(a.type==='COW'?'COW_HIT':'FARMER_HIT',{sourceId:'actor:'+a.key,impulse:r.body.c.mass*speed*.6,position:[a.x,a.y,a.z]});if(a.type==='COW'){animals.fragments(a,r.body);this.feedback.burst([a.x,a.y+1,a.z],r.body.v,24,'dust');a.active=false;}else{Object.assign(a,{hit:true,running:false,hitAge:0,tumble:0,velocity:[r.body.v[0]*.35,4,r.body.v[2]*.35]});this.feedback.burst([a.x,a.y+1,a.z],r.body.v,12,'cloth');}}}
 carContacts(){for(let i=0;i<this.racers.length;i++)for(let j=i+1;j<this.racers.length;j++){const a=this.racers[i],b=this.racers[j];if(((a.dnf&&this.time-a.dnfAt>3)||(b.dnf&&this.time-b.dnfAt>3)))continue;if(Math.hypot(a.body.p[0]-b.body.p[0],a.body.p[2]-b.body.p[2])>5)continue;const front=rotate(b.body.q,[0,0,1]),obstacle={x:b.body.p[0],z:b.body.p[2],y:b.body.p[1]-.8,rotation:Math.atan2(front[0],front[2]),width:1.74,depth:3.8,height:1.9},contact=boxContact(a.body,obstacle);if(!contact)continue;const [nx,nz]=contact.normal;for(const [r,sign] of [[a,1],[b,-1]]){r.body.p[0]+=sign*nx*(contact.depth+.001)*.5;r.body.p[2]+=sign*nz*(contact.depth+.001)*.5;}const closing=Math.max(0,-((a.body.v[0]-b.body.v[0])*nx+(a.body.v[2]-b.body.v[2])*nz)),impulse=closing*a.body.c.mass*.52;if(closing>.1){if(closing>4){a.stabilizeUntil=b.stabilizeUntil=this.time+.5;}a.body.v[0]+=nx*impulse/a.body.c.mass;a.body.v[2]+=nz*impulse/a.body.c.mass;b.body.v[0]-=nx*impulse/b.body.c.mass;b.body.v[2]-=nz*impulse/b.body.c.mass;for(const r of [a,b])r.run.hit('TRAFFIC_HIT',{sourceId:'racer:'+i+':'+j,impulse,position:r.body.p.slice()});this.horn(a,b,closing);}}}

 retire(r){if(r.dnf)return;r.dnf=true;r.dnfAt=this.time;r.run.ended=true;r.run.applyEngine(r.body);}
 horn(a,b,closing){if(closing<1.5||this.time<this.nextHorn)return;const speaker=a.id?a:b;if(!speaker.id||this.time<(speaker.nextHorn||0))return;this.hornSeed=(Math.imul(this.hornSeed,1664525)+1013904223)>>>0;if(this.hornSeed/4294967296>Math.min(.85,.15+closing*.045))return;const distance=Math.hypot(speaker.body.p[0]-this.player.p[0],speaker.body.p[2]-this.player.p[2]);if(distance>100)return;speaker.nextHorn=this.time+7;this.nextHorn=this.time+1.5;this.feedback.emit('AI_HORN',{distance,impulse:closing*1000});}
 safePlayer(){} // Racing rescue uses only accepted gates; no arbitrary safe-road shortcut.

 position(){if(this.countdown>0)return 10;return [...this.racers].sort((a,b)=>this.progress.score(b)-this.progress.score(a)).findIndex(r=>r.id===0)+1;}
 finish(dnf=false){if(this.finished)return;this.finished=true;const r=this.racers[0];if(dnf)r.dnf=true;this.result={dnf,position:this.position(),time:this.time,bestLap:r.bestLap,mode:this.run.mode,distance:this.world.raceLength||null};this.stats.races++;if(!dnf&&this.result.position===1)this.stats.wins++;try{this.storage?.setItem(RACE_CONFIG.cupKey,JSON.stringify(this.stats));}catch{}this.run.ended=true;this.run.applyEngine(this.player);this.player.v=[0,0,0];this.player.omega=[0,0,0];this.player.state.vehicleSpeed=0;this.player.wheels.forEach(w=>w.omega=0);this.feedback.emit('CUP_END',this.result);}
}

// Start lock isolates chassis motion, not engine input. Normal on-track physics is unchanged.
export function revOnGrid(body,dt,input){const s=body.state,c=body.c,gas=s.engineRunning===false?0:clamp(input,0,1);s.startLock=true;s.throttleInput=gas;s.throttle+=(gas-s.throttle)*(1-Math.exp(-c.throttleResponse*dt));s.brake=0;s.handbrake=false;s.currentRPM+=((c.idleRPM+s.throttle*(c.redlineRPM-c.idleRPM-650))-s.currentRPM)*(1-Math.exp(-c.engineResponse*dt));s.load=s.throttle*.18;s.stepDistance=0;s.vehicleSpeed=0;body.v=[0,0,0];body.omega=[0,0,0];body.wheels.forEach(w=>w.omega=0);}
