import {OffroadVehicle,CAR_CONFIG,rotate} from './physics.js?v=021';
import {RunState} from './run-state.js?v=021';
import {VehicleFeedback} from './feedback.js?v=021';
import {TreeCollisions} from './trees.js?v=021';
import {PropCollisions} from './props.js?v=021';
import {Pickups} from './pickups.js?v=021';
import {CIRCUIT_CONFIG} from './circuit-world.js?v=021';
import {boxContact} from './colliders.js?v=021';
export const GAME_MODE={ENDLESS:'ENDLESS',CIRCUIT:'CIRCUIT'};
export const RACE_CONFIG={laps:3,racers:6,countdown:3,cupKey:'niva3d.cupStats.v1',aiSpeeds:[23,26,25,27,24],colors:[[.90,.88,.80],[.70,.18,.13],[.18,.34,.62],[.24,.47,.27],[.70,.61,.43]]};
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a)),clamp=(a,l,h)=>Math.max(l,Math.min(h,a));
export function raceInput(body,world,personality=1,other=[]){const p=world.locate(body.p[0],body.p[2]),speed=Math.hypot(body.v[0],body.v[2]),look=clamp(9+speed*.72,10,28),target=world.atDistance(p.s+look),front=rotate(body.q,[0,0,1]),yaw=Math.atan2(front[0],front[2]);let desired=Math.atan2(target.x-body.p[0],target.z-body.p[2]),curve=0;
 for(const distance of [12,28,48,70]){const next=world.atDistance(p.s+distance);curve=Math.max(curve,Math.abs(wrap(next.yaw-p.yaw))/distance);}
 let targetSpeed=Math.min(23*personality,Math.sqrt(3.4/Math.max(.004,curve)));if(['HAIRPIN','TECH_S_CURVE','CHICANE','APEX_TURN'].includes(target.section.type))targetSpeed=Math.min(targetSpeed,14);if(['LOG_CROSSING','RUTS','WASHOUT','TECHNICAL_HILL'].includes(target.section.type))targetSpeed=Math.min(targetSpeed,8);if(target.section.crestSafe)targetSpeed=Math.min(targetSpeed,17);
 const hazard=target.section.localFeatures.find(o=>Math.abs((o.u-target.u)*target.section.length)<14&&['ROCK','LOG_LARGE','LOG_MEDIUM','DITCH','PIT'].includes(o.kind));if(hazard){const lane=hazard.lateral>0?-1.3:1.3;desired=Math.atan2(target.x+Math.cos(target.yaw)*lane-body.p[0],target.z-Math.sin(target.yaw)*lane-body.p[2]);targetSpeed=Math.min(targetSpeed,12);}
 let steer=clamp(-wrap(desired-yaw)*2.2+body.omega[1]*.12,-1,1);for(const n of other){if(n===body)continue;const dx=n.p[0]-body.p[0],dz=n.p[2]-body.p[2],ahead=dx*Math.sin(yaw)+dz*Math.cos(yaw),side=dx*Math.cos(yaw)-dz*Math.sin(yaw);if(ahead>0&&ahead<12&&Math.abs(side)<2.2){targetSpeed=Math.min(targetSpeed,Math.max(4,Math.hypot(n.v[0],n.v[2])-.5));steer+=side>=0?.20:-.20;}}
 if(Math.abs(p.lateral)>p.width/2)targetSpeed=Math.min(targetSpeed,9);if(body.state.detachedWheel)targetSpeed=Math.min(targetSpeed,10);
 return{drive:speed>targetSpeed+1?-clamp((speed-targetSpeed)*.30,.05,1):clamp((targetSpeed-speed)*.20+.3,.15,1),steer:clamp(steer,-1,1),handbrake:false,targetSpeed};}
export class RaceProgress{
 constructor(world){this.world=world;this.gates=[];for(let s=100;s<world.circuitLength-60;s+=CIRCUIT_CONFIG.checkpointSpacing)this.gates.push(world.atDistance(s));this.gates.push(world.atDistance(CIRCUIT_CONFIG.startLine));}
 reset(racer){Object.assign(racer,{nextGate:0,laps:0,lastLap:null,bestLap:null,lapStart:0,finishTime:null,dnf:false,acceptedS:0,previousP:racer.body.p.slice(),safeS:20});}
 tick(racer,time){if(racer.dnf||racer.finishTime!==null)return;const gate=this.gates[racer.nextGate],old=racer.previousP,p=racer.body.p;const signed=q=>(q[0]-gate.x)*Math.sin(gate.yaw)+(q[2]-gate.z)*Math.cos(gate.yaw),before=signed(old),after=signed(p);if(before<=0&&after>0){const t=-before/(after-before),x=old[0]+(p[0]-old[0])*t,z=old[2]+(p[2]-old[2])*t,lateral=(x-gate.x)*Math.cos(gate.yaw)-(z-gate.z)*Math.sin(gate.yaw);if(Math.abs(lateral)<gate.section.width/2+1.2&&Math.abs(p[1]-gate.y)<3.5){racer.acceptedS=gate.s;racer.nextGate++;if(racer.nextGate===this.gates.length){racer.laps++;racer.lastLap=time-racer.lapStart;racer.bestLap=Math.min(racer.bestLap??Infinity,racer.lastLap);racer.lapStart=time;racer.nextGate=0;racer.acceptedS=0;if(racer.laps===RACE_CONFIG.laps)racer.finishTime=time;}}}racer.previousP=p.slice();}
 score(racer){if(racer.finishTime!==null)return RACE_CONFIG.laps*1e6+1e5-racer.finishTime;if(racer.dnf)return -1e6+racer.laps*1000+racer.nextGate;const gate=this.gates[racer.nextGate],previous=racer.nextGate?this.gates[racer.nextGate-1]:this.world.atDistance(CIRCUIT_CONFIG.startLine),p=this.world.locate(...[racer.body.p[0],racer.body.p[2]]),length=(gate.s-previous.s+this.world.circuitLength)%this.world.circuitLength,delta=(p.s-previous.s+this.world.circuitLength)%this.world.circuitLength;return racer.laps*1e6+racer.nextGate*1000+clamp(delta/Math.max(1,length),0,.99)*1000;}
}
export class VillageCup{
 constructor(world,player,run,feedback,storage){Object.assign(this,{world,player,run,feedback,storage});this.stats={wins:0,races:0};try{Object.assign(this.stats,JSON.parse(storage?.getItem(RACE_CONFIG.cupKey)||'{}'));}catch{}this.active=false;this.ai=[];}
 start(){this.clear();this.active=true;this.finished=false;this.countdown=RACE_CONFIG.countdown;this.time=0;this.result=null;this.progress=new RaceProgress(this.world);this.racers=[{id:0,name:'ТЫ',body:this.player,run:this.run}];this.progress.reset(this.racers[0]);
 const emptyTraffic={active:[]};for(let i=0;i<5;i++){const fx=new VehicleFeedback(this.world.seed+i+1),r=new RunState(fx,null);fx.particles.length=90;r.mode=GAME_MODE.CIRCUIT;r.randomFailures=false;r.isAI=true;const trees=new TreeCollisions(this.world,fx),props=new PropCollisions(this.world,fx),pickups=new Pickups(this.world,r,emptyTraffic),body=new OffroadVehicle({height:(x,z)=>this.world.height(x,z),normal:(x,z)=>this.world.normal(x,z),surface:(x,z)=>this.world.surface(x,z),grip:(x,z)=>this.world.surface(x,z).longitudinalGrip,afterStep:(dt,b)=>{trees.tick(dt,b);props.tick(dt,b);fx.physicsTick(dt,b);r.tick(dt,b);pickups.tick(dt,b);}},{...CAR_CONFIG,mapLimit:Infinity}),s=22-Math.floor((i+1)/2)*CIRCUIT_CONFIG.gridGap,p=this.world.atDistance(s),side=(i+1)%2?1:-1;body.reset(p.x+Math.cos(p.yaw)*side*1.6,p.z-Math.sin(p.yaw)*side*1.6,p.yaw);r.body=body;r.mechanical.bind(body,this.world.seed+i*19);r.applyEngine(body);const racer={id:i+1,name:['ДЕД','МИХАЛЫЧ','ПАЛЫЧ','САНЫЧ','ВАСИЛИЧ'][i],body,run:r,feedback:fx,trees,props,personality:RACE_CONFIG.aiSpeeds[i]/25,color:RACE_CONFIG.colors[i],stuck:0,controllerTime:0};this.progress.reset(racer);this.racers.push(racer);this.ai.push(racer);}
 const p=this.world.atDistance(22);this.player.reset(p.x-Math.cos(p.yaw)*1.6,p.z+Math.sin(p.yaw)*1.6,p.yaw);this.run.applyEngine(this.player);this.racers[0].previousP=this.player.p.slice();for(const racer of this.racers)this.settle(racer.body);this.run.distance=0;this.run.fuel=100;this.run.hp=100;
 }
 settle(body){const callback=body.terrain.afterStep;body.terrain.afterStep=()=>{};try{body.advance(.35,{drive:0,steer:0,handbrake:true});}finally{body.terrain.afterStep=callback;}body.v=[0,0,0];body.omega=[0,0,0];body.wheels.forEach(w=>w.omega=0);body.state.stepDistance=0;}
 clear(){for(const ai of this.ai||[])ai.run.unsubscribe?.();this.ai=[];this.racers=[];this.active=false;}
 before(dt){if(!this.active||this.finished)return false;if(this.countdown>0){this.countdown=Math.max(0,this.countdown-dt);for(const racer of this.racers){racer.body.v=[0,0,0];racer.body.omega=[0,0,0];}return false;}this.time+=dt;return true;}
 update(dt,animals,farmers){if(!this.active||this.finished||this.countdown>0)return;const others=this.racers.filter(a=>!a.dnf).map(a=>a.body);for(const r of this.ai){if(r.dnf||r.finishTime!==null)continue;if(r.run.ended){r.dnf=true;r.dnfAt=this.time;continue;}r.controllerTime-=dt;if(r.controllerTime<=0){r.input=raceInput(r.body,this.world,r.personality,others);r.controllerTime=.055;}r.body.advance(dt,r.input);if(Math.hypot(r.body.p[0]-this.player.p[0],r.body.p[2]-this.player.p[2])<120)r.feedback.update(dt,r.body);else r.feedback.particles.forEach(p=>p.active=false);r.stuck=Math.hypot(r.body.v[0],r.body.v[2])<1.5?r.stuck+dt:0;if(r.stuck>7||rotate(r.body.q,[0,1,0])[1]<-.5){this.recover(r);r.stuck=0;}this.actorContacts(r,animals,farmers);}
 this.carContacts();for(const r of this.racers){this.progress.tick(r,this.time);if(r.id&&r.nextGate>0)r.safeS=Math.max(20,r.acceptedS-8);if(r.run.ended){r.dnf=true;r.dnfAt??=this.time;}}
 const p=this.racers[0];if(p.dnf||p.finishTime!==null)this.finish(p.dnf);
 }
 actorContacts(r,animals,farmers){for(const a of (animals?.active||[]).concat(farmers?.active||[])){if(a.type==='CHICKEN'||a.hit||!a.active)continue;const obstacle={...a,width:a.width||.65,depth:a.depth||.7,height:a.height||1.75};if(!boxContact(r.body,obstacle))continue;const speed=Math.hypot(r.body.v[0],r.body.v[2]);r.body.v[0]*=.65;r.body.v[2]*=.65;r.run.hit(a.type==='COW'?'COW_HIT':'FARMER_HIT',{sourceId:'actor:'+a.key,impulse:r.body.c.mass*speed*.6,position:[a.x,a.y,a.z]});if(a.type==='COW'){animals.fragments(a,r.body);this.feedback.burst([a.x,a.y+1,a.z],r.body.v,24,'dust');a.active=false;}else{Object.assign(a,{hit:true,running:false,hitAge:0,tumble:0,velocity:[r.body.v[0]*.35,4,r.body.v[2]*.35]});this.feedback.burst([a.x,a.y+1,a.z],r.body.v,12,'cloth');}}}
 carContacts(){for(let i=0;i<this.racers.length;i++)for(let j=i+1;j<this.racers.length;j++){const a=this.racers[i],b=this.racers[j];if((a.dnf&&this.time-a.dnfAt>3)||(b.dnf&&this.time-b.dnfAt>3))continue;const front=rotate(b.body.q,[0,0,1]),obstacle={x:b.body.p[0],z:b.body.p[2],y:b.body.p[1]-.8,rotation:Math.atan2(front[0],front[2]),width:1.74,depth:3.8,height:1.9},contact=boxContact(a.body,obstacle);if(!contact)continue;const [nx,nz]=contact.normal;for(const [r,sign] of [[a,1],[b,-1]]){r.body.p[0]+=sign*nx*(contact.depth+.001)*.5;r.body.p[2]+=sign*nz*(contact.depth+.001)*.5;}const closing=Math.max(0,-((a.body.v[0]-b.body.v[0])*nx+(a.body.v[2]-b.body.v[2])*nz)),impulse=closing*a.body.c.mass*.52;if(closing>.1){a.body.v[0]+=nx*impulse/a.body.c.mass;a.body.v[2]+=nz*impulse/a.body.c.mass;b.body.v[0]-=nx*impulse/b.body.c.mass;b.body.v[2]-=nz*impulse/b.body.c.mass;for(const r of [a,b])r.run.hit('TRAFFIC_HIT',{sourceId:'racer:'+i+':'+j,impulse,position:r.body.p.slice()});}}}
 recover(r){const s=r.safeS||20,p=this.world.atDistance(s);r.body.reset(p.x,p.z,p.yaw);r.run.applyEngine(r.body);this.settle(r.body);r.previousP=r.body.p.slice();r.run.damageImmuneUntil=r.run.time+.8;}
 safePlayer(){const r=this.racers[0],p=this.world.locate(this.player.p[0],this.player.p[2]);if(this.player.wheels.filter(w=>!w.detached).every(w=>w.contact&&w.load>200)&&Math.abs(p.lateral)<p.width/2-1&&!p.section.crestSafe&&this.world.surface(p.x,p.z).mudDepth<.12){if(this.progress.score(r)%1000<990)r.safeS=p.s;}}
 position(){return [...this.racers].sort((a,b)=>this.progress.score(b)-this.progress.score(a)).findIndex(r=>r.id===0)+1;}
 finish(dnf=false){if(this.finished)return;this.finished=true;const r=this.racers[0];if(dnf)r.dnf=true;this.result={dnf,position:this.position(),time:this.time,bestLap:r.bestLap};this.stats.races++;if(!dnf&&this.result.position===1)this.stats.wins++;try{this.storage?.setItem(RACE_CONFIG.cupKey,JSON.stringify(this.stats));}catch{}this.run.ended=true;this.run.applyEngine(this.player);this.player.v=[0,0,0];this.player.omega=[0,0,0];this.player.state.vehicleSpeed=0;this.player.wheels.forEach(w=>w.omega=0);this.feedback.emit('CUP_END',this.result);}
}
