import {populateFarmers} from './farmers.js?v=026';
import {populateScenery} from './scenery.js?v=026';
import {populateAnimals} from './animals.js?v=026';
import {populatePickups} from './pickups.js?v=026';
import {BiomeStream,biomeWeights,populateVillage,populateField} from './biomes.js?v=026';
import {OBSTACLE_CONFIG,HILL_CONFIG,obstacleWeight,hillElevation} from './obstacles.js?v=026';
import {SURFACE_CONFIG,SURFACE_SETTINGS} from './surfaces.js?v=026';
export const ROAD_CONFIG={activeSections:9,behind:2,ahead:6,lengths:[40,54,68],widths:[6.4,7.2,8.0],corridor:48,treeLimit:38,step:2,maxHeadingOffset:1.10,maxCurve:.32,seed:731024};
export const SECTION_TYPES=['FAST_STRAIGHT','SHORT_STRAIGHT','FAST_CURVE','FAST_S_CURVE','JUMP','EARTH_JUMP','BLIND_CREST','DOUBLE_WAVE','FAST_HILL','BRAKING_ZONE','CHICANE','HAIRPIN','TECH_S_CURVE','APEX_TURN','RUTS','TECHNICAL_HILL','STEEP_DESCENT','ROCK_SECTION','LOG_CROSSING','BUMP_CHAIN','WASHOUT','EXIT'];
export const RALLY_CONFIG={fastLengthScale:1.2,jumpHeight:.55,jumpWidth:5.5};
export const JUMP_TYPES=['JUMP','EARTH_JUMP','BLIND_CREST','DOUBLE_WAVE'];
export const FAST_TYPES=['FAST_STRAIGHT','SHORT_STRAIGHT','FAST_CURVE','FAST_S_CURVE',...JUMP_TYPES,'FAST_HILL','EXIT'];
export const RALLY_GROUPS=[
 ['FAST_CURVE','SHORT_STRAIGHT','FAST_S_CURVE','JUMP','FAST_CURVE','BRAKING_ZONE','TECH_S_CURVE','APEX_TURN','EXIT'],
 ['FAST_S_CURVE','FAST_HILL','FAST_CURVE','EARTH_JUMP','BRAKING_ZONE','HAIRPIN','RUTS','TECHNICAL_HILL','EXIT'],
 ['FAST_CURVE','DOUBLE_WAVE','FAST_S_CURVE','SHORT_STRAIGHT','FAST_CURVE','BRAKING_ZONE','CHICANE','ROCK_SECTION','TECH_S_CURVE','EXIT'],
 ['FAST_S_CURVE','FAST_HILL','BLIND_CREST','FAST_CURVE','BRAKING_ZONE','STEEP_DESCENT','APEX_TURN','CHICANE','EXIT'],
 ['FAST_CURVE','FAST_STRAIGHT','FAST_S_CURVE','JUMP','FAST_CURVE','BRAKING_ZONE','CHICANE','TECH_S_CURVE','EXIT']
];
export const SECTION_LENGTHS={FAST_STRAIGHT:[200,260,320],SHORT_STRAIGHT:[35,45,55],FAST_CURVE:[110,140,170],FAST_S_CURVE:[140,170,200],JUMP:[100,110,120],EARTH_JUMP:[115,125,135],BLIND_CREST:[120,135,150],DOUBLE_WAVE:[125,140,155],FAST_HILL:[100,130,160],BRAKING_ZONE:[110,125,140],CHICANE:[48,56,64],HAIRPIN:[40,44,48],TECH_S_CURVE:[65,80,95],APEX_TURN:[55,65,75],RUTS:[48,60,72],TECHNICAL_HILL:[50,60,70],STEEP_DESCENT:[55,65,75],ROCK_SECTION:[45,55,65],LOG_CROSSING:[65,75,85],BUMP_CHAIN:[70,80,90],WASHOUT:[65,75,85],EXIT:[75,90,105]};
export const SPECIAL_TYPES=['EARTH_JUMP','BLIND_CREST','DOUBLE_WAVE','LOG_CROSSING','BUMP_CHAIN','WASHOUT'];
export function jumpElevation(type,d,length){const center=length*.38;if(type==='JUMP')return .55*Math.exp(-(((d-center)/5.5)**2));if(type==='EARTH_JUMP')return 1.05*Math.exp(-(((d-center)/6.0)**2));if(type==='BLIND_CREST')return 1.85*Math.exp(-(((d-center)/10.5)**2));if(type==='DOUBLE_WAVE')return .48*Math.exp(-(((d-center+5)/5.0)**2))+.84*Math.exp(-(((d-center-9)/5.3)**2));return 0;}
export function asphaltBlend(section,u){return Math.min(1,u*section.length/6,(1-u)*section.length/6);}
export function envelope(u){return smooth(u/.16)*smooth((1-u)/.16);}

const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),smooth=x=>{x=clamp(x,0,1);return x*x*(3-2*x);};
export class RoadWorld{
 constructor(seed=ROAD_CONFIG.seed,environment=null){this.environment=environment;this.reset(seed);}
 random(){this.rng=(Math.imul(this.rng,1664525)+1013904223)>>>0;return this.rng/4294967296;}
 reset(seed=this.seed){this.seed=Number(seed)>>>0;this.rng=this.seed;this.biomes=new BiomeStream(this.seed);this.sections=[];this.queue=[];this.lastGroup=-1;this.bins=new Map();this.binsDirty=true;this.nextId=0;this.distance=0;this.offset=[0,0];this.revision=(this.revision||0)+1;this.nextPickupS=120;this.nextEventS=75;this.nextComboS=220;this.nextSpecialS=700;this.lastSpecial=null;this.current=null;for(let i=0;i<ROAD_CONFIG.activeSections;i++)this.append();this.current=this.sections[0];}
 choose(){if(this.nextId<4)return ['SHORT_STRAIGHT','FAST_CURVE','FAST_S_CURVE','JUMP'][this.nextId];const progress=this.sections.at(-1)?.exitDistance||0;if(progress>=this.nextSpecialS&&(!this.queue.length||(FAST_TYPES.includes(this.queue[0])&&this.queue[0]!=='EXIT'))){let kind=SPECIAL_TYPES[Math.floor(this.random()*SPECIAL_TYPES.length)];if(kind===this.lastSpecial)kind=SPECIAL_TYPES[(SPECIAL_TYPES.indexOf(kind)+1)%SPECIAL_TYPES.length];this.lastSpecial=kind;this.queue.unshift(JUMP_TYPES.includes(kind)?'SHORT_STRAIGHT':'BRAKING_ZONE',kind,'EXIT');this.nextSpecialS=progress+OBSTACLE_CONFIG.specialSpacing[0]+this.random()*(OBSTACLE_CONFIG.specialSpacing[1]-OBSTACLE_CONFIG.specialSpacing[0]);}if(!this.queue.length){let group=Math.floor(this.random()*RALLY_GROUPS.length);if(group===this.lastGroup)group=(group+1)%RALLY_GROUPS.length;this.lastGroup=group;this.queue=RALLY_GROUPS[group].slice();}return this.queue.shift();}
 append(){const previous=this.sections.at(-1),entry=previous?{...previous.exitTransform}:{x:0,y:0,z:40,yaw:Math.PI,width:7.2},type=this.choose(),length=SECTION_LENGTHS[type][Math.floor(this.random()*3)]*(FAST_TYPES.includes(type)?RALLY_CONFIG.fastLengthScale:1),exitWidth=FAST_TYPES.includes(type)?9.0+this.random()*1.5:type==='BRAKING_ZONE'?6.5:6.4+this.random()*.8,difficulty=Math.floor(this.random()*3),template=Math.floor(this.random()*3),sign=this.random()<.5?-1:1;let turn=0;
 if(['FAST_CURVE','FAST_HILL','STEEP_DESCENT','EXIT'].includes(type))turn=sign*(.30+this.random()*.35);if(type==='BRAKING_ZONE'&&['HAIRPIN','APEX_TURN'].includes(this.queue[0]))turn=sign*.98-(entry.yaw-Math.PI);if(['HAIRPIN','APEX_TURN'].includes(type))turn=-2*(entry.yaw-Math.PI);if(Math.abs(entry.yaw-Math.PI)>.65&&type!=='HAIRPIN')turn=-(entry.yaw-Math.PI);turn=clamp(entry.yaw+turn,Math.PI-ROAD_CONFIG.maxHeadingOffset,Math.PI+ROAD_CONFIG.maxHeadingOffset)-entry.yaw;
 // Every heading remains forward in Z, including rare tight hairpin bends.
 const id=this.nextId++,startDistance=previous?previous.startDistance+previous.length:0,section={id,type,biomeProfile:this.biomes.sample(startDistance),localFeatures:[],hill:null,decorationRevision:0,mode:FAST_TYPES.includes(type)?'FAST':'TECH',length,width:entry.width,entryTransform:entry,startDistance,difficulty,template,surface:'DIRT',obstacles:[],nodes:[],decorations:[]};const step=['ROCK_SECTION','CHICANE','RUTS'].includes(type)?.5:1.5;
 if(['FAST_HILL','TECHNICAL_HILL','STEEP_DESCENT'].includes(type)){const extreme=type!=='FAST_HILL'&&this.random()<HILL_CONFIG.extremeChance,angle=type==='FAST_HILL'?HILL_CONFIG.light[difficulty]:type==='TECHNICAL_HILL'?(extreme?HILL_CONFIG.extreme[difficulty]:HILL_CONFIG.hard[difficulty]):extreme?HILL_CONFIG.extremeDescent:HILL_CONFIG.descent[difficulty],span=type==='FAST_HILL'?81:extreme?16:27,ramp=type==='FAST_HILL'?6:4;section.hill={category:extreme?'EXTREME':type==='FAST_HILL'?'LIGHT':'HARD',angle,span,ramp,start:length*(type==='FAST_HILL'?.30:.40),exitRamp:type==='FAST_HILL'?55:ramp,sign:type==='STEEP_DESCENT'?-1:type==='FAST_HILL'?sign:1};section.crestSafe=true;}
 if(JUMP_TYPES.includes(type))section.crestSafe=true;section.asphalt=!['CHICANE','RUTS','ROCK_SECTION','LOG_CROSSING','WASHOUT','TECHNICAL_HILL',...JUMP_TYPES].includes(type)&&(section.biomeProfile.type==='VILLAGE'||startDistance%1500>1125);section.surface=section.asphalt?'ASPHALT':'DIRT';this.populateEvents(section);
 if(type==='LOG_CROSSING')for(let i=0;i<5;i++)section.localFeatures.push({kind:'LOG_MEDIUM',u:.38+i*.05,lateral:0,...OBSTACLE_CONFIG.types.LOG_MEDIUM,radius:2.3});
 if(type==='BUMP_CHAIN')for(let i=0;i<4;i++)section.localFeatures.push({kind:'BUMP',u:.30+i*.12,lateral:i%2?.8:-.8,...OBSTACLE_CONFIG.types.BUMP,radius:2});
 if(type==='WASHOUT')for(let i=0;i<4;i++)section.localFeatures.push({kind:'DITCH',u:.32+i*.10,lateral:i%2?1.7:-1.7,...OBSTACLE_CONFIG.types.DITCH});
 const count=Math.ceil(length/step),samples=new Set(Array.from({length:count+1},(_,i)=>i*length/count));for(const o of section.localFeatures){for(let d=-o.longRadius*OBSTACLE_CONFIG.detailRadius;d<=o.longRadius*OBSTACLE_CONFIG.detailRadius;d+=(o.shape==='log'?OBSTACLE_CONFIG.logSamplingStep:o.surfaceType&&o.surfaceType!=='ROCK'?OBSTACLE_CONFIG.surfaceSamplingStep:OBSTACLE_CONFIG.samplingStep))samples.add(clamp(o.u*length+d,0,length));}const distances=[...samples].sort((a,b)=>a-b).filter((d,i,all)=>!i||d-all[i-1]>.005);let x=entry.x,z=entry.z,lastDistance=0;
 const heading=u=>entry.yaw+turn*smooth(u)+(['FAST_S_CURVE','TECH_S_CURVE'].includes(type)?sign*Math.min(type==='TECH_S_CURVE'?.65:.38,1.38-Math.abs(entry.yaw-Math.PI))*Math.sin(2*Math.PI*u)**3:0);
 for(const distance of distances){const u=distance/length,yaw=heading(u);if(distance){const angle=heading((distance+lastDistance)/(2*length));x+=Math.sin(angle)*(distance-lastDistance);z+=Math.cos(angle)*(distance-lastDistance);}const env=Math.sin(Math.PI*u)**2,jump=jumpElevation(type,distance,length)*envelope(u),wave=type==='FAST_STRAIGHT'&&id>=4?.10*Math.sin(distance/9)**2*envelope(u):0,y=entry.y+(section.hill?hillElevation(distance,section.hill):0)+.08*env+jump+wave;section.nodes.push({x,y,z,yaw,width:entry.width+(exitWidth-entry.width)*smooth(u),u,s:startDistance+distance});lastDistance=distance;}
 const actualCount=section.nodes.length-1;
 if(type==='CHICANE')for(const [u,lateral] of [[.32,-2.1],[.65,2.1]])section.obstacles.push({u,lateral,height:.85,radius:1.55,kind:'boulder'});
 if(type==='ROCK_SECTION')for(const [u,lateral] of [[.30,-1.1],[.46,.9],[.64,-.2]])section.obstacles.push({u,lateral,height:.43,radius:.85,kind:'rock'});
 const end=section.nodes.at(-1);section.exitTransform={x:end.x,y:end.y,z:end.z,yaw:end.yaw,width:exitWidth};section.exitDistance=startDistance+length;section.startHeight=entry.y;section.endHeight=section.exitTransform.y;section.entryDirection=entry.yaw;section.exitDirection=end.yaw;
 for(let i=0;i<Math.min(72,Math.max(32,Math.round(length/5)));i++){const node=section.nodes[1+Math.floor(this.random()*(actualCount-1))],side=i%2?-1:1,category=['SMALL','MEDIUM','LARGE'][Math.floor(this.random()*3)],radius={SMALL:.12,MEDIUM:.25,LARGE:.46}[category],offset=side*(node.width/2+(category==='LARGE'?5:2.5)+(this.random()<.12?this.random()*2:3+this.random()*24)),scale=category==='SMALL'?2.8+this.random()*1.2:category==='MEDIUM'?3.7+this.random()*1.5:5+this.random()*1.4,variant=Math.floor(this.random()*3);const weights=biomeWeights(section.biomeProfile,node.s);if(this.random()>weights.FOREST*.96+weights.FIELD*.06+weights.VILLAGE*.14)continue;section.decorations.push({kind:'tree',category,radius,broken:false,u:node.u,x:node.x+Math.cos(node.yaw)*offset,z:node.z-Math.sin(node.yaw)*offset,y:node.y+.025*Math.max(0,Math.abs(offset)-node.width/2),scale,rotation:this.random()*6.28,variant});}
 for(let i=0;i<7;i++){const node=section.nodes[Math.floor(this.random()*actualCount)],side=i%2?-1:1,offset=side*(node.width/2+1+this.random()*4);section.decorations.push({kind:i%3?'bush':'stone',x:node.x+Math.cos(node.yaw)*offset,z:node.z-Math.sin(node.yaw)*offset,y:node.y,scale:.35+this.random()*.55,rotation:this.random()*6.28});}
 populateVillage(this,section);this.sections.push(section);this.binsDirty=true;populateField(this,section);this.populateParking(section);populatePickups(this,section);populateAnimals(this,section);this.binsDirty=true;for(const existing of this.sections){const before=existing.decorations.length;existing.decorations=existing.decorations.filter(d=>{if(d.kind!=='tree'||d.broken)return true;if(existing.decorations.some(o=>['house','hay','parked'].includes(o.kind)&&Math.abs((d.x-o.x)*Math.cos(o.rotation)-(d.z-o.z)*Math.sin(o.rotation))<o.width/2+1&&Math.abs((d.x-o.x)*Math.sin(o.rotation)+(d.z-o.z)*Math.cos(o.rotation))<o.depth/2+1))return false;const p=this.locate(d.x,d.z);return Math.abs(p.lateral)>p.width/2+(d.category==='LARGE'?4:2);});if(existing!==section&&existing.decorations.length!==before){existing.decorationRevision++;this.revision++;}}populateScenery(this,section);populateFarmers(this,section);return section;}
 populateEvents(section){
 const {startDistance:start,length,type}=section,end=start+length;
 const wet=section.biomeProfile.type!=='FOREST';
 const minimum=this.sections.at(-1)?.crestSafe?OBSTACLE_CONFIG.clearLanding:OBSTACLE_CONFIG.minimumStart;
 const safe=['FAST_STRAIGHT','FAST_CURVE','FAST_S_CURVE','EXIT','BRAKING_ZONE','TECH_S_CURVE','APEX_TURN'].includes(type);
 while(this.nextEventS<end-14){const distance=Math.max(this.nextEventS,start+minimum);this.nextEventS=distance+(OBSTACLE_CONFIG.localSpacing[0]+this.random()*(OBSTACLE_CONFIG.localSpacing[1]-OBSTACLE_CONFIG.localSpacing[0]))*(wet?.78:1);if(!safe)continue;
 const combo=distance>=this.nextComboS;if(combo)this.nextComboS=distance+OBSTACLE_CONFIG.comboSpacing[0]+this.random()*(OBSTACLE_CONFIG.comboSpacing[1]-OBSTACLE_CONFIG.comboSpacing[0]);
 const choices=section.asphalt?['PUDDLE','POTHOLE','PIT','PUDDLE','POTHOLE']:['MUD_PATCH','MUD_MEDIUM','MUD_STRIP','PUDDLE','PIT','POTHOLE','ROCK','SHORT_RUT','DITCH','BUMP','SOFT_PATCH','LOG_SMALL','LOG_MEDIUM','LOG_LARGE'];
 let kind=section.asphalt?choices[Math.floor(this.random()*choices.length)]:type==='APEX_TURN'?'MUD_MEDIUM':wet&&this.random()<.55?['PUDDLE','MUD_PATCH','MUD_STRIP'][Math.floor(this.random()*3)]:choices[Math.floor(this.random()*choices.length)];const raining=this.environment?.rainIntensity||0;if(raining>.03&&kind!=='PUDDLE'&&this.random()<raining*.045)kind='PUDDLE';const count=combo?3:1,side=this.random()<.5?-1:1;
 for(let i=0;i<count;i++){const at=Math.min(end-14,distance+i*5.5),spec=OBSTACLE_CONFIG.types[kind],feature={kind,...spec,u:(at-start)/length,lateral:side*(.65+this.random()*1.1),ragged:!!spec.surfaceType,phase:this.random()*6.28};
 if(kind==='PUDDLE'){feature.radius=.65+this.random()*1.15;feature.longRadius=1+this.random()*1.6;feature.radius=Math.min(feature.radius*(1+raining*.40),section.width*.31);feature.longRadius*=1+raining*.45;feature.lateral=Math.sign(feature.lateral)*Math.min(Math.abs(feature.lateral),Math.max(.2,section.width/2-feature.radius-.35));feature.waterDepth=[.045,.12,.24][Math.floor(this.random()*3)];feature.height=-feature.waterDepth;}
 section.localFeatures.push(feature);if(kind==='PUDDLE'&&raining>.03&&this.random()<raining*.85&&section.localFeatures.length<OBSTACLE_CONFIG.maxFeatures){section.localFeatures.push({...feature,u:Math.min((end-14-start)/length,feature.u+4.5/length),lateral:-feature.lateral*.7,phase:feature.phase+1.7,radius:feature.radius*.80,longRadius:feature.longRadius*.75,waterDepth:Math.min(.16,feature.waterDepth),height:-Math.min(.16,feature.waterDepth)});if(this.random()<raining*.22&&section.localFeatures.length<OBSTACLE_CONFIG.maxFeatures)section.localFeatures.push({...feature,u:Math.min((end-14-start)/length,feature.u+8/length),radius:feature.radius*.50,longRadius:feature.longRadius*.60,lateral:feature.lateral*.85,phase:feature.phase+3.1,waterDepth:.06,height:-.06});}}
 }
 }
 populateParking(section){
 const biome=section.biomeProfile.type;if(biome==='FOREST'||section.crestSafe||section.id<4||this.random()>(biome==='VILLAGE'?.27:.18))return;
 const u=.35+this.random()*.3,p=this.point(section,u),side=this.random()<.5?-1:1,lateral=side*(section.width/2+3.7),npcType=biome==='FIELD'?'TRACTOR':this.random()<.55?'NIVA':'KOPEIKA',width=npcType==='TRACTOR'?2.05:npcType==='NIVA'?1.75:1.64,depth=npcType==='TRACTOR'?3.65:npcType==='NIVA'?3.8:4.05;
 const x=p.x+Math.cos(p.yaw)*lateral,z=p.z-Math.sin(p.yaw)*lateral;
 if(section.decorations.some(d=>Math.hypot(x-d.x,z-d.z)<5))return;
 section.decorations.push({kind:'parked',npcType,colorIndex:Math.floor(this.random()*4),x,z,y:this.height(x,z),rotation:p.yaw+(side<0?Math.PI:0),width,depth,height:npcType==='TRACTOR'?2.7:1.8,broken:false});
 }
 indexSegments(){this.bins.clear();for(const section of this.sections)for(let i=0;i<section.nodes.length-1;i++){const a=section.nodes[i],b=section.nodes[i+1],entry={section,i,a,b};for(let cell=Math.floor((b.z-52)/12);cell<=Math.floor((a.z+52)/12);cell++){if(!this.bins.has(cell))this.bins.set(cell,[]);this.bins.get(cell).push(entry);}}this.zMin=Math.min(...this.bins.keys());this.zMax=Math.max(...this.bins.keys());this.binsDirty=false;}
 locate(x,z){if(this.binsDirty)this.indexSegments();let best=null,distance=Infinity;const candidates=this.bins.get(Math.floor(z/12))||(this.finiteRace?this.bins.get(clamp(Math.floor(z/12),this.zMin,this.zMax)):null)||[...this.bins.values()].flat();for(const {section,i,a,b} of candidates){const dx=b.x-a.x,dz=b.z-a.z,t=clamp(((x-a.x)*dx+(z-a.z)*dz)/(dx*dx+dz*dz),0,1),cx=a.x+dx*t,cz=a.z+dz*t,d=(x-cx)**2+(z-cz)**2;if(d<distance){distance=d;const yaw=a.yaw+(b.yaw-a.yaw)*t;best={section,t,index:i,x:cx,z:cz,y:a.y+(b.y-a.y)*t,yaw,width:a.width+(b.width-a.width)*t,u:a.u+(b.u-a.u)*t,s:a.s+(b.s-a.s)*t,lateral:(x-cx)*Math.cos(yaw)-(z-cz)*Math.sin(yaw)};}}return best;}
 update(x,z){const point=this.locate(x,z);this.current=point.section;this.distance=Math.max(this.distance,point.s-18);while(this.sections.at(-1).id<this.current.id+ROAD_CONFIG.ahead)this.append();while(this.sections.length>ROAD_CONFIG.activeSections&&this.sections[0].id<this.current.id-ROAD_CONFIG.behind)this.sections.shift(),this.binsDirty=true;return point;}
 localHeight(section,u,lateral){let h=0;for(const o of [...section.obstacles,...section.localFeatures])h+=o.height*obstacleWeight(o,u,lateral,section.length);if(section.type==='RUTS')h-=.115*envelope(u)*(Math.exp(-((((lateral-.84)/.40)**2)))+Math.exp(-((((lateral+.84)/.40)**2))));return h*envelope(u);}
 height(x,z){const p=this.locate(x,z),outside=Math.max(0,Math.abs(p.lateral)-p.width/2);return p.y+this.localHeight(p.section,p.u,p.lateral)+.025*outside+.12*Math.sin(p.lateral*.2)**2*smooth(outside/5);}
 normal(x,z){const h=.08,a=this.height(x-h,z)-this.height(x+h,z),b=this.height(x,z-h)-this.height(x,z+h),length=Math.hypot(a,2*h,b);return[a/length,2*h/length,b/length];}
 surface(x,z){return this.surfaceAt(this.locate(x,z));}
 surfaceAt(p){const env=Math.sin(Math.PI*p.u)**2,edge=Math.abs(p.lateral),onRoad=edge<p.width/2;let surfaceType=onRoad?(p.section.surface||'DIRT'):'GRASS',mudDepth=0,waterDepth=0;
 for(const o of p.section.localFeatures){const weight=obstacleWeight(o,p.u,p.lateral,p.section.length);if(onRoad&&weight>.12&&o.surfaceType){surfaceType=o.surfaceType;mudDepth=Math.max(mudDepth,(o.mudDepth||0)*weight);waterDepth=Math.max(waterDepth,(o.waterDepth||0)*weight);}}
 if(onRoad&&['ROCK_SECTION','CHICANE'].includes(p.section.type))surfaceType='ROCK';const c={...SURFACE_CONFIG[surfaceType]};if(surfaceType==='ASPHALT'){const blend=asphaltBlend(p.section,p.u);for(const key of Object.keys(c))c[key]=SURFACE_CONFIG.DIRT[key]+(c[key]-SURFACE_CONFIG.DIRT[key])*blend;}if(surfaceType==='MUD'){c.longitudinalGrip*=1-SURFACE_SETTINGS.mudGripLoss*mudDepth;c.lateralGrip*=1-.45*mudDepth;c.rollingResistance+=SURFACE_SETTINGS.mudResistance*mudDepth;c.sinkAmount=Math.min(.10,c.sinkAmount*mudDepth);}if(surfaceType==='WATER')c.rollingResistance+=waterDepth*SURFACE_SETTINGS.waterResistance;const offroadFactor=onRoad?0:smooth((edge-p.width/2)/SURFACE_SETTINGS.offroadShoulderBlend);const result={surfaceType,mudDepth,waterDepth,offroadFactor,...c};return this.environment?this.environment.surface(result):result;}
 visualMaterial(section,u,lateral){for(const o of section.localFeatures){if(obstacleWeight(o,u,lateral,section.length)>.15)return o.kind.startsWith('LOG_')?'WOOD':o.kind==='ROCK'?'HAZARD_ROCK':['PIT','POTHOLE','SHORT_RUT','DITCH'].includes(o.kind)?'PIT':o.kind==='BUMP'?'EARTH_BUMP':o.surfaceType==='MUD'?'MUD':o.surfaceType||'DIRT';}return this.surfaceAt({section,u,lateral,width:section.nodes[Math.min(section.nodes.length-1,Math.floor(u*(section.nodes.length-1)))].width}).surfaceType;}
 point(section=this.current,u=.15){u=clamp(u,0,1);let lo=0,hi=section.nodes.length-1;while(hi-lo>1){const mid=(lo+hi)>>1;if(section.nodes[mid].u<=u)lo=mid;else hi=mid;}const a=section.nodes[lo],b=section.nodes[hi],t=(u-a.u)/(b.u-a.u);return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t,yaw:a.yaw+(b.yaw-a.yaw)*t,width:a.width+(b.width-a.width)*t};}

 shift(dx,dz){for(const s of this.sections){for(const n of s.nodes){n.x-=dx;n.z-=dz;}for(const tr of [s.entryTransform,s.exitTransform,...s.decorations,...(s.visualDecor||[])]){tr.x-=dx;tr.z-=dz;}}this.offset[0]+=dx;this.offset[1]+=dz;this.revision++;this.binsDirty=true;}
}
