import {biomeWeights} from './biomes.js?v=026';
export const SCENERY_CONFIG={maxPerSection:240,grassGroups:95,forestMiddle:26,forestFar:34,horizonGroups:18,nearDecorationDistance:125,midDecorationDistance:260};
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};}
// Separate random stream: dressing never consumes the road/obstacle/traffic seed stream.
export function populateScenery(world,section){const r=rng(world.seed^Math.imul(section.id+1,0x165667b1)),items=section.visualDecor=[];
 function add(kind,u,lateral,extra={}){if(items.length>=SCENERY_CONFIG.maxPerSection)return;const p=world.point(section,u),x=p.x+Math.cos(p.yaw)*lateral,z=p.z-Math.sin(p.yaw)*lateral,q=world.locate(x,z);if(Math.abs(q.lateral)<q.width/2+1)return;if(Math.abs(lateral)<35&&section.decorations.some(d=>['house','hay','parked'].includes(d.kind)&&Math.hypot(d.x-x,d.z-z)<Math.hypot(d.width,d.depth)/2+1.2))return;items.push({kind,x,z,y:world.height(x,z),rotation:['gate','well','busStop','shed','canopy'].includes(kind)?p.yaw:r()*6.28,scale:.65+r()*.75,variant:Math.floor(r()*3),...extra});}
 for(let i=0;i<SCENERY_CONFIG.grassGroups;i++){const u=.03+r()*.94,node=section.nodes[Math.floor(u*(section.nodes.length-1))],side=r()<.5?-1:1,offset=node.width/2+.8+Math.pow(r(),1.7)*26,weights=biomeWeights(section.biomeProfile,node.s);if(r()>.65+weights.FIELD*.30)continue;add('grass',u,side*offset,{variant:offset-node.width/2<2?0:weights.FIELD>.4&&r()<.55?2:1,scale:.6+r()*.8,field:weights.FIELD});}
 for(let i=0;i<14;i++){const u=.06+r()*.88,node=section.nodes[Math.floor(u*(section.nodes.length-1))],weights=biomeWeights(section.biomeProfile,node.s),side=r()<.5?-1:1;add(r()<.6?'scrub':weights.FOREST>.5?r()<.5?'stump':'deadwood':'scrub',u,side*(node.width/2+3+r()*19),{field:weights.FIELD});}
 for(let i=0;i<SCENERY_CONFIG.forestMiddle+SCENERY_CONFIG.forestFar;i++){const u=.01+r()*.98,node=section.nodes[Math.floor(u*(section.nodes.length-1))],weights=biomeWeights(section.biomeProfile,node.s),side=i%2?-1:1,far=i>=SCENERY_CONFIG.forestMiddle;if(r()>(weights.FOREST*.97+weights.FIELD*.23+weights.VILLAGE*.10))continue;add(far?'treeFar':'treeMiddle',u,side*(far?70+r()*60:38+r()*22),{scale:4.5+r()*4,variant:Math.floor(r()*3)});}
 for(let i=0;i<SCENERY_CONFIG.horizonGroups;i++){const u=r(),node=section.nodes[Math.floor(u*(section.nodes.length-1))],weights=biomeWeights(section.biomeProfile,node.s),side=i%2?-1:1;add('horizon',u,side*(155+r()*110),{scale:12+r()*20,variant:weights.FOREST>.5?0:1});}
 const profile=section.biomeProfile.type;
 if(profile==='VILLAGE'){for(const u of [.20,.65]){const side=r()<.5?-1:1;add('gate',u,side*(section.width/2+6.1));add('pole',u+.05,side*(section.width/2+8.5));}add('well',.43,-(section.width/2+9));if(section.id%3===0)add('busStop',.72,section.width/2+8);if(section.id%2===0)add('shed',.35,-(section.width/2+22));if(section.id%4===0)add('canopy',.56,section.width/2+17);}
 else if(profile==='FIELD'&&r()<.45)add('pole',.3+r()*.4,(r()<.5?-1:1)*(section.width/2+9));
 return items;
}
